Partially rewrite external message handler
pixiebrix/pixiebrix-extension pull request #1019
Opened 2021-08-08 19:15 UTC by fregante

Core changes:

- it ensures that the messages aren't just lost into the void: Every message has to ping back or else it will fail just like `chrome.runtime.sendMessage` does.
- avoids passing of serialized errors as described in https://github.com/pixiebrix/pixiebrix-extension/issues/580
- refactors the file to linearize the sequence of events: send, await response, return response/error

---

Before review:

- [ ] It depends on https://github.com/pixiebrix/pixiebrix-extension/pull/1016
- [ ] Needs more testing, especially against a mismatched app
- [ ] Self-review

Interim solution to some issues described in:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1015

Replaces an old unmerged PR: https://github.com/pixiebrix/pixiebrix-extension/pull/950

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +    });
This is the pingback to ensure that the message has been delivered even for notifications.

2021-08-09 04:22 UTC, fregante commented on src/contentScript.ts
> -  addExternalListener();
Leaky abstraction, the lifter now sets up its own listener when and if it's called.

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
> -const rejectedSuffix = "_REJECTED";
These suffixes have been dropped since `isErrorResponse` is already able to detect errors.

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +const RESPONSE_TIMEOUT = 2000; // XXX: Might need to be longer
This depends on the handler itself. If the handler includes a `sleep(3000)` this will fail. Better solutions to this will be in #1015, like an immediate data-less pingback ([ACK](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_establishment)) regardless of result, which would make it an exact equivalent of how `sendMessage` internally works.

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +async function oneResponse<R>(nonce: string): Promise<R> {
This is the core of the change.

It only handles a single message, as described, so it can be used as a promise in the sender’s function itself. This essentially hides one part of the messaging behind a single promise and makes it a bit clearer that this communication is one-way **from the app.** Hence the name "one response", not "one message"

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
>    return async (...args: TArguments) => {
This function is now linear just like the other lifters: it starts here and it passes/handles the CS response locally. Previously this was split between this function and the `message` listener

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +export default () => {};
After we revert https://github.com/pixiebrix/pixiebrix-app/pull/339/files, this export can also be dropped

2021-08-09 04:22 UTC, fregante commented on src/contentScript/externalProtocol.ts
>  const POLL_READY_TIMEOUT = 2000;
This PR now exposes an annoying "bug" that might occur when the dev tools are open. Instead of being ready in 100ms, the script might take 3000 or 6000ms to resolve. It could be avoided in:

- #1015 


Here's what happens in detail:

1. This times out
2. The content script becomes ready 1.4s later


https://user-images.githubusercontent.com/1402241/128660060-893aeb5e-0014-4d5a-8aba-caba4ed6d8ae.mov

2021-08-10 02:12 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +const RESPONSE_TIMEOUT = 2000; // XXX: Might need to be longer
NIT: include the unit in the variable name `RESPONSE_TIMEOUT_MS`

2021-08-10 02:13 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +  payload: unknown[];
Long term, we should probably move the payload to just `unknown`. This array approach is very RPC-esque where the payload is the args to the remote procedure

2021-08-10 02:15 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +  isResponse: true;
Add a comment for why `isResponse: true;` is necessary? In what case would the listener receive an object with the correct nonce that's not a response?

2021-08-10 02:17 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +interface MessageResponse<R> {
`MessageRepsonse<R = unknown>`? The plumbing code will be payload agnostic, so might as well default it

2021-08-10 02:18 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +  message: PostedMessage | MessageResponse<unknown>
This terminology is pretty confusing -- the MessageResponse is also a message? It probably makes sense to create a common base class of Message?

2021-08-10 02:20 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    });
Please include this as a comment in the code. It's non-obvious that that is what this is

2021-08-10 02:21 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +  isResponse: true;
I think it'd make sense to put isResponse as a property in `meta` instead of on the body of the message

2021-08-10 02:21 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +async function onLifterMessage(
Call it `onContentScriptMessage`?

2021-08-10 02:24 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    });
Should this be a `.finally` on handler?

2021-08-10 02:27 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +        document.defaultView.removeEventListener("message", onMessage);
This needs to be in `finally` to ensure it actually gets removed if resolve throws an exception. It also wouldn't hurt to call this before the resolve.

2021-08-10 02:30 UTC, twschiller commented on src/contentScript/externalProtocol.ts
>  const POLL_READY_TIMEOUT = 2000;
> This PR now exposes an annoying "bug" that might occur when the dev tools are open

This is a developer ergonomics bug, as it only applied to dev tools on our app.pixiebrix?

2021-08-10 02:31 UTC, twschiller requested changes
See comments about using `finally` in a couple places. We'll also need to transfer some of the comments from the PR to the code, as certain spots aren't obvious

2021-08-10 09:28 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +    });
Yeah this piece was added at the last moment, I realized I could refactor the code a bit to have a single `sendMessageToOtherSide` call in every case. 

However what do you mean by "the handler might never return"? Functions should probably always return (other than generators). "Not returning" sounds like there's a `new Promise` without `resolve` call, which would be an anti pattern.

I'm currently treating `asyncResponse === false` as _"Don't bother passing the result back"_

2021-08-10 09:31 UTC, fregante commented on src/contentScript/externalProtocol.ts
>  const POLL_READY_TIMEOUT = 2000;
In theory yes, but users also potentially open the dev tools since the Editor lives there. I'll place a warning comment in the code so we don't lose track of this.

2021-08-10 09:49 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +  isResponse: true;
> In what case would the listener receive an object with the correct nonce that's not a response?

Unfortunately we're posting the message to the same page/window so, after we post it, `onMessage` is immediately called in the same context (the unsafe context). We need a way to tell apart the message we just sent from the response it receives from the content script.

However there's already a differentiating property here: Responses don't have a `type`, so I'll drop `isReponse` and use that. I'll leave a comment in the code.

2021-08-10 09:57 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +  payload: unknown[];
But that's what we're doing, the `payload` is spread as parameters of `handler`: https://github.com/pixiebrix/pixiebrix-extension/blob/988dbc131ba9300ce85065dc96332021bf07779a/src/contentScript/externalProtocol.ts#L111

I changed it to `unknown` anyway to allow merging the 2 message types and then placed a `isArray` as a type guard.

2021-08-10 10:01 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +        document.defaultView.removeEventListener("message", onMessage);
I moved the `remove` higher, however for future reference `resolve` would never throw, it's the equivalent of:

```js
promise.value = event.data.payload;
promise.state = 'resolved'
nextTick(thenCallback)
```

`event.data` is also guaranteed to exist by the condition.

2021-08-10 13:59 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +  type?: string; // Responses *must not* include a `type`
If this is the case I think it's clearer to use 2 separate types, e.g., Message and Response, where Response doesn't have the type property on it. Let's use the type system to enforce the property instead of a code comment

2021-08-10 14:09 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    response = await handler(...payload);
What I don't like about this is, if the handler for the notification is "infinite loop" then sender will never get the pingback

It's probably fine in our current code. But to be robust, one of the following patterns must hold: 1) the notifier doesn't await/block on the pingback, 2) the notifyee sends the pingback immediately before doing its work

2021-08-10 14:10 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +      // Responses *must not* have a `type`, but just a `nonce` and `payload`
Let's enforce this through the type system, not code comments: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

2021-08-10 14:15 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +        document.defaultView.removeEventListener("message", onMessage);
I think you're correct that in this case since it's only used internally it's fine

Your pseudo code still looks like it would throw if `thenCallback = () => throw`, and would never return if `thenCallback = () => while {true}`

2021-08-10 14:18 UTC, twschiller approved these changes
I encourage you to separate the Message and Response into two separate types to make the invariant on `type` explicit instead of implicit/captured via comments

Also see comment about awaiting handler for notifications. I think it's fine in our current code, but waiting on the handler before performing a pingback I think is a bad idea

2021-08-10 14:56 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    });
> Functions should probably always return

There's definitely some places in our code where a promise never returns (e.g., waiting for an element on a page to place a menu that never appears (e.g., because it's in a modal the user never accesses))

In our infrastructure code, a general philosophy will be to defensive and minimize the number of foot guns

2021-08-10 16:29 UTC, merged