Show config for blocks in the reference tab #1058
pixiebrix/pixiebrix-extension pull request #1177
Opened 2021-08-24 10:04 UTC by BALEHOK

2021-08-24 10:19 UTC, BALEHOK commented on package.json
> +    "identity-obj-proxy": "^3.0.0",
to mock CSS modules

2021-08-24 10:19 UTC, BALEHOK commented on src/options/pages/brickEditor/BrickReference.tsx
> -const BrickDetail: React.FunctionComponent<{ brick: ReferenceEntry }> = ({
moved to a new file

2021-08-24 10:22 UTC, BALEHOK commented on src/testHelpers.ts
> +  });
empty `act`. must be called and awaited for the test to work properly with state updates by `useEffect` hook

2021-08-24 12:42 UTC, twschiller commented
On the UI side of things, we'll want to:

1. Make the brick detail side of the card scroll on overflow. The intention is for the search results on the left to be full height if there's enough content there
2. Make the YAML definition display the full width (IIRC, you'll probably need to use a layout effect here as AceEditor doesn't support it natively)

I'm seeing some scroll flashing when I'm scrolled down in the window and click between bricks. I think #1 above will fix that

![image](https://user-images.githubusercontent.com/1879821/130617836-5139585d-a636-49f9-b81e-a88301dbce94.png)

2021-08-24 12:43 UTC, twschiller commented on src/testHelpers.ts
> +  });
Let's create a tests subdirectory?

2021-08-24 12:46 UTC, twschiller commented on src/utils/objToYaml.ts
> +function orderKeys<T extends Record<string, unknown>>(
Rewrote as a generic helper method

2021-08-24 12:53 UTC, twschiller requested changes
Looking good overall! See comment on the layout issue

2021-08-24 16:46 UTC, BALEHOK commented on src/options/pages/brickEditor/BlockResult.module.scss
> +.titleColumn {
this is a new SCSS file.
`BrickReference.scss` is converted to a module `BrickReference.module.scss`

2021-08-24 16:48 UTC, BALEHOK commented on src/options/pages/brickEditor/BlockResult.tsx
> +        <div className="flex-grow-0 BlockResult__badges">
@twschiller I'm not sure if `BlockResult__badges` class is actually needed?

2021-08-24 16:52 UTC, BALEHOK commented on src/testHelpers.ts
> +  });
there is a `tests` directory under `src` with `ConsoleLogger.ts` and `errors.test.ts`. not sure what are they. @twschiller Do you think I can put the `helpers` into this directory?

2021-08-24 18:30 UTC, twschiller commented on src/options/pages/brickEditor/BlockResult.tsx
> +        <div className="flex-grow-0 BlockResult__badges">
I think you're right. The only reference to `__badges` I see is in an unrelated class: http://github.com/pixiebrix/pixiebrix-extension/blob/27855d8c6d0ffed1b1f05aae9376777dc9656159/src/components/fields/BlockModal.scss#L26-L26

IIRC, this code was copied over from code I used in a search modal. It looks like it's a margin fix for the line height issue we say earlier:

```scss
  &__badges {
    margin-top: -2px;
  }
```

2021-08-24 18:31 UTC, twschiller commented on src/options/pages/brickEditor/BrickReference.module.scss
> +  :global {
TIL: https://github.com/css-modules/css-modules/issues/264#issuecomment-609067219

2021-08-24 18:34 UTC, twschiller requested changes
Looks good! Just a couple UI quirks left:

1. The scroll bar for the BrickDetail somehow is rendered to the right of it?
2. Would it be possible to have the Definition YAML display be the full width of the BrickDetail? See here for how I had done it on the Edit page: http://github.com/pixiebrix/pixiebrix-extension/blob/27855d8c6d0ffed1b1f05aae9376777dc9656159/src/options/pages/brickEditor/Editor.tsx#L137-L137

![image](https://user-images.githubusercontent.com/1879821/130670797-ed31c1a9-cc6c-4e3a-81a4-207f60e3233b.png)

2021-08-25 09:22 UTC, BALEHOK commented
> Looks good! Just a couple UI quirks left:
> 
> 1. The scroll bar for the BrickDetail somehow is rendered to the right of it?
> 2. Would it be possible to have the Definition YAML display be the full width of the BrickDetail? See here for how I had done it on the Edit page: [http://github.com/pixiebrix/pixiebrix-extension/blob/27855d8c6d0ffed1b1f05aae9376777dc9656159/src/options/pages/brickEditor/Editor.tsx#L137-L137](https://github.com/pixiebrix/pixiebrix-extension/blob/27855d8c6d0ffed1b1f05aae9376777dc9656159/src/options/pages/brickEditor/Editor.tsx#L137-L137)

Fixes for these issues are in PR https://github.com/pixiebrix/pixiebrix-extension/pull/1189
I've also refactored styles a little bit there.

2021-08-25 14:49 UTC, twschiller commented on src/options/pages/brickEditor/isOfficial.tsx
> +export function isOfficial(block: ReferenceEntry): boolean {
This should probably go here? http://github.com/pixiebrix/pixiebrix-extension/blob/85eec6e67f4a55acc4203ede92c2b985f4477a39/src/blocks/util.ts#L1-L1

Since it will will be useful in other places as well, not just the brick editor

Then the type should just be `{ id: RegistryId }`

2021-08-25 14:49 UTC, twschiller approved these changes
See comment about moving isOfficial to a shared location

2021-08-25 16:06 UTC, merged