#1202: Add support for calling remote bricks
pixiebrix/pixiebrix-extension pull request #1205
Opened 2021-08-30 11:00 UTC by umair-pixiebrix

2021-08-30 15:07 UTC, twschiller commented on src/background/executor.ts
> +  async (blockId: string, blockArgs: RenderedArgs) => {
Let's use the RegistryId type from `core.ts` for the blockId

2021-08-30 15:09 UTC, twschiller commented on src/blocks/combinators.ts
> +        return (await executeOnServer(stage.id, blockArgs)).data;
This `data` is the data field of the AxiosResponse? Correct? Shouldn't it be data.data?

2021-08-30 15:09 UTC, twschiller commented on src/background/executor.ts
> +export const executeOnServer = liftBackground(
We shouldn't have AxiosResponse objects crossing component boundaries. Let's return the actual data returned from the response

2021-08-30 15:11 UTC, twschiller commented on src/background/executor.ts
> +export const executeOnServer = liftBackground(
How is the `data.error` property from running on the server handled? See "Response Body (status 200)": https://github.com/pixiebrix/pixiebrix-app/issues/307

2021-08-30 15:12 UTC, twschiller requested changes
See comment about not passing AxiosResponses across component boundaries, and the question on the error property

2021-08-30 16:12 UTC, umair-pixiebrix commented on src/blocks/combinators.ts
> +        return (await executeOnServer(stage.id, blockArgs)).data;
Yeah. I changed in backend as well. Let me revert.

2021-08-31 11:31 UTC, BALEHOK commented on src/blocks/combinators.ts
> +          // TODO: Determine type of error
I'd suggest implementing the functionality or creating an Issue. A `TODO` often just lives in code abandoned and nobody knows how/when to deal with it.

2021-08-31 12:33 UTC, umair-pixiebrix commented on src/blocks/combinators.ts
> +          // TODO: Determine type of error
Good idea @BALEHOK. I have added the link of the issue in the comment. https://github.com/pixiebrix/pixiebrix-extension/issues/1227

2021-09-01 00:29 UTC, twschiller commented on src/blocks/errors.ts
> +    this.name = "PipelineConfigurationError";
This name needs to match the class name RemoteExecutionError

2021-09-01 00:35 UTC, twschiller commented on src/background/executor.ts
> +    return (await getLinkedApiClient()).post("/api/run/", {
Annotate post with a type. E.g., regenerate the swagger.ts so you can refer to the type, or just annotate it yourself here

```
post<{data?: JsonObject, error?: JsonObject}>
```

2021-09-01 00:36 UTC, twschiller requested changes
Fix RemoteExecutionError class definition
Add return type to post call

2021-09-01 12:33 UTC, twschiller commented on src/blocks/errors.ts
> +  readonly errors: OutputUnit[];
@umair-pixiebrix Let's make this `error: unknown` until we land on the error format. There may be other errors aside from input validation errors

2021-09-01 12:33 UTC, twschiller commented on src/blocks/combinators.ts
> +        const { data, errors } = (
Use singular `error` of type unknown

2021-09-01 12:34 UTC, twschiller requested changes
For the error, let's have it be `error: unknown`. There will be other other types of errors aside from input validation errors (which have the outputunit type)

2021-09-01 13:33 UTC, umair-pixiebrix commented on src/blocks/errors.ts
> +  readonly errors: OutputUnit[];
I have used `JsonObject` @twschiller

2021-09-01 13:34 UTC, umair-pixiebrix commented
> For the error, let's have it be `error: unknown`. There will be other other types of errors aside from input validation errors (which have the outputunit type)

Does `JsonObject` work?

2021-09-01 14:48 UTC, twschiller approved these changes

2021-09-01 14:49 UTC, twschiller commented
@umair-pixiebrix Could you resolve the merge conflict and then merge?

2021-09-01 15:21 UTC, merged