Open sidebar in new tab instead of throwing error
pixiebrix/pixiebrix-extension pull request #1395
Opened 2021-09-20 17:29 UTC by fregante

- Fixes #1334 

# Before

https://user-images.githubusercontent.com/1402241/134046916-66587f9e-90f0-40c4-bc09-8e3dca4b2145.mov

# After

https://user-images.githubusercontent.com/1402241/134047030-e64bbde1-2404-4b78-9b5f-c32e9270089a.mov

2021-09-20 17:31 UTC, fregante commented on src/actionPanel/native.tsx
> +    `<div id="${PANEL_CONTAINER_ID}" data-nonce="${nonce}" style="height: 100%; margin: 0; padding: 0; border-radius: 0; width: ${SIDEBAR_WIDTH_PX}px; position: fixed; top: 0; right: 0; z-index: 2147
I moved the border from the CSS file because now it's used to constrain action.html to a sidebar even when it's opened on its own

2021-09-20 18:47 UTC, twschiller commented
@fregante Mike will be the best person for helping decide if the interaction makes sense. I can help review from a code perspective

2021-09-20 18:57 UTC, fregante commented
One issue: this button does nothing because the sidebar does not live in an iframe, so it can't be closed:

<img width="81" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/134057230-d37929d4-9c94-4cef-9a3d-806e5cacc05c.png">

I also attempted to show the iframe in the options page, but it doesn't work due to some backlog stuff (https://github.com/fregante/webext-detect-page/issues/9 and possibly more). I'm not sure if https://github.com/pixiebrix/pixiebrix-extension/issues/430#issuecomment-890961400 would have affected this.

Anyway, maybe we could just hide the toggle in this case.

2021-09-20 19:35 UTC, fregante commented
> One issue: this button does nothing

Fixed: Button is only shown if the sidebar is a regular iframe



https://user-images.githubusercontent.com/1402241/134063296-6c5c03e1-29ab-4d3d-befd-7ef30ed5e179.mov

2021-09-22 13:55 UTC, twschiller commented
The behavior of opening a blank tab with the sidebar makes it look broken/buggy to me. Also, no sidebar panels will generally be available on that page, so the sidebar will also be empty with a "no available panels message"

![image](https://user-images.githubusercontent.com/1879821/134356097-5b9c803a-6677-4cb8-afad-8ee3087b2d55.png)

The relevant user stories for accessing the options page are:
1. As an enterprise team member I need to open the active bricks page to activate deployments assigned to me
2. As an enterprise team member I need to open the my blueprints page to activate the blueprints shared with me
3. As a developer, I need to open the workshop to create/edit a brick

On the special pages, I don't think the user is clicking the icon with the hopes of viewing panels in the sidebar (since there won't be any).

My vote is probably just to open (a new tab, or an existing tab) to the options page. @MMirandi thoughts?

2021-09-22 13:57 UTC, twschiller requested changes
See comment

2021-09-22 16:11 UTC, fregante commented
> @fregante Is there something I'm missing here where this situation also comes up with the devtools/page editor somehow?

I think you're referring to:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1005

> My vote is probably just to open (a new tab, or an existing tab) to the options page. (And maybe not even show an error message) @MMirandi thoughts?

Sounds fine to me

2021-09-27 15:32 UTC, fregante commented
I opened a new PR because the solution is completely different

2021-09-27 15:32 UTC, closed without merging