#1475 Collapsable sidebar
pixiebrix/pixiebrix-extension pull request #1548
Opened 2021-09-30 19:30 UTC by BALEHOK

Closes #1475 

![image](https://user-images.githubusercontent.com/3116723/135518564-e04851f9-dff9-4646-870e-e6ac7a2f0e3e.png)

![image](https://user-images.githubusercontent.com/3116723/135518595-c03f105d-af58-4346-bbb4-60781ed5f5ef.png)

2021-09-30 21:51 UTC, fregante commented
Note: the diff is huge, npm is having issues

2021-10-01 08:50 UTC, BALEHOK commented
> Note: the diff is huge, npm is having issues

It is.
Btw, `resolutions` in `package.json` is not something that is officially supported by npm.
https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions
https://github.com/npm/statusboard/issues/343

@twschiller I believe should not use (or try to use) unsupported and unstable features and remove it or migrate to `yarn`.

2021-10-01 09:07 UTC, fregante commented
https://github.com/pixiebrix/pixiebrix-extension/issues/1549#issuecomment-932056179

2021-10-01 16:55 UTC, fregante commented on package.json
> +    "react-transition-group": "^4.4.2",
@BALEHOK once https://github.com/pixiebrix/pixiebrix-extension/pull/1553 is merged, you can try reverting the changes to the lockfile, using `git merge origin/main`, and then running `npm install` to update the lockfile

2021-10-05 15:17 UTC, BLoe requested changes
Hey, I'm seeing a UI issue where the footer doesn't pin to the bottom of the side bar:

![image](https://user-images.githubusercontent.com/2801308/136051995-9d2d4871-ddae-4175-b546-2d749590f741.png)

2021-10-05 17:51 UTC, BLoe approved these changes

2021-10-05 18:22 UTC, merged