#1020: Input field type toggles
pixiebrix/pixiebrix-extension pull request #1768
Opened 2021-10-29 19:55 UTC by BLoe

This PR implements "toggle" inputs on input fields in block configs in the page editor so that a user can choose which type of data is being entered, either a raw literal of some data type, a "wired-up" data variable reference, or a template string.

![image](https://user-images.githubusercontent.com/2801308/139494020-e1fe25c7-2b38-4203-94bc-13a11f0cbcba.png)

![image](https://user-images.githubusercontent.com/2801308/139494142-5fbcb073-9b90-4777-99a1-d2c42426a294.png)

2021-11-05 01:24 UTC, twschiller commented on src/components/fields/fieldUtils.ts
> +export function useApiVersion(): ApiVersion {
This is very specific to the state of the page editor. It should not go in our generic field utils

2021-11-05 01:26 UTC, twschiller commented on src/components/fields/fieldUtils.ts
> +export function useApiVersion(): ApiVersion {
This method is only used in useApiVersionAtLeast. There's no reason to export it? And it can also just be merged into useApiVersionAtLeast

2021-11-05 01:27 UTC, twschiller commented on src/components/fields/schemaFields/BooleanField.tsx
> +      as={SwitchButtonWidget} // Do not use layout="switch" by default
> Do not use layout="switch" by default

Please clarify: why not?

2021-11-05 01:33 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +  fieldSchema: Schema,
This signature is very error prone since it includes multiple arguments of the same type (boolean) 

In cases like these it's best to have the function destructure an object so we get named arguments. (And since the names are generally the same in the caller, it can be called with object short hand

2021-11-05 01:35 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +        label: "Handlebars template",
As mentioned in our meeting, we can exclude Handlebars since it doesn't work with variable that start with an "@" prefix because it uses that prefix for control flow

2021-11-05 01:38 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +  if (fieldSchema.oneOf?.length > 0) {
This looks like it's a duplicate of the one above? Merge them into a single loop 

```
for (const x of [...(fieldSchema.anyOf ?? []), ...(fieldSchema.oneOf ?? [])]) {
  
}
```

2021-11-05 01:39 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +  function pushOpts(...opts: InputModeOption[]) {
NIT: don't abbreviate when the difference is 3-4 letters

2021-11-05 01:40 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +      symbol: "🗑",
As discussed, let's use a difference icon. If you want to use unicode, you could use × or similar

2021-11-05 01:41 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +  const useLegacyFields = !useApiVersionAtLeast("v3");
Negating a hook is wacky

2021-11-05 01:43 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +  const useLegacyFields = !useApiVersionAtLeast("v3");
I would probably just check this first and split into 2 sub components: 1) LegacySchemaField, and 2) ToggleSchemaField

This will help you avoid some of the wacky checks on useLegacyFields

2021-11-05 01:44 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.tsx
> +    inputModeOptions,
Should this only default on initial mount? If so, we can just use a blank `[]` dependency list

2021-11-05 01:47 UTC, twschiller commented on src/components/fields/schemaFields/SelectorSelectorField.tsx
> +  const displayLabel = noLabel ? undefined : label ?? fieldLabel(name);
Mixing ternary and nullish coalescing operator is really hard to read (which takes precedence). Add parens or split into 2 statements if prettier is removing the parens

2021-11-05 01:49 UTC, twschiller commented on src/components/fields/schemaFields/fieldInputMode.ts
> +  const hasField = fieldName in fieldConfig;
Technically this should be Object.prototype.hasOwnProperty.call(fieldConfig, fieldName)

2021-11-05 01:51 UTC, twschiller commented on src/components/fields/schemaFields/fieldInputMode.ts
> +  if (Array.isArray(value)) {
Would be helpful to add a comment here that isArray check has to come before the typeof checks because arrays have type object

2021-11-05 01:53 UTC, twschiller commented on src/components/fields/schemaFields/propTypes.ts
> +  noLabel?: boolean;
Why not call hideLabel?

2021-11-05 01:53 UTC, twschiller commented on src/components/fields/schemaFields/propTypes.ts
> +   * Is this field a nested object property?
Would be helpful to provide context for why you're tracking this

2021-11-05 01:54 UTC, twschiller commented on src/components/fields/schemaFields/propTypes.ts
> +   * Is this field an item in an array?
Would be helpful to provide context for why you're tracking this in the object.

2021-11-05 01:55 UTC, twschiller commented on src/components/fields/schemaFields/schemaFieldUtils.ts
> +  return noLabel ? undefined : label ?? title ?? fieldLabel(name);
Please don't mix ternary and null coalescing operator. I think prettier removes the parens because technically the precendence is well-defined. But it's extremely hard to read

2021-11-05 01:56 UTC, twschiller commented on src/components/fields/schemaFields/schemaFieldUtils.ts
> +  const {
Why not destructure in the method signature?

2021-11-05 01:59 UTC, twschiller commented on src/components/fields/schemaFields/widgets/LoadingWidget.tsx
> +export default LoadingWidget;
Is there any value to calling this a widget vs. WidgetLoadingIndicator or something a bit more descriptive?

2021-11-05 02:00 UTC, twschiller commented on src/components/fields/schemaFields/widgets/NumberWidget.tsx
> +const NumberWidget: React.FC = () => <Form.Control type="number" />;
Would be nice to add comment referencing the IntegerWidget to help people navigate related fields

```
/**
* @see IntegerWidget
*/
```

2021-11-05 02:02 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss
> +  width: auto !important;
I'm surprised we need to use important in SCSS modules?

2021-11-05 02:04 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +  const fieldName = name.includes(".")
Refactor into a helper method that returns tuple of the parentFieldName and fieldName

2021-11-05 02:05 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +  const parentValues = getIn(values, parentFieldName) ?? values;
Why does this default to values?

2021-11-05 02:07 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +            delete values[fieldName];
- [ ] This looks like a bug. We don't want to modify the values object. We only want to modify the draft here

2021-11-05 02:07 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +          }
Why no else here? I like to include a else which includes a comment as to why the else branch is a no-op

2021-11-05 02:09 UTC, twschiller commented on src/devTools/editor/extensionPoints/base.ts
> +export const PAGE_EDITOR_DEFAULT_BRICK_API_VERSION: ApiVersion = "v3";
I thought we were keeping this at v2 but allowing PixieBrix team members to opt into v3 via toggle in the interface

- [ ] Make page editor default controllable

2021-11-05 02:11 UTC, twschiller commented on src/hooks/useBlockOptions.ts
> +      return registered ?? genericOptionsFactory(block.inputSchema);
Why isn't inputProperties needed here? Isn't it needed to support the JS bricks using schema shorthand (where they declare properties directly instead of under a properties field?)

2021-11-05 02:13 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +  const { values, setValues } = useFormikContext<UnknownObject>();
Rename setValues (e.g., setFormValues). It's too similar to setValue.

2021-11-05 02:15 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +        const newFormState = produce(values, (draft) => {
This "delete" field would be a good helper helper method

2021-11-05 02:19 UTC, twschiller requested changes
- See comment about default page editor version
- See comment about potential bug in delete field logic
- Fix broken tests

I think those are the only 2 functional comments. Other comments are about places where documentation/refactoring/renaming would be helpful to make it easier to read and avoid errors when working with the code int he future

2021-11-05 02:25 UTC, BLoe commented on src/components/fields/schemaFields/BooleanField.tsx
> +      as={SwitchButtonWidget} // Do not use layout="switch" by default
I forget where exactly this came from, it's not something new I wrote, I'll remove it, agreed it doesn't make a lot of sense.

2021-11-05 02:46 UTC, BLoe commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss
> +  width: auto !important;
The bootstrap styles always override my modules unless I use `!important`

2021-11-05 02:51 UTC, BLoe commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +  const parentValues = getIn(values, parentFieldName) ?? values;
Because `parentFieldName` may be `undefined`, in which case there is no nesting in the field structure, so we should look directly in `values` for the property `name`.

2021-11-05 02:52 UTC, BLoe commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +            delete values[fieldName];
Nice catch!

2021-11-05 02:53 UTC, BLoe commented on src/devTools/editor/extensionPoints/base.ts
> +export const PAGE_EDITOR_DEFAULT_BRICK_API_VERSION: ApiVersion = "v3";
Yep, good catch.

2021-11-05 02:54 UTC, BLoe commented on src/hooks/useBlockOptions.ts
> +      return registered ?? genericOptionsFactory(block.inputSchema);
It's already called inside `genericOptionsFactory()`

2021-11-07 23:18 UTC, twschiller commented on src/components/fields/schemaFields/widgets/ObjectWidget.tsx
> +    !useApiVersionAtLeast("v3") && Boolean(additionalProperties);
useApiVersionAtLeast is a React hook. Let's not use as if it were it were a normal function call. E.g., if the order was swapped here React would report an error about inconsistent hook execution orders

Assign hook output to a variable and then do any boolean logic

2021-11-07 23:19 UTC, twschiller commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss
> +  width: auto !important;
@BALEHOK could you chime in here on how to use specificity/global etc to avoid using important? Or is important the right way to go here?

2021-11-07 23:23 UTC, twschiller commented
@BLoe I added some test cases as partial example of how SchemaField can be tested (at least the static rendering of it, I can also help with test the transitions between types too)

My main concern for getting this PR merged in is not having it impact v1/v2 extensions. Right now that concern is centered on getToggleOptions since the method still runs on v1/v2 extensions. IIRC, I've only see errors when toggling between entry types. But that also worries me for initial rendering as well

See comment https://github.com/pixiebrix/pixiebrix-extension/pull/1768/files#r743337368 about splitting up SchemaField in a way that doesn't execute the v3 code on v1/v2 extensions

2021-11-09 00:24 UTC, BLoe commented
@twschiller Ready for another pass. I split it into a separate v1 and v3 SchemaField component. I also split the v3 one further into a wrapper that either renders `ServiceField` or `BasicSchemaField` to eliminate another awkward boolean condition in the `useEffect()` call. Let me know if you like that or not, and further, should I keep splitting in this matter for `UnsupportedSchemaField` / `ToggleSchemaField` to eliminate the last awkward boolean condition, or leave it as is?

2021-11-09 02:37 UTC, twschiller commented on src/devTools/editor/hooks/useOmitFormField.tsx
> +  // Can't remove a field from something that isn't an array or object
In what case would a caller call this method if parent is not an array or object?

You should test this path

2021-11-09 02:41 UTC, twschiller approved these changes
Good to go once you address comments on error/unexpected case handling in omit field

2021-11-09 02:41 UTC, twschiller commented on src/devTools/editor/hooks/useOmitFormField.tsx
> +export function removeField(parent: unknown, fieldName: string) {
Write return types on exported functions

2021-11-09 02:41 UTC, twschiller commented on src/devTools/editor/hooks/useOmitFormField.tsx
> +export function getFieldNamesFromPathString(name: string) {
Write return types on exported functions

2021-11-09 02:41 UTC, twschiller commented on src/devTools/editor/hooks/useOmitFormField.tsx
> +        // Cannot find property to remove
Why is doing nothing the right thing to do here? Is this case expected to occur in practice? If not we should at least be logging a warning here

2021-11-09 02:41 UTC, twschiller commented on src/devTools/editor/hooks/useOmitFormField.test.tsx
> +  test("remove field from object", () => {
Add test case for non array/object

2021-11-09 15:45 UTC, BLoe commented on src/devTools/editor/hooks/useOmitFormField.tsx
> +  // Can't remove a field from something that isn't an array or object
It would be an improper use of this hook, or a mis-configured form state for that to happen. I can log a warning.

2021-11-09 23:08 UTC, merged