Feature/1687 group active marketplace bricks by team
pixiebrix/pixiebrix-extension pull request #1852
Opened 2021-11-09 00:46 UTC by mnholtz

Closes #1687, and depends on https://github.com/pixiebrix/pixiebrix-app/pull/781

This adds Team sections to the Active Bricks page that further group Active Bricks by their respective teams, or by Public Marketplace if not associated with a team.

<img width="1440" alt="Screen Shot 2021-11-08 at 4 42 55 PM" src="https://user-images.githubusercontent.com/36575242/140841133-45b9250d-b73f-433f-88e9-b9838ccb052a.png">

2021-11-09 18:24 UTC, mnholtz commented on src/options/pages/installed/ActiveBricksCard.tsx
> +      (!isPublic(extension) && !hasOrganization(extension))
Before, personal bricks were only determined by `!extension._recipe && !extension._deployment`, was there a reason for this? While testing, if I were to create a brick in the Workshop under my personal scope, the brick would not show up because metadata would contain the `_recipe` field.

 I imagine that we would want to determine personal bricks by personal scope on `_recipe`, as well, especially if a user decides to make a personal brick Public, which would transfer it to the marketplace section.'

I want to confirm the desired behavior for these situations.

2021-11-09 18:33 UTC, twschiller commented on src/core.ts
> +  readonly sharing?: Sharing;
Instead of adding it to Metadata, I think it's better to include another type that either extends Metadata or is `Metadata & { sharing: Sharing}`.

That would make it clearer in the code where the sharing property is expected to be available

2021-11-09 18:43 UTC, twschiller requested changes
See comment on Metadata type

2021-11-09 18:43 UTC, twschiller commented on src/options/pages/installed/ActiveBricksCard.tsx
> +): Array<[string, ResolvedExtension[]]> =>
The first element of the tuple is a UUID not a string?

2021-11-09 18:43 UTC, twschiller commented on src/options/pages/installed/ActiveBricksCard.tsx
> +      (!isPublic(extension) && !hasOrganization(extension))
Good question!

> personal bricks were only determined by !extension._recipe && !extension._deployment

The "personal" bricks is a bit of a misnomer/ambiguous. There's two things at play here:
1. Personal Extensions: ad-hoc extensions that aren't part of a versioned blueprint. These are stored locally and synced to the users account in the cloud
2. Personal Blueprints: an extension coming from a versioned blueprint the user has installed with their "@myscope/blueprint" that they have access to because the wrote the blueprint (and no one else can see)

In my spec,  think I forgot about case 2

I think the logic you outlined is correct/makes sense

2021-11-09 18:43 UTC, twschiller commented on src/options/pages/installed/ActiveBricksCard.tsx
> +      (extension) => extension._recipe.sharing.organizations[0]
NIT: add code comment that we're intentionally taking the first organization even though there might be multiple. I would imagine someone being confused by this later

2021-11-09 22:22 UTC, mnholtz commented
There's a lot of extensions in this example due to testing, but this is an example of the headers I chose:

<img width="839" alt="Screen Shot 2021-11-09 at 2 19 03 PM" src="https://user-images.githubusercontent.com/36575242/141013889-8461e531-6faa-498a-b7bd-e78631c521f2.png">

"Marketplace Bricks" is the catch-all heading for extensions that don't have sharing information yet.

2021-11-09 23:23 UTC, twschiller commented on src/options/pages/installed/ActiveBricksCard.tsx
> +    const personal = [];
This would be a good candidate for a helper method -- it's long and only takes a couple of inputs

2021-11-09 23:31 UTC, twschiller requested changes
Merged in main, grabbed the latest version of the server changes, and tried this PR locally

Extensions I've installed from my team marketplace previous (that have a _recipe but no _recipe.sharing or deployment) are all showing up under "Personal Bricks" and aren't being grouped by recipe

New personal blueprints I install are also showing up the same way

It looks like there's a problem with the isPersonal check. isPersonal is getting the wrong scope (the scope it sees is null). I think it needs to be added to the dependencies? There's no reason for isPersonal to be in the component? Define it outside the component

2021-11-10 14:06 UTC, twschiller commented
I see the problem - it looks like there was some miscommunication on personal extensions. There’s two cases:
1. Extensions that don’t have a corresponding recipe
2. Extensions that have a recipe, but I own that recipe (it has my scope), and it’s not shared with anyone else

For case No. 2, those need to be grouped by recipe

I left a FIXME but you’ll also need to adjust the extension grouping code: https://github.com/pixiebrix/pixiebrix-extension/pull/1852/files#diff-00cfc27d6d82530d1222baf54507e5cdecfd57fe5a242da976bec71ddaacaf60R55

2021-11-10 14:07 UTC, twschiller commented
Added @BALEHOK as an FYI on the sharing information being added to recipes going forward

2021-11-10 17:07 UTC, mnholtz commented on src/options/pages/installed/ActiveBricksCard.tsx
> +                  <ExtensionGroupHeader label="Personal Blueprints" />
Not sure if there is a better name for this...

2021-11-10 18:53 UTC, twschiller approved these changes

2021-11-10 18:58 UTC, merged