#1826: Custom option field toggles
pixiebrix/pixiebrix-extension pull request #1927
Opened 2021-11-17 15:28 UTC by BLoe

Fixes #1826 

This converts some custom block options fields to use `SchemaField` with type toggles.

_(See [this Notion](https://www.notion.so/pixiebrix/Field-toggles-for-custom-brick-options-afda60df74594f0390b20c09619629f6))_

2021-11-17 17:30 UTC, twschiller commented
@BLoe Looks like tests are failing?

2021-11-17 18:12 UTC, BLoe commented
@twschiller Should be good to go on tests now

2021-11-17 19:26 UTC, twschiller commented on src/components/formBuilder/FieldEditor.tsx
> +  const labelFieldProps = useMemo<SchemaFieldProps>(
Use a single useMemo since they all depend on the same dependency?

2021-11-17 19:27 UTC, twschiller commented on src/components/formBuilder/FormEditor.tsx
> +  const titleFieldProps = useMemo<SchemaFieldProps>(
Same feedback as on FieldEditor.tsx

2021-11-17 19:28 UTC, twschiller commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +      <BlockConfig name={blockFieldName} blockId={blockId} />
I don't like renaming this component, because it conflicts with the name of our other type: http://github.com/pixiebrix/pixiebrix-extension/blob/743ab50bb40d8f72971516b1fa91806d74667ee5/src/blocks/types.ts#L69-L69

2021-11-17 19:32 UTC, twschiller approved these changes
See comments on refactoring useMemo. I'm good with this once Aleksandr give the thumbs up

2021-11-18 08:49 UTC, BALEHOK requested changes

2021-11-18 08:49 UTC, BALEHOK commented on src/components/fields/schemaFields/v3/BasicSchemaField.tsx
> +    }
NIT: the 2 loops can be merged in a single for-of:
```
for (const type of typeArray) {
    const optionSet = getToggleOptions({
        fieldSchema: { type, ...rest },
        isRequired,
        customToggleModes,
        isObjectProperty,
        isArrayItem,
      });
    pushOptions(...optionSet);
}
```

2021-11-18 08:49 UTC, BALEHOK commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +    : BlockConfigurationV1;
This logic seems to be used in many places. How about a helper component that can render one or another depending on the API version?
```
<ForApiVersion  v1={BlockConfigurationV1} v3={BlockConfigurationV3} name={blockFieldName} blockId={blockId} />
```

I.e. you give it components and props, it decides which component to render.
Use this wrapper somewhere close to the `BlockConfiguration` component, so its consumers should not care about versioning. Maybe create `@/devTools/editor/tabs/effect/BlockConfiguration.tsx` for that purpose.

2021-11-18 08:49 UTC, BALEHOK commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +    : BlockConfigurationV1;
In fact, even without a wrapper, I think it's better to conceal the versioning stuff inside the component. If I use the component in 2+ places I don't want to repeat the versioning code.

2021-11-18 08:49 UTC, BALEHOK commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +    : BlockConfigurationV1;
Oh, I found the `SchemaField`, this is what I meant.

https://github.com/pixiebrix/pixiebrix-extension/blob/e5223da82e80ca69148d35c41153f3aaefd3c2b9/src/components/fields/schemaFields/SchemaField.tsx#L30

2021-11-18 08:49 UTC, BALEHOK commented on src/components/fields/schemaFields/widgets/OmitFieldWidget.tsx
> +const OmitFieldWidget: React.FC<SchemaFieldProps & FormControlProps> = ({
Looks like the component uses only `name` from `SchemaFieldProps`. Maybe just add a name to `FormControlProps`? BTW `Form.Control` by itself doesn't define the `name`, why are we adding it?
The main point of prop types is to show what props a component needs or can use. Defining properties that just get dropped may be confusing.

I'd do:
```
const OmitFieldWidget: React.FC<FormControlProps> = (props) => <Form.Control {...props} disabled />;
```

or

```
const OmitFieldWidget: React.FC<Except<FormControlProps, "disabled">> = ({disabled, ...restProps}) => <Form.Control {...restProps} disabled />;
```

2021-11-18 15:37 UTC, BLoe commented on src/components/fields/schemaFields/widgets/OmitFieldWidget.tsx
> +const OmitFieldWidget: React.FC<SchemaFieldProps & FormControlProps> = ({
Name is necessary because it gets set as the `id` in `FieldTemplate`. This was why a bunch of those tests were failing the other day on my PR. Without `name`, the `screen.getByLabelText()` weren't finding the (disabled) input because it didn't have the `id` set to match the `for` attribute on the label.

If I remove the rest of `SchemaFieldProps` here, I start to get a bunch of console errors about extra props being passed to this component that it doesn't accept, like `isRequired`. The problem is that these widgets are passed in as a prop and then have the `SchemaFieldProps` spread onto them (see `TemplateToggleWidget` line 170). Some of the more complicated widgets use all the fields in `SchemaFieldProps`. I would have to refactor some other stuff so that I could control which props are actually going to be passed in to which widget, but I don't think it's worth the work right now. I'd rather keep these widgets very forgiving in terms of the props they accept, even if they aren't using them all.

2021-11-18 15:47 UTC, BLoe commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +    : BlockConfigurationV1;
These pieces of code are going to be relatively short-lived, just until we fully release `v3` runtime to everyone. I'd rather not build up too much structure around this. I did it for `SchemaField` because it's used in so many places. I don't think there's any duplicate usage of the versioning checks anywhere else, it's all one-off cases. `BlockConfiguration` is only used in this one place, for example. I agree about abstracting this out when it's used in 2+ places, that's what I did for `SchemaField`, but I don't think "2+ usages" applies to any other versioned thing right now that I'm aware of.

2021-11-18 19:10 UTC, BALEHOK approved these changes

2021-11-18 19:11 UTC, BALEHOK commented on src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
> +    : BlockConfigurationV1;
There's nothing more permanent than a temporary versioning thing ;)

2021-11-18 19:19 UTC, merged