#1872 Document brick. Card component + Tests.
pixiebrix/pixiebrix-extension pull request #1935
Opened 2021-11-19 20:04 UTC by BALEHOK

Relates to #1872

2021-11-20 17:16 UTC, twschiller commented on src/blocks/renderers/documentView/documentView.test.tsx
> +    expect(rendered.asFragment()).toMatchSnapshot();
I'm OK including a snapshot tests, but we also have to have more meaningful assertions.

In this case, looking for an h1, h2, h3, etc. that contains the text

2021-11-20 17:22 UTC, twschiller requested changes
See comment on not relying solely on snapshots

2021-11-20 17:23 UTC, twschiller commented on src/blocks/renderers/documentView/documentView.test.tsx
> +  // FIXME This one fails to render the pipeline, see the snapshot
This is a great example of why snapshots aren't sufficient. Just from looking at the test you don't know whether or not the brick is meant to be in a loading state/error state/or successfully showing the content

You'd have to also open up the snapshot

2021-11-20 20:06 UTC, twschiller commented on src/blocks/renderers/documentView/documentView.test.tsx
> +  // FIXME This one fails to render the pipeline, see the snapshot
@BALEHOK I've added an example of more detailed assertions here and in the pipeline test

2021-11-21 17:50 UTC, twschiller approved these changes
@BALEHOK I'm merging this in, but see comments about not relying solely on snapshots in Jest tests

2021-11-21 17:50 UTC, merged

2021-11-22 11:55 UTC, BALEHOK commented on src/blocks/renderers/documentView/documentView.test.tsx
> +  // FIXME This one fails to render the pipeline, see the snapshot
> You'd have to also open up the snapshot
This is correct. You always have to look, read, and understand the snapshot with snapshot testing.

With the tiny elements like `h1` or `p` we want to assert on pretty much everything: tag, attributes, content. One snapshot can replace multiple assertions.

If we add explicit assertions on all of those properties, then the snapshot itself is not needed.

PR: https://github.com/pixiebrix/pixiebrix-extension/pull/1973