Drop some lint warnings
pixiebrix/pixiebrix-extension pull request #2026
Opened 2021-11-30 09:33 UTC by fregante

There were a couple of lint rules that were set to `warn` only due to a couple of situations each. I fixed those places and let the default (`error`) through.

2021-11-30 09:38 UTC, fregante commented on src/blocks/readers/jquery.ts
> +        ? $safeFind(normalizedSelector.selector, $root)
I also took the opportunity to avoid the `no-array-callback-reference` false positive altogether. This also paves the way for Sizzle since we'll be able to just replace `$safeFind` with `sizzle`

- https://github.com/pixiebrix/pixiebrix-extension/issues/725

2021-11-30 09:38 UTC, fregante commented on src/contentScript/lifecycle.ts
> +    while ($safeFind(jointSelector).length > 0) {
Instead of querying the DOM once per selector, this joins the selectors and queries them all at once.

2021-11-30 09:41 UTC, fregante commented on src/blocks/readers/jquery.ts
> +        ? $safeFind(normalizedSelector.selector, $root)
If you're fine with this, **before merging** I'll also replace all of these:

```diff
- $(document).find(rootSelector).get(0)
+ $safeFind(rootSelector).get(0)
```

```
src/contentScript/devTools.ts
120:    : $(document).find(rootSelector).get(0);
159:    : $(document).find(rootSelector).get(0);

src/nativeEditor/dynamic.ts
120:    const $root = $(document).find(rootSelector);
188:  const $elt = $(document).find(selector);

src/nativeEditor/infer.ts
549:  return $(document).find(selector).length === 1;

src/nativeEditor/infer.test.tsx
24:    $(document).find("div").get(0),
25:    $(document).find("button").get()
34:    $(document).find("div").get(0),
35:    $(document).find("button").get()
43:    $(document).find("div").get(0),
44:    $(document).find("input").get()
52:    $(document).find("div").get(0),
53:    $(document).find("input").get()
62:    $(document).find("div").get(0),
63:    $(document).find("button").get()
72:    $(document).find("div").get(0),
73:    $(document).find("button").get()
93:    $(document).find("div").get(0),
94:    $(document).find("a").get()
105:    $(document).find("div").get(0),
106:    $(document).find("a").get()
124:    $(document).find("ul").get(0),
125:    $(document).find("button").toArray()
141:    $(document).find("ul").get(0),
142:    $(document).find("button").toArray()
157:    $(document).find("ul").get(0),
158:    $(document).find("button").toArray()
172:    $(document).find("ul").get(0),
173:    $(document).find("button").toArray()
185:    $(document).find("div").get(0),
186:    $(document).find("button").get()
201:    $(document).find("div").get(0),
202:    $(document).find("button").get()
220:    $(document).find("div").get(0),
221:    $(document).find("button").get()
231:    $(document).find("ul").get(0),
232:    $(document).find("li").get()
246:    $(document).find("ul").get(0),
247:    $(document).find("li div").get()
260:    $(document).find("div").get(0),
261:    $(document).find("section").get()
277:    $(document).find("div").get(0),
278:    $(document).find("section").get()
294:    $(document).find("div").get(0),
295:    $(document).find("section").get()
311:    $(document).find("div").get(0),
312:    $(document).find("section").get()

src/extensionPoints/triggerExtension.ts
163:      const $currentElements = $(document).find(this.triggerSelector);
305:    const $root = rootSelector ? $(document).find(rootSelector) : $(document);

src/extensionPoints/menuItemExtension.ts
260:      const $item = $(document).find(`[${DATA_ATTR}="${extensionId}"]`);
612:        const $dependency = $(document).find(dependency);
665:    const $currentMenus = $(document).find(

src/blocks/transformers/detect.ts
57:    const $result = $(document).find(selector);

src/blocks/effects/attachAutocomplete.ts
61:    const $elt = $(document).find(selector);

src/blocks/readers/jquery.ts
163:      $elt = $(document).find(normalizedSelector.selector);

src/blocks/effects/tour.ts
128:      if ($(document).find(firstStep.element).length === 0) {
143:            element: $(document).find(element).get(0),

src/blocks/effects/hide.ts
52:    const $elt = $(document).find(selector);

src/blocks/effects/event.ts
77:    const $element = $(document).find(selector);

src/blocks/effects/show.ts
42:    const $elt = $(document).find(selector);
```

2021-11-30 17:54 UTC, twschiller commented on src/blocks/readers/jquery.ts
> +        ? $safeFind(normalizedSelector.selector, $root)
This looks good to me! I'd like to review the diff to avoid any errors though since this code doesn't have good test coverage

2021-11-30 17:55 UTC, twschiller commented
LGTM, I'd like to review the diff for safeFind just to double-check the transformation b/c some of the places don't have good test coverage

2021-12-01 13:21 UTC, twschiller requested changes
This looks good to me! 

I'd like to review the safeFind diff to avoid any errors though since this code doesn't have good test coverage

2021-12-02 01:55 UTC, twschiller approved these changes

2021-12-02 01:55 UTC, merged