Use Messenger for `executeInTarget`
pixiebrix/pixiebrix-extension pull request #2044
Opened 2021-12-04 10:18 UTC by fregante

## Tests done

### 200 Successful

1. open tab
2. alert in Target:target

### 404 Missing target

1. alert in Target:target
	- it doesn't exist, so it will receive `BusinessError("Sender tab has no target")`

### 410 Outdated target

1. open tab
2. wait 2000 ms
3. manually close tab
3. alert in Target:target
	- it no longer exists exist, so it will receive `BusinessError("Sender tab has no target")`

2021-12-04 10:33 UTC, fregante commented on src/background/executor.ts
> -      );
This specific error no longer exists because the retries are handled automatically by `webext-messenger` when forwarding it. The max retry time is fixed/global to around 5s, but it only applies "per hop", i.e. the background can take 4s to answer, then the content script can wait 4s more, etc.

I suppose this is an issue on large pages that have `document_idle` late.

If you think this is an issue, I could add an option for this (but options are kind of difficult at the moment, 🤭 which is why I split `getMethod` from `getNotifier` instead of using `isNotification: true`)

2021-12-04 10:33 UTC, fregante commented on src/blocks/effects/redirectPage.ts
> +};
The target was previous stored in the background page and the messaging solution expected the background page to match "sender" with "target".

With the messenger we can message the tab "directly" (i.e. the messenger takes care of forwarding) so we can store it locally (which is where the tab is requested anyway). 

This might not be the best solution but it's clean-ish (when messaging the target, you'll have to import this block, which shows the direct dependency between the two)

2021-12-04 10:54 UTC, fregante commented on src/background/executor.ts
>  const MESSAGE_RUN_BLOCK_FRAME_NONCE = `${MESSAGE_PREFIX}RUN_BLOCK_FRAME_NONCE`;
A note about the other targets:

- `opener` can probably be handled by the messenger by using `runBlock({tabId: "opener"})`
- `broadcast` likely similar implementation to https://github.com/pixiebrix/pixiebrix-extension/pull/1329
- `frame_nonce` I haven't looked at it yet, but maybe via `{tabId: "this", page: "?nonce=ABC"}`. Related: https://github.com/pixiebrix/webext-messenger/issues/41

2021-12-07 03:29 UTC, twschiller commented on src/background/executor.ts
>  const MESSAGE_RUN_BLOCK_FRAME_NONCE = `${MESSAGE_PREFIX}RUN_BLOCK_FRAME_NONCE`;
> Broadcast likely similar implementation to Replace notifyContentScripts with Messenger #1329

Unlike notifications, broadcast actually returns the results as the array. You mean in terms of how it notifies all the tabs?

> frame_nonce I haven't looked at it yet, but maybe via {tabId: "this", page: "?nonce=ABC"}

I think using the more general capability here to support our nonce based frame approach makes sense here

2021-12-07 03:32 UTC, twschiller commented on src/blocks/effects/redirectPage.ts
> +};
@fregante It'd be good to add this context to the code. Just from looking at the code I wouldn't know how it works.  It also doesn't have a type.

2021-12-07 03:38 UTC, twschiller requested changes
See comment about the "target" book keeping. How does the target in redirectPage file relate to tabToTarget in the executor?

I might be missing something?

2021-12-07 04:07 UTC, fregante commented on src/blocks/effects/redirectPage.ts
> +};
Indeed. In that case we can exclusively send messages via the background page because that's the only context that can know that information. I'll have to restore the previous manual forwarding

2021-12-07 04:11 UTC, fregante commented on src/background/executor.ts
>  const MESSAGE_RUN_BLOCK_FRAME_NONCE = `${MESSAGE_PREFIX}RUN_BLOCK_FRAME_NONCE`;
> I think using the more general page matching capability here to support our nonce based frame approach makes sense here

I'm starting to think that all of these methods will continue existing in the background page because that's the only context that can do this.

2021-12-07 04:14 UTC, fregante commented
You're right, I left a comment in the review. I'll preserve the background-based manual forwarding as before, except with the messenger instead of `sendMessage`

2021-12-07 04:18 UTC, fregante commented on src/background/executor.ts
> -      );
Since I'm bringing the handler back to this context, I will restore this function

2021-12-08 13:44 UTC, fregante commented
None of this is useful unfortunately, I'll reopen a PR with new code that only replaces the `sendMessage` with the messenger.

2021-12-08 13:44 UTC, closed without merging