Blocks Map
pixiebrix/pixiebrix-extension pull request #2101
Opened 2021-12-10 16:47 UTC by BALEHOK

Maintain a cache of all blocks with resolved types.

2021-12-10 16:48 UTC, BALEHOK commented on src/blocks/registry.ts
> +    return blocksMap;
Just for the sake of quick implementation, to be reviewed.

2021-12-10 16:49 UTC, BALEHOK commented on src/components/documentBuilder/edit/ElementEditor.tsx
> +    async () => blockRegistry.allTyped(),
This is the consumer.

2021-12-10 16:51 UTC, BALEHOK commented
Hey @twschiller @BLoe 
Please take a look at the proposal for the Blocks Map cache. We use it in 2 (for now) places and build on every render of the components.

2021-12-10 22:58 UTC, twschiller commented
I think it's reasonable to pre-compute. I was expecting to see the types also cached? The allTyped method recomputes it each time though?

The implementation in the PR has some race conditions and issues with error handling

2021-12-14 01:05 UTC, twschiller commented
@BALEHOK could you split out the BlockMap part of this? There's conflicts now that I've merged in the document editor PR

2021-12-14 17:30 UTC, twschiller requested changes
The problem with this approach is that there's a cyclical dependency between the cache and the registry (since getType calls into the registry for composite blocks). Therefore depending on the order bricks are registered some may end up with a "null" type

Therefore we have to ensure all the blocks are already registered before computing the types. (Registering a new block needs to invalidate the cache)

I would recommend:
- Calculating it the first time allTyped is called, not on registration
- Invalidating the cache whenever register is called

I can help write this up in 30min or so

2021-12-14 17:31 UTC, twschiller commented on src/blocks/registry.ts
> +        getType(item).then((itemType) => {
Use await here instead of chaining

2021-12-14 18:53 UTC, twschiller commented
@BALEHOK made tweaks (made it a Map) and adjusted when the values are computed. Please take a look

2021-12-14 18:54 UTC, twschiller approved these changes

2021-12-14 21:41 UTC, merged