Replace content script notifications
pixiebrix/pixiebrix-extension pull request #2102
Opened 2021-12-10 19:04 UTC by fregante

- Preparing for https://github.com/pixiebrix/pixiebrix-extension/issues/2096

For now this PR only replaces `$.notify` to improve the style and prepare them to be wrapped in a single shadowed container. It can already be merged, probably, and I'll build on this.

One concern:

- [ ] https://github.com/pixiebrix/pixiebrix-extension/issues/2096#issuecomment-991202913

### Demo

You can see the notification under the modal because I had enabled "notifyProgress" in `reducePipeline`

https://user-images.githubusercontent.com/1402241/145627925-d8614dbd-58bc-4e88-8bb9-4d8bc3f4cf3c.mov

2021-12-10 19:07 UTC, fregante commented on src/contentScript/notify.tsx
> +  const options = { id, duration };
The library uses CSS-in-JS so custom styles can be added here, if we decide to make it more colorful

https://react-hot-toast.com/docs/styling

2021-12-10 19:22 UTC, fregante commented on src/contentScript/notify.tsx
> +  render(<Toaster />, root);
I think isolating these would only take:

- add shadow DOM to avoid inheriting styles
- that's it

I doubt it uses any `rem` and if it does we can override them via inline styles.

I just need some sites to test this on.

2021-12-10 21:56 UTC, twschiller commented on src/contentScript/notify.tsx
> +  render(<Toaster />, root);
Let me see if I can put together a list of places we've had issues. The icon aligment issue for the old library was frequent

- LinkedIn uses rem

2021-12-10 21:58 UTC, twschiller commented
Nice! Didn't know the `all: inherit` trick

Initially I thought keeping in the upper right would be good for consistency with our current ones. But then I realized that our current ones have an issue where they're hidden by the sidebar

2021-12-10 22:10 UTC, twschiller commented
During QA I noticed the first notification isn't show? https://www.loom.com/share/233b31fe3be1493aa2a747993be18223

- [ ] First notification not being shown

2021-12-10 22:11 UTC, twschiller requested changes
See notes

2021-12-11 08:29 UTC, fregante commented on src/contentScript/notify.tsx
> +  render(<Toaster />, root);
LinkedIn:

https://user-images.githubusercontent.com/1402241/145669543-7f5d98b6-d5bc-47f2-bf56-8f1f27f79ecd.mov

> LinkedIn uses rem

Whether the host page uses them doesn't affect us, it's all good as long as _we_ don't use rem.

The good part of hot-toast is that it only uses div and generated classes, so chances of conflict are slim:

<img width="443" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/145669694-de299ed9-c613-4784-9646-6c2b982d9044.png">

Should we encounter issues, then yes, we can just wrap it in a shadow DOM in 2 lines. However it currently does not support it:

- https://github.com/timolins/react-hot-toast/issues/139

2021-12-11 08:35 UTC, fregante commented
> During QA I noticed the first notification isn't show? [loom.com/share/233b31fe3be1493aa2a747993be18223](https://www.loom.com/share/233b31fe3be1493aa2a747993be18223)

Good catch! I guess that's because React’s rendering is async so calling `render()` and `toast()` in the same tick makes the toast library abort operations (because the root isn't ready yet). 

I fixed this by _always_ adding this root to the document instead of _just in time._

Questions:

- [ ] Any style/duration tweaks? https://react-hot-toast.com/docs/toast#default-durations
- [ ] Bricks seem to [use Notify.js’ options directly](https://github.com/pixiebrix/pixiebrix-extension/issues/2096#issuecomment-991202913), can we replace them with a simple `{duration, type}` object or would that be a breaking change? Currently I'm only using the notification type (`className`)

2021-12-13 10:06 UTC, fregante commented
https://user-images.githubusercontent.com/1402241/145792327-490e913c-5034-4a76-990c-0e4a98c41659.mov

2021-12-13 16:44 UTC, twschiller approved these changes

2021-12-13 16:45 UTC, twschiller commented
![image](https://user-images.githubusercontent.com/1879821/145853306-7f4e5e7f-0601-4414-a02a-7c1c5c6ae1cd.png)

2021-12-13 16:45 UTC, merged