#2147 Update form builder to work with v3 template object fields
pixiebrix/pixiebrix-extension pull request #2163
Opened 2021-12-16 16:49 UTC by BALEHOK

2021-12-16 16:53 UTC, BALEHOK commented on src/components/formBuilder/FormPreview.tsx
> -  }, [name]);
Editor inits the active field. Also `name` at ln 68 refers to a global variable, not a component property.

2021-12-16 16:56 UTC, BALEHOK commented on src/components/formBuilder/FormPreview.tsx
> +  const previewSchema = useMemo(() => getPreviewValues(schema), [schema]);
This is the trick.

2021-12-16 21:47 UTC, BALEHOK commented on src/runtime/mapArgs.ts
> +export type DeferExpression<TValue = string> = Expression<TValue, "defer">;
Default to `string` - same as `Expression`

2021-12-17 15:01 UTC, twschiller commented on src/runtime/mapArgs.ts
> +export type DeferExpression<TValue = string> = Expression<TValue, "defer">;
IIRC, Defer doesn't support primitive values for `__value__`. (The YAML tag serializer/deserializer requires an object under the defer. Pipeline requires an array) 

What was the reason for changing this to string?

2021-12-17 15:04 UTC, twschiller commented on src/components/fields/fieldUtils.ts
> +  return produce(obj, (draft) => {
This method is confusing to read, that it's a function within a function, and the function definition is after it's call. 

Can we move unwrapTemplateExpressions outside of getPreviewValues?

2021-12-17 15:05 UTC, twschiller commented on src/components/fields/fieldUtils.ts
> +    if (typeof mutableObj !== "object") {
Arrays are also typeof object. Is that OK? Should this be using isPlainObject?

2021-12-17 15:07 UTC, twschiller requested changes
@BALEHOK 

The PR looks good. The only 2 things that stuck out to me were:
- The default type of Defer Expression
- That helper method definition (do we need to differentiate arrays vs. objects)?

Can chat these over on slack quickly if you prefer

2021-12-17 15:21 UTC, BALEHOK commented on src/components/fields/fieldUtils.ts
> +    if (typeof mutableObj !== "object") {
yes, arrays are ok. here I want to quit earlier in case of a "value" type: string, number, boolean

2021-12-17 16:13 UTC, BALEHOK commented on src/components/fields/fieldUtils.ts
> +    if (typeof mutableObj !== "object") {
In fact`isPlainObject` fails on immer `Draft` here, `Draft` is not a plain object, so it always returns `false`.

2021-12-17 16:19 UTC, BALEHOK commented on src/runtime/mapArgs.ts
> +export type DeferExpression<TValue = string> = Expression<TValue, "defer">;
Just made the default type to the same as the default type of the `Expression`. Reverted to `UnknownObject`.

2021-12-17 16:21 UTC, twschiller approved these changes

2021-12-17 16:22 UTC, merged