Feature/1474 integrations screen UI
pixiebrix/pixiebrix-extension pull request #2167
Opened 2021-12-16 20:09 UTC by mnholtz

Resolves #1474

WIP

2021-12-17 20:49 UTC, mnholtz commented
Thoughts for future work:

- [ ] Maybe move the delete action from the configure modal to the ellipsis menu

2021-12-17 21:48 UTC, mnholtz commented on src/options/pages/services/ServiceEditorModal.tsx
> +            required: true,
See comment above. I've tried the JSONSchema7 alternative below, which did not result in "required" form validation for label.
```
...
properties: {
  organization: {
    type: "string",
  },
  label: {
    type: "string",
  },
  // $RefParse mutates the schema
  config: cloneDeep(service.schema),
},
required: ["label"]
...
```

2021-12-17 21:49 UTC, mnholtz commented on src/options/pages/services/ServicesEditor.tsx
>    deleteServiceConfig: typeof deleteServiceConfig;
See code comment. This was already here when I started working on this file, not sure how important it is.

2021-12-17 22:02 UTC, mnholtz commented on src/options/pages/services/ServicesEditor.tsx
> +      (activeService && activeConfiguration));
Without including the right-hand expression to configurationId `((newService && newConfiguration) ||
          (activeService && activeConfiguration))`, there was some unexpected component re-rendering that was causing activeService or newService data to be lost before `notify` is called onSave or onDelete, preventing modal from closing.

2021-12-17 22:21 UTC, mnholtz commented on src/options/pages/services/SharedServicesCard.tsx
> +  );
I notice this is a repeated pattern, but I think it would be better solved by using PaginationTable in this case.

2021-12-20 16:56 UTC, mnholtz commented on src/options/store.ts
> +        ignoredActions: ["persist/PERSIST", "persist/FLUSH"],
Re: https://github.com/pixiebrix/pixiebrix-extension/issues/1476
I was getting serialization error referenced in this issue. This line solved the problem for me.

2021-12-21 16:28 UTC, BALEHOK requested changes

2021-12-21 16:39 UTC, mnholtz commented on src/options/pages/services/ServicesEditor.tsx
> +        console.log("Error:", error);
Oops, thanks for catching this. This was supposed to get removed.

2021-12-21 19:25 UTC, mnholtz commented on src/options/pages/services/PrivateServicesCard.module.scss
> +    }
This is actually to override bootstrap table styles that are overriding BrickIcon styles. I'm essentially trying to restore BrickIcon styles that already exist. I edited this for consistency and left a comment here.

2021-12-21 19:34 UTC, BALEHOK approved these changes

2021-12-21 19:53 UTC, merged