#2233 Add an image cropping field/widget to our form builder
pixiebrix/pixiebrix-extension pull request #2242
Opened 2021-12-22 21:06 UTC by BALEHOK

Closes #2233

Side panel
![image](https://user-images.githubusercontent.com/3116723/147154449-01cfe918-5baa-4eb7-b1aa-015cf94f90e3.png)

Edit page
![image](https://user-images.githubusercontent.com/3116723/147155055-d81599ae-154c-44fe-90f8-e753ac10c7ed.png)

2021-12-22 21:23 UTC, twschiller commented on src/components/formBuilder/ImageCropWidget.tsx
> +    return canvas.toDataURL("image/jpeg");
Making a note for myself: if we run into issues with image compression/quality we might need to support PNG here

2021-12-22 21:25 UTC, twschiller commented on src/components/formBuilder/ImageCropWidget.tsx
> +    return canvas.toDataURL("image/jpeg");
@BALEHOK any reason to use image/jpeg here instead of png? 

canvas.toDataURL looks like the default is png? Our screenshot brick current outputs png

2021-12-22 21:49 UTC, BALEHOK commented on src/components/formBuilder/ImageCropWidget.tsx
> +    return canvas.toDataURL("image/jpeg");
done

2021-12-22 22:12 UTC, twschiller commented
I'm getting this error when I try it (on v3):

![image](https://user-images.githubusercontent.com/1879821/147160793-3aea7b0e-0631-44ee-aed8-05cceb73b566.png)

2021-12-22 22:17 UTC, twschiller requested changes
See comment about the error I'm getting when I try it

2021-12-23 16:05 UTC, twschiller approved these changes
![image](https://user-images.githubusercontent.com/1879821/147265235-ee300ebb-4327-4baf-a676-f9c449df7a3d.png)

2021-12-23 16:08 UTC, merged