#2306 Forbit creating/updating a recipe if API version of the extension changes
pixiebrix/pixiebrix-extension pull request #2348
Opened 2022-01-10 22:22 UTC by BALEHOK

Resolves #2306

2022-01-10 22:23 UTC, BALEHOK commented on src/devTools/editor/panes/save/SavingExtensionModal.test.tsx
> -});
This was a duplicate of "renders new recipe button when recipe is not editable".

2022-01-10 22:49 UTC, BLoe approved these changes
Add to the message if you think it makes sense, but otherwise LGTM 👍

2022-01-10 22:49 UTC, BLoe commented on src/devTools/editor/panes/save/SavingExtensionModal.tsx
> +    message = `This extension is part of blueprint ${recipeName}. The API version ${recipe.apiVersion} of the blueprint is not compatible with the current API version ${element.apiVersion} of the ext
Maybe could also add to the end of this, something like: "You may still save `${element.label}` as a personal extension"

2022-01-10 22:53 UTC, BLoe requested changes
Sorry, I jumped the gun with my approval, just thought of something else.

I was thinking about the message text and thought it was unclear what it was actually referring to, since the button is removed in this case. I wonder if we should instead show the button, but disabled. This might be more clear what's going on to users.

2022-01-10 23:08 UTC, twschiller commented
Double-checking my understanding:

1. If the extension is the only extension in the blueprint, we want to save the blueprint with the new version. (It should be safe)
2. If there's multiple extensions in the blueprint, then prevent updating the blueprint if the version doesn't match

Glancing at the code I don't see the logic for 1?

2022-01-10 23:40 UTC, BLoe commented
> Glancing at the code I don't see the logic to allow 1?

We definitely forgot to go over this part earlier today, sorry about that. I assume we want to update the `apiVersion` property on the blueprint in this case?

2022-01-11 00:01 UTC, twschiller commented
> I assume we want to update the `apiVersion` property on the blueprint in this case?

Yes, we need to update the apiVersion on the blueprint in that case. Between v2 and v3 we didn't change how the `definitions` and `options` sections work, so this should be safe

2022-01-11 07:25 UTC, BALEHOK commented
> Sorry, I jumped the gun with my approval, just thought of something else.
> 
> I was thinking about the message text and thought it was unclear what it was actually referring to, since the button is removed in this case. I wonder if we should instead show the button, but disabled. This might be more clear what's going on to users.

Currently we don't show Blueprint buttons if a user can't update the Blueprint. It makes sense to me to follow the same pattern with the API version mismatch. Otherwise, I can change the wizard to always show buttons but disable them, but for all the cases, not just the one related to API version.

2022-01-11 07:28 UTC, BALEHOK commented on src/devTools/editor/panes/save/SavingExtensionModal.tsx
> +    message = `This extension is part of blueprint ${recipeName}. The API version ${recipe.apiVersion} of the blueprint is not compatible with the current API version ${element.apiVersion} of the ext
Should it say this for other cases as well then?
API version mismatch is no different for the non-editable case for example.

2022-01-11 15:48 UTC, BLoe commented
I think it makes sense in this case just because the message text is referring to the user not allowed to do something, but it's not totally clear what they aren't allowed to do, since there is just a save and cancel button. In other cases, if the extension hasn't been packaged into a blueprint, and there's no message about blueprints, then I think it makes sense to hide the button.

2022-01-11 17:26 UTC, BLoe commented on src/devTools/editor/panes/save/SavingExtensionModal.tsx
> +    message = `This extension is part of blueprint ${recipeName}. The API version ${recipe.apiVersion} of the blueprint is not compatible with the current API version ${element.apiVersion} of the ext
If you want to keep the style similar to the others, you could make it "Do you want to create a personal extension?" on the end of this one. And you could also add similar questions to the end of those other cases if you want to, yeah.

2022-01-11 19:11 UTC, BLoe commented on src/devTools/editor/panes/save/SavingExtensionModal.tsx
> +      message = `This extension is part of blueprint ${recipeName}.`;
👍

2022-01-11 19:14 UTC, BLoe approved these changes

2022-01-11 21:13 UTC, merged