[DO NOT MERGE] #2290 Remove v1 files and move v3 files up a level, fix references
pixiebrix/pixiebrix-extension pull request #2355
Opened 2022-01-11 02:42 UTC by BLoe

Closes #2290.

We should wait until after the 1.5.0 release to merge this change.

2022-01-19 02:58 UTC, twschiller commented
Adding @BALEHOK as reviewer since he's working on blueprint option definitions in the page editor

2022-01-19 13:29 UTC, twschiller commented
Looking forward to having this cleaned up. Here are some things I found so far during QA:

- [ ] Variable _should never__ be an option on the integrations configuration modal or the blueprint activation options screen 
- [ ] I also wanted to double-check also that the "Text" widget is not producing expressions -- only literal values are supported on the integrations screen and blueprint activation options
- [ ] Schema fields with  `$ref: "https://app.pixiebrix.com/schemas/key#"` need to be strings. The $ref there tells PixieBrix not to make the key available in the sanitized version of the configuration

```
apiKey:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: The DataRobot API key
```

2022-01-19 13:30 UTC, twschiller requested changes
See comments on variables/expressions/and key refs

2022-01-20 03:23 UTC, BLoe commented
@twschiller I think we're good for another pass here, I think I made all the changes we discussed today. Here's the AARI modal now with changes:

![image](https://user-images.githubusercontent.com/2801308/150266077-71358040-d70b-4779-ac40-ffb31384a042.png)

2022-01-20 12:55 UTC, twschiller commented on src/options/pages/services/ServiceEditorModal.tsx
> +  apiVersion: "v2",
Should the default apiVersion now be "v3"?

- [ ] Change default apiVersion to v3?

2022-01-20 12:56 UTC, twschiller commented on src/components/fields/schemaFields/FieldRuntimeContext.ts
>    apiVersion: "v2",
Should this default version now be apiVersion "v3"?

2022-01-20 12:57 UTC, twschiller commented on src/options/pages/marketplace/OptionsBody.tsx
>    apiVersion: "v2",
Should this be apiVersion "v3"?

- [ ] Should this be apiVersion "v3"?

2022-01-20 13:06 UTC, twschiller requested changes
- [ ] Review use of v2 vs. v3 in defaults
- [ ] "Omit" shows in the toggle for "$ref: key" fields, but doesn't toggle over to it. (Although it does clear whatever text you had in there)

Non-blockers: 
- [ ] In the magical forest, the width is different between the disabled toggles and normal field toggles

2022-01-20 13:28 UTC, BALEHOK commented on src/components/fields/schemaFields/SchemaField.test.tsx
> +    "show toggle widget for %s",
v1 and v2 Fields also show the toggle widget?

2022-01-20 13:28 UTC, BALEHOK commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +        </Button>
Can we disable the `DropdownButton` instead?

2022-01-20 13:28 UTC, BALEHOK commented on src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
> +        </Button>
The button title code is duplicated, can be moved to a const and re-used.

2022-01-20 13:31 UTC, BALEHOK commented on src/options/pages/services/ServiceEditorModal.tsx
> +  apiVersion: "v2",
@BLoe Let's introduce a global constant to hold the current default API version:
`const DEFAULT_API_VERSION = "v3"`

2022-01-20 13:33 UTC, BALEHOK commented on src/options/pages/services/ServiceEditorModal.tsx
> +  apiVersion: "v2",
In the `core.ts` maybe? Right after the `ApiVersion` definition https://github.com/pixiebrix/pixiebrix-extension/blob/d6c47d9666ed023bdfd3018decab8af32dbbd2d2/src/core.ts#L57

2022-01-20 17:31 UTC, twschiller commented on src/components/fields/schemaFields/SchemaField.test.tsx
> +    "show toggle widget for %s",
I like updating the tests instead of dropping them. If it's now redundant with an existing test, then it's ok to drop it

In this case, the test still makes sense, since it's double-checking things still work

2022-01-20 19:25 UTC, twschiller approved these changes

2022-01-20 19:25 UTC, merged

2022-01-20 20:57 UTC, BALEHOK commented on src/components/fields/schemaFields/SchemaField.test.tsx
> +    "show toggle widget for %s",
Of course, it should be what makes sense. Here I read it as SchemaField shows the toggle widget for v1 and v2, I thought it's a v3 feature...