Add table parser
pixiebrix/pixiebrix-extension pull request #2380
Opened 2022-01-13 12:10 UTC by fregante

- For https://github.com/pixiebrix/pixiebrix-extension/issues/2314

Let me know what inputs/options you'd like. There's a lot of guessing at the moment but I suppose it could be replaced by plain options in the editor, for example:

- headers: 
	- [x] first row
	- [ ] custom: ________
- direction:
	- [x] rows
	- [ ] columns

Possible improvements:

- is "direction" ok? There must be a better word for "in which axis are the records added?"

2022-01-14 04:58 UTC, twschiller commented
Good start. I would do the following for now using "orientation" instead of "direction". Direction in CSS tends to refer to right to left vs. left to right human languages?

```yaml
properties:
  selector:
     type: string
     format: selector
  orientation:
     type: string
     enum: ["infer", "vertical", "horizontal"]
     # provide a default so the page editor starts with a value provided
     default: "infer"
required: ["selector"]
```

2022-01-14 04:58 UTC, twschiller commented on src/utils/parseDomTable.test.ts
> +describe("parseDomTable", () => {
💯

2022-01-14 07:30 UTC, fregante commented
So I went ahead and added the brick. It seems to work

<img src="https://user-images.githubusercontent.com/1402241/149468324-9ec585bb-ace6-46b9-be73-666dee130e5b.jpg" width="100">


<img width="1155" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/149468130-23c2b2cd-c0bb-45a8-a6b1-14dbddecbd92.png">

2022-01-14 15:05 UTC, twschiller commented on src/blocks/transformers/component/TableReader.ts
> +
We support an outputSchema here

2022-01-14 15:09 UTC, twschiller requested changes
Looks great - see note about outputting an object instead of array so we have more flexibility around extending the output in the future

2022-01-15 00:47 UTC, BLoe approved these changes
Just a naming nit pick but otherwise LGTM

2022-01-15 00:47 UTC, BLoe commented on src/utils/parseDomTable.ts
> +interface List {
Should this be called Table? Or Rows or something? List seems a little bit generic here.

2022-01-15 00:47 UTC, BLoe commented on src/utils/parseDomTable.ts
> +function getList(
Same here obviously with the interface name

2022-01-15 00:49 UTC, BLoe commented on src/utils/parseDomTable.ts
> +interface List {
Ah I see there's another type called Table... So idk, whatever, not a big deal here 🤷‍♂️

2022-01-15 09:04 UTC, fregante commented
Followed both suggestions

<img width="410" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/149616240-9fa39d57-f0c4-414d-9c4f-794d5aff9d58.png">

2022-01-15 09:05 UTC, fregante commented on src/utils/parseDomTable.ts
> +interface List {
Indeed, there's a little overlap in names and types because they're all "table" data except they're in different shapes. I made some changes following Todd’s suggestions.

2022-01-16 16:24 UTC, twschiller approved these changes

2022-01-16 16:25 UTC, merged