Logs and Traces performance
pixiebrix/pixiebrix-extension pull request #2383
Opened 2022-01-13 22:17 UTC by BALEHOK

Related to #2216

2022-01-14 13:57 UTC, BALEHOK commented on src/background/logging.ts
> +  const matches = entries.filter((entry) => match(entry));
This part can be avoided when `context` contains only `extensionId` or only `blueprintId` but it completes in a fraction of time:
```
{
  entries: 3500, // number of fetched log entries (filtered by blueprintId)
  entriesTime: 424, // time of IDB request
  matchingTime: 1.600000023841858 // time to match by the context
  totalTime: 425.60000002384186,
}
```

2022-01-14 15:57 UTC, twschiller commented on src/background/logging.ts
> -      // Create individual indexes
What was reason for removing the other indexes? Does having the additional indexes slow things down?

2022-01-14 16:23 UTC, BALEHOK commented on src/background/logging.ts
> -      // Create individual indexes
Every index slows down append, update and delete operations. I doubt it's noticeable with 3-5 indexes though.
However, having an index only makes sense when we actually use it.

By `brickId` do you mean `blockId` (https://github.com/pixiebrix/pixiebrix-extension/blob/620e5e80ced2d69eb5a943c812bba44102441473/src/background/logging.ts#L72:L74)?

2022-01-14 16:25 UTC, BALEHOK commented on src/background/logging.ts
> -      // Create individual indexes
Not directly related to the question, just something I learned. In case of an empty value at the `keyPath` (the index key), there will be no index entry created, ex. if 'blockId' of a `context` is empty. This is one of the reasons why I didn't use a multi-key index. If at least one of the `context` properties included in the index is undefined, IndexedDB doesn't create an index entry. In fact `context` index was entirely empty when I had ~3,5k log entries).

2022-01-14 16:38 UTC, BALEHOK commented on src/background/logging.ts
> -      // Create individual indexes
> I think we want the brickId index b/c it's used when viewing the logs for a composite brick defined in the workshop 

Just checked the code, I see what you mean. Yes, we want `blockId`, `serviceId` and `extensionPointId` indexes. Will put them back and probably remove the `queryAll` without index entirely, throw an exception in this case instead.

2022-01-14 18:26 UTC, twschiller commented on src/devTools/editor/hooks/useExtensionTrace.ts
> +  let checkingNewEntries = false;
I don't think there should be function-scoped variables in hooks. This should be using a ref or useState?

2022-01-14 18:27 UTC, twschiller commented on src/contentScript/lifecycle.ts
> +    for (const [, extensionPoint] of _dynamic.entries()) {
NIT: if you're ignoring the keys, use values instead of entries

2022-01-14 18:27 UTC, twschiller commented on src/components/logViewer/useLogEntries.ts
> +  let checkingNewEntries = false;
I don't think there should be function-scoped variables in hooks. This should be using a useRef or useState?

- [ ] No function-scoped variables in hooks

2022-01-14 18:29 UTC, twschiller commented on src/background/logging.ts
> +  if (context.extensionId) {
It would be good to leave a code comment here on why this works in practice. We use the index to do an initial filter, and then makeMakeEntry to apply the full filter.

When I initially read the code I thought it wouldn't work for multi-field filters

2022-01-14 18:30 UTC, twschiller commented on src/background/logging.ts
> -      // Create individual indexes
Makes sense to throw if an index is missing to prevent performance issues/regressions

2022-01-14 18:36 UTC, twschiller requested changes
Looks good overall. Marking as "Request changes" for re-adding the additional indexes and comments about the function-scoped variables in hooks

2022-01-18 00:17 UTC, twschiller commented on src/background/logging.ts
> +  let indexKey: IndexKey;
NIT: prefer to use `indexKeys.find` here instead of a loop

2022-01-18 00:18 UTC, twschiller approved these changes

2022-01-18 00:22 UTC, merged