#851: Open all links in a new tab by default
pixiebrix/pixiebrix-extension pull request #2425
Opened 2022-01-18 08:54 UTC by fregante

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/851
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2365

Are there any other contexts in which links may appear?

2022-01-18 08:55 UTC, fregante commented on src/ephemeralForm.html
> +    <script src="ephemeralForm.js"></script>
I also moved these down for consistency

2022-01-19 01:45 UTC, twschiller commented
I think this is unsafe unless we also include `rel="noopener noreferrer"` automatically somehow?

2022-01-19 01:45 UTC, twschiller requested changes
See comment on `rel`

2022-01-19 04:01 UTC, fregante commented
They're not necessary because `target=_blank` implies `noopener` and Chrome probably never passes `chrome-extension://` URLs as the referrer.

To test this, use this HTML snippet in a renderer: 
```
<a href="https://headers.brigante.workers.dev/">click me
```

I see:

```
{
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
  "accept-encoding": "gzip",
  "accept-language": "en-US,en;q=0.9",
  "cf-connecting-ip": "XXX",
  "cf-ipcountry": "ID",
  "cf-ray": "6cfd2600ecf",
  "cf-visitor": "{\"scheme\":\"https\"}",
  "connection": "Keep-Alive",
  "host": "headers.brigante.workers.dev",
  "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"",
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": "\"macOS\"",
  "sec-fetch-dest": "document",
  "sec-fetch-mode": "navigate",
  "sec-fetch-site": "cross-site",
  "sec-fetch-user": "?1",
  "upgrade-insecure-requests": "1",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
  "x-forwarded-proto": "https",
  "x-real-ip": "XXX"
}
```

2022-01-19 12:45 UTC, twschiller commented
The opener wouldn't be on the headers, it would be on the window variable. https://web.dev/external-anchors-use-rel-noopener/

Looks like they just added the noopener behavior directly in the browser:

> As of Chromium version 88, anchors with target="_blank" automatically get noopener behavior by default. Explicit specification of rel="noopener" helps protect users of legacy browsers including Edge Legacy and Internet Explorer.

For the referrer, are you using a clean profile? If not another browser extension you have running might be stripping it off? Your guess about Chrome not passing extension referrers is also likely

2022-01-19 17:41 UTC, twschiller approved these changes

2022-01-19 17:44 UTC, merged