Share blueprint modal improvements
pixiebrix/pixiebrix-extension pull request #2428
Opened 2022-01-18 19:06 UTC by BALEHOK

Closes #2378 
Closes #2379 

Share as Blueprint:
![image](https://user-images.githubusercontent.com/3116723/150002125-3a80b600-f050-4c74-9ccf-a96324d9e57b.png)

Copy blueprint link:
![image](https://user-images.githubusercontent.com/3116723/150002230-3e3880c7-2061-423e-a231-a537f4e00e0f.png)

2022-01-18 19:11 UTC, BALEHOK commented on src/options/App.tsx
> -
Because all the other routes (including `/installed/share/:extensionId`) are handled by the `InstalledPage`, see ln. 149.

2022-01-18 19:13 UTC, BALEHOK commented on src/options/pages/installed/InstalledPage.tsx
> +          return toShare && !flags.includes("restricted-marketplace") ? (
Came from https://github.com/pixiebrix/pixiebrix-extension/pull/2428/files#diff-0240d71f16c23bc0da6d9af83c458c3e641bcc577a169239a7d208ebca64c86eL141

2022-01-18 19:15 UTC, BALEHOK commented
@BLoe need to figure how we'll merge SwitchButton

2022-01-19 03:13 UTC, twschiller commented on src/options/pages/installed/ShareLinkModal.tsx
> +        <Button onClick={copyLink}>Copy</Button>
Instead of having the copy button here, let's do like we do in the Zapier modal: http://github.com/pixiebrix/pixiebrix-extension/blob/b1585868a3299072258a78eb10ab54752edcfcf2/src/options/pages/services/ZapierModal.tsx#L51-L51

It's a readonly text field with a copy button attached to it

The modal button can then just be "Close" or "OK"

2022-01-19 03:15 UTC, twschiller submitted a review, later dismissed
Looking good. See comment on the layout of the copy modal

2022-01-19 03:16 UTC, twschiller requested changes
See comment on copy modal style

2022-01-19 03:17 UTC, twschiller commented
@BALEHOK You'll need to merge in the changes from Ben's layout PR (rebase?)

I'm also adding Adding @mnholtz b/c these changes will conflict with the PR she's working on (consolidating the active bricks and blueprint page)

2022-01-19 16:07 UTC, BALEHOK commented on src/options/pages/installed/ShareLinkModal.tsx
> +        <Button onClick={copyLink}>Copy</Button>
> Instead of having the copy button here, let's do like we do in the Zapier modal: [http://github.com/pixiebrix/pixiebrix-extension/blob/b1585868a3299072258a78eb10ab54752edcfcf2/src/options/pages/services/ZapierModal.tsx#L51-L51](https://github.com/pixiebrix/pixiebrix-extension/blob/b1585868a3299072258a78eb10ab54752edcfcf2/src/options/pages/services/ZapierModal.tsx#L51-L51)
> 
> We don't want to user to actually click on the link. And some users won't know to right click to copy it via the link
> 
> It's a readonly text field with a copy button attached to it
> 
> The modal button can then just be "Close" (or "OK", whichever you prefer)

@twschiller 
![image](https://user-images.githubusercontent.com/3116723/150169289-0ef86e29-b98b-463c-ba6d-097c066d38ec.png)

2022-01-19 17:32 UTC, twschiller approved these changes

2022-01-19 17:33 UTC, merged