#2427 Handle empty expression values properly
pixiebrix/pixiebrix-extension pull request #2452
Opened 2022-01-20 20:35 UTC by BLoe

Fixes #2427

2022-01-20 21:35 UTC, twschiller requested changes
Add tests here: http://github.com/pixiebrix/pixiebrix-extension/blob/bb270d1a9e1ca27785b83cc868a1fed3b651b609/src/devTools/editor/extensionPoints/base.test.ts#L20-L20

2022-01-21 15:01 UTC, BALEHOK commented on src/devTools/editor/extensionPoints/base.ts
> +      isExpression(parent) || (typeof value !== "undefined" && value !== "")
should we remove empty expressions like `a` and/or `b`?

```
{
  a: { __type__: "nunjucks", __value__: undefined },
  b: { __type__: "nunjucks", __value__: "" }
}
```

maybe:
```
isExpression(value)
  ? typeof value.__type__ !== "undefined" && typeof value.__value__ !== "undefined" && typeof value.__value__ !== ""
  : typeof value !== "undefined" && value !== ""
```

2022-01-21 15:06 UTC, BALEHOK commented on src/devTools/editor/extensionPoints/base.ts
> +      isExpression(parent) || (typeof value !== "undefined" && value !== "")
Related to https://github.com/pixiebrix/pixiebrix-extension/issues/2413
The runtime gets empty expressions: `{ __type__: "nunjucks" }` and fails to render templates. I added a [check](https://github.com/pixiebrix/pixiebrix-extension/pull/2456/files#diff-dea3921d1c165631d2eb1f84b42913c52e2c6979f9c66b4ab1fbc578810a4c3bR102) for the empty template but would be nice to get rid of such properties entirely.

@twschiller your thoughts?

2022-01-21 15:14 UTC, twschiller commented on src/devTools/editor/extensionPoints/base.ts
> +      isExpression(parent) || (typeof value !== "undefined" && value !== "")
There's a difference between what we do in the runtime vs. what we do in the Page Editor. My philosophy in the runtime is: "make everything explicit to avoid surprises". 

In the Page Editor, that's where we can have shortcuts/UX affordances

For your particular examples:

- I don't think our widgets ought to ever produce (a)? Do they currently? If they do, that seems like a bug
- In case (b), I don't want the runtime to remove it or remove it during save. Instead, I'd have the field maybe switch to "omit" on blur?

2022-01-21 16:23 UTC, twschiller commented on src/devTools/editor/extensionPoints/base.test.ts
> +  expect(
@BLoe can we give this a better name? The better name for this test would be "don't remove empty values from expressions

2022-01-21 16:24 UTC, twschiller approved these changes
Conditionally approving so we can get this merged in. @BLoe please split the test code out into a separate test with a better name and get this merged in

2022-01-21 16:25 UTC, twschiller commented on src/devTools/editor/extensionPoints/base.test.ts
> +    bar: { __type__: "nunjucks", __value__: null },
Why is this changing from undefined to null here? I would have though it would just be returned as-is? I'd expect the test to be `expect(removeEmptyValues(obj)).toStrictEqual(obj)`

2022-01-21 16:46 UTC, merged