#2434: WIP: Add multiple-table reader
pixiebrix/pixiebrix-extension pull request #2509
Opened 2022-01-26 08:14 UTC by fregante

- closes https://github.com/pixiebrix/pixiebrix-extension/issues/2434

Tested on https://pbx.vercel.app/create-react-app/table/

Notes:

- I guess that the vast majority of tables on the internet are not labelled/captioned, so we should probably default to using the headers as key

To do:

- [ ] Add more ways to figure out the table name as [previously suggested](https://github.com/pixiebrix/pixiebrix-extension/issues/2434)
- [ ] Add some automated tests

<img width="1009" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/151125559-7b4b95ff-4e6c-445e-b0dd-dd59f2d53fe2.png">

2022-01-26 09:56 UTC, fregante commented on src/blocks/transformers/component/TableReader.ts
> +    return { tables: Object.keys(tables).length === 0 ? undefined : tables };
This doesn't look right. How do I defined returning the object without wrapping it into `tables`? 

Currently to use a table one would have to specify `@tables.tables.table-name`

2022-01-26 09:56 UTC, fregante commented on src/utils/parseDomTable.ts
> +      parsedTable.fieldNames.join("-");
The order of this could go either way. Ideally we'd want a short but human-readable key. The `id` is short but it could be anything; `caption` is for humans but it could be a whole sentence.

2022-01-26 15:54 UTC, twschiller commented on src/blocks/transformers/component/TableReader.ts
> +    return { tables: Object.keys(tables).length === 0 ? undefined : tables };
You can just return the tables object directly? Then it will be `@tables.table-name`

2022-01-26 15:58 UTC, twschiller requested changes
- [ ] We can't use kebab case because it produces invalid identifiers. Template/expression libraries like nunjucks don't like kebab case because it's ambiguous with a minus sign. We should use underscore (🐍  case), or combine things in camel case

- [ ] Name generation: I like the column based name approach, but am worried the variable names might be too long in practice. A couple options: 1: only include enough column names to uniquely identify the table on the page, 2: compute a short hash of the column names, e.g., `Table_l33t`

Thoughts?

2022-01-26 17:35 UTC, BLoe commented
Also, are we sure we don't just want to make the normal table reader accept an array of table selectors or something? Instead of a separate brick?

2022-01-26 18:05 UTC, twschiller commented
> Also, are we sure we don't just want to make the normal table reader accept an array of table selectors or something? Instead of a separate brick?

I agree, I like the idea of a single brick. In general, we're going to be consolidating bricks (e.g., merging the Slack bricks together, etc.)

The blocker is not supporting nested object fields in the page right now. (Our single table reader brick takes a selector and orientation). We could do an array approach

2022-01-27 14:37 UTC, BLoe commented
Yeah, I was thinking an array might work okay for this

2022-01-28 11:47 UTC, fregante commented
Always returning an array is certainly simple to implement:

- if the selector matches anything, return `[table]`
- if the selector is missing, return all the tables

If we go with arrays, I suppose we're doing away with the table IDs?

2022-01-28 13:57 UTC, twschiller commented
>  If we go with arrays, I suppose we're doing away with the table IDs?

The array approach was referring to the _inputs_ to the brick, not the outputs.

The output must name the tables, having array is not robust because table position on the page might change.

Currently we have no way in the Page Editor to configure nested objects. 

For example, the Page Editor can handle:

```json
[
    { "name": "MyTable", "selector": "#table-1", "orientation": "vertical"},
    { "name": "MyTable2", "selector": "#table-2", "orientation": "horizontal"}
]
```

But a the Page Editor _cannot_ configure the following because the Page Editor currently does not support nested objects:

```json
{
    "MyTable": {
         "selector": "#table-1", "orientation": "vertical"
    },
    "MyTable2": {
         "selector": "#table-2", "orientation": "horizontal"
    },
}

So the input schema would need to be:

```yaml
type: object
properties:
    tables:
        type: array
        items:
           type: object
           properties:
              name:
                 type: string
                 description: Key for the table in the output 
              selector:
                 type: string
                 format: selector
              orientation:
                 type: string
                 enum: ["infer", "horizontal", "vertical"]
```

As I'm typing this, from a brick ergonomics perspective, I'm think for now we should just keep a "read all tables" brick that reads everything, and a "read table" brick that reads a single table

Adding support for multiple manual table selectors complicates the single-table case because the user has to come up with a name for the single table. That's an unnecessary detail it would be nice to avoid. And, if you need multiple tables, you can use the "read all tables" brick or multiple single table bricks

In the future, we can always decide to deprecate one of them and consolidate

2022-01-28 13:58 UTC, twschiller commented on src/blocks/transformers/component/TableReader.ts
> +export const TABLES_READER_ID = validateRegistryId("@pixiebrix/tables-reader");
Let's call this `@pixiebrix/table-reader-all` to visually distinguish the two ids better

2022-01-28 13:58 UTC, twschiller commented on src/blocks/transformers/component/TableReader.ts
> +      "Tables Reader",
Let's call this "Read All Tables"

2022-01-28 13:59 UTC, twschiller commented on src/blocks/transformers/component/TableReader.ts
> +      "Extract data from all the tables"
"Extract data from all the tables" -> "Extract data from all the tables on the page"

2022-01-28 14:29 UTC, fregante commented
I think I followed all the suggestions

2022-01-31 16:22 UTC, twschiller approved these changes

2022-01-31 16:27 UTC, merged