#2240 Clear the selected service if it doesn't exist in the extension configured services
pixiebrix/pixiebrix-extension pull request #2511
Opened 2022-01-26 18:05 UTC by BLoe

Fixes #2240

2022-01-26 19:07 UTC, twschiller commented on src/components/fields/schemaFields/ServiceField.tsx
> +        helpers.setValue(null);
@BLoe How does this work for the Get/Put database bricks and others which use a hidden select field? Does this cover it? If it does, could you add a comment how it works for this case?

2022-01-26 19:08 UTC, twschiller requested changes
- [ ] Add a comment explaining how this works for hidden PixieBrix service fields

2022-01-26 20:28 UTC, BLoe commented on src/components/fields/schemaFields/ServiceField.tsx
> +        helpers.setValue(null);
Yep, definitely need to change `AppServiceField` as well... I forgot that was a separate component.

2022-01-26 23:03 UTC, BLoe commented on src/components/fields/schemaFields/AppServiceField.tsx
> -  >(props);
I missed this in the v1/v3 cleanup change

2022-01-26 23:06 UTC, BLoe commented on src/components/fields/schemaFields/ServiceField.tsx
> +        helpers.setValue(null);
I think we're good to go on this now.

2022-01-27 02:23 UTC, twschiller approved these changes

2022-01-27 02:23 UTC, merged