#2501 Move copy+remove buttons to header above node layout
pixiebrix/pixiebrix-extension pull request #2553
Opened 2022-02-01 15:29 UTC by BLoe

Closes #2501 

Standard:
![image](https://user-images.githubusercontent.com/2801308/151998115-01cff3f3-8140-43ef-96c0-667474d004a6.png)

Disabled on foundation nodes:
![image](https://user-images.githubusercontent.com/2801308/151998006-f963e06d-c550-489a-8003-058877e27325.png)

2022-02-01 16:26 UTC, fregante commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  flex-direction: row;
This is the default and doesn't need to be specified

2022-02-01 16:26 UTC, fregante commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  align-items: stretch;
I think this too

2022-02-01 16:26 UTC, fregante commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  justify-content: flex-end;
Since you use flex-grow on the headerTitle this isn't needed/used

2022-02-01 16:26 UTC, fregante commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  background: none;
I think these 2 properties can be avoided by using the "link" style of the Button component. Undoing styles is generally a code smell (although sometimes unavoidable when using frameworks) https://csswizardry.com/2012/11/code-smells-in-css/

2022-02-01 16:34 UTC, fregante commented on src/devTools/editor/tabs/editTab/EditTab.tsx
> +              tooltipText="Remove Brick"
Strangely they don't have the same orientation (but should)

![jig2](https://user-images.githubusercontent.com/1402241/152010025-095e58fb-4f1d-4a2c-bd55-c60ae3725b81.gif)

2022-02-01 18:25 UTC, BLoe commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  background: none;
These are just using plain, HTML `button` elements. `TooltipIconButton` is used in another place and manually styled already in a similar way (in `EditorNodeLayout`), so I'd rather leave it as is for now. If I refactor it to use Bootstrap `<Button/>` with a variant then I have to fix the styling in the other place also.

2022-02-01 18:28 UTC, BLoe commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  flex-direction: row;
I think I prefer specifying this anyways, for code clarity and readability. Just one less thing to have to think of and remember when reading CSS in the future, imo. Especially when nested elements are switching back and forth between flex column and flex row.

2022-02-01 18:29 UTC, BLoe commented on src/devTools/editor/tabs/editTab/EditTab.tsx
> +              tooltipText="Remove Brick"
Interesting, on my machine they are both like your copy button, I don't see a difference. The layout is automatically done by the Bootstrap `<OverlayTrigger/>` component anyway, it's not something we're implementing directly.

2022-02-01 18:39 UTC, BLoe commented
Alright, I changed the buttons to grey for now. I think we'll want to revisit all the button styling at some point and move away from grey as the active button color for all of these icon-buttons. I think it's a little bit confusing - they look disabled at first.

2022-02-01 19:15 UTC, BALEHOK commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  flex-direction: row;
Sorry @BLoe, but I'm +1 for **not** specifying the default values explicitly :)

Otherwise silly questions come to my mind: should we write the default settings for other properties, which of them, `position`, `margin`, `display`? all those props for each element or choosing randomly?

2022-02-01 20:01 UTC, twschiller commented
> Alright, I changed the buttons to grey for now. I think we'll want to revisit all the button styling at some point and move away from grey as the active button color for all of these icon-buttons. I think it's a little bit confusing - they look disabled at first.

I've never understood the appeal of grey buttons. Bootstrap 4's "Secondary" style is also grey https://getbootstrap.com/docs/4.0/components/buttons/

We end up using those dark grey one in the save modal for blueprints

I like the translucent/light grey for being disabled for now

2022-02-01 21:12 UTC, twschiller commented on src/devTools/editor/tabs/editTab/EditTab.module.scss
> +  flex-direction: row;
From a signaling developer intent perspective, I agree we should either: 1) leave defaults off, or 2) indicate which properties are overriden vs. which are repeating the defaults

2022-02-01 21:18 UTC, twschiller commented
If the buttons are going to be grey, they need to have a hover effect. E.g., making them blue and red respectively on hover

That's what we do for the other buttons in the extension overview:

![image](https://user-images.githubusercontent.com/1879821/152052762-cfaa14a4-b6cf-422e-8d8e-0a30831e4b11.png)

![image](https://user-images.githubusercontent.com/1879821/152052787-337bf628-3b50-4158-bcab-4a54e81aa7c1.png)

Also, I think the overlay target is the icon currently? I think we need to have the overlay target on the container that has padding? Right now there's a bit of a flicker because the overlay target is so small

2022-02-01 21:19 UTC, twschiller requested changes
Add hover effect to buttons

2022-02-02 18:58 UTC, twschiller approved these changes

2022-02-02 19:02 UTC, merged