#2556 Require user scope to access Workshop page
pixiebrix/pixiebrix-extension pull request #2570
Opened 2022-02-02 20:19 UTC by BALEHOK

Closes #2556 

Scope settings in dev tools:
<img width="1920" alt="Screen Shot 2022-02-02 at 5 26 18 PM" src="https://user-images.githubusercontent.com/3116723/152230641-f8138d3c-9720-4ad5-92a6-f710166e0309.png">

Scope settings on Workshop page:
<img width="1247" alt="Screen Shot 2022-02-02 at 5 27 00 PM" src="https://user-images.githubusercontent.com/3116723/152230688-c3075db2-00d2-4423-883c-df08263cc5ea.png">

2022-02-02 23:26 UTC, twschiller commented on src/auth/RequireScope.tsx
> +  scopeSettingsTitle: string;
Should the parent component just pass through the ScopeSettings as a renderprop component?

```
<RequireScope fallback=(() => <ScopeSettings title="blah blah blah"/>>
  <div>Protected contnet</div>
</RequireScope>
```

It's not bad in this case b/c it's only 2 props, but if we had more I'd favor the render prop approach

2022-02-02 23:45 UTC, twschiller commented on src/auth/RequireScope.tsx
> +  if (mode !== "local" && !isPending && (scope === "" || !scope)) {
Prefer lodash's `isBlank(scope)`

2022-02-02 23:48 UTC, twschiller commented on src/options/pages/workshop/WorkshopPage.tsx
> +  const { isLoggedIn, flags, scope, isPending } = useContext(AuthContext);
NIT: in the destructring rename isPending so the uses are clearer
```
const { isLoggedIn, flags, scope, isPending: isAuthPending } = useContext(AuthContext);
```

2022-02-03 00:14 UTC, twschiller approved these changes
See comments, but good to merge

2022-02-03 12:38 UTC, BALEHOK commented on src/auth/RequireScope.tsx
> +  scopeSettingsTitle: string;
In this case the parent component should know about not 1, but 2 components the `ScopeSettings` and `RequireScope`.

2022-02-03 13:53 UTC, twschiller commented on src/options/pages/workshop/WorkshopPage.tsx
> +    const errorMessage = getErrorMessage(authError);
Hmm, instead of having yet another way of displaying an error, this should really be using the `<Page>` component's error prop

I think you can use it by setting the `<RequireScope isPending={isAuthPending || Boolean(authError}>`

And then passing

`<Page error={authError}>`?

2022-02-03 13:53 UTC, twschiller requested changes
Don't introduce another error component, see comment above

2022-02-03 14:21 UTC, twschiller commented on src/auth/RequireScope.tsx
> +  scopeSettingsTitle: string;
It's a bit of YAGNI, but there's hypothetical scenarios where you want a different fallback

I'm OK with the current approach in this PR

2022-02-03 14:45 UTC, BALEHOK commented on src/options/pages/workshop/WorkshopPage.tsx
> +    const errorMessage = getErrorMessage(authError);
`isPending={isAuthPending || Boolean(authError}` using the `authError` in the `isPending` prop looks confusing to me...

2022-02-03 14:53 UTC, twschiller approved these changes

2022-02-03 15:04 UTC, merged