#2151 Remove "scope" configuration on Page Editor first run
pixiebrix/pixiebrix-extension pull request #2588
Opened 2022-02-04 12:46 UTC by BALEHOK

Closes #2151

2022-02-06 23:33 UTC, twschiller commented on src/devTools/editor/panes/save/SaveExtensionWizard.test.tsx
> +test("requires user context to save as new blueprint", async () => {
💯

2022-02-06 23:55 UTC, twschiller commented
I'm getting a scollbar on the workshop page

![image](https://user-images.githubusercontent.com/1879821/152707019-70ddc07b-24df-4788-bffd-26877f188b3c.png)

2022-02-07 00:01 UTC, twschiller commented
Also getting for the share modal 

![image](https://user-images.githubusercontent.com/1879821/152707280-45eebf04-3d61-4ca2-9c91-726db1d34558.png)

2022-02-07 00:08 UTC, twschiller commented
Also on the save wizard

![image](https://user-images.githubusercontent.com/1879821/152707502-0e110cc9-d3fc-4d4f-9e07-bb02c90c7204.png)

The save wizard is also getting cut off:

![image](https://user-images.githubusercontent.com/1879821/152707524-33757ca9-f9f6-4933-a920-4588ab432e32.png)

We probably need to add a scroll to the modal body?

2022-02-07 00:12 UTC, twschiller commented
Completing the form reloads the page: http://github.com/pixiebrix/pixiebrix-extension/blob/feature/2151-page-editor-scope/src/auth/ScopeSettings.tsx#L97-L97

That's a not great experience for the sharing modal, but it's dealbreak for the save modal in the dev tools because people will lose their work

The correct solution is to probably create an authSlice in the Redux Store so you can update the scope. For this PR, I'd also be OK with just exposing a method from the React Context

2022-02-07 00:13 UTC, twschiller requested changes
See comments on reloading and size/scrolling

2022-02-07 16:05 UTC, BALEHOK commented on src/devTools/Error.tsx
> +const Error: React.VoidFunctionComponent<ErrorProps> = ({
Extracted from `Panel.tsx`

2022-02-07 16:05 UTC, BALEHOK commented on src/devTools/PersistLoader.tsx
> +const PersistLoader: React.VoidFunctionComponent = () => (
Extracted from `Panel.tsc`

2022-02-07 21:14 UTC, BLoe reviewed
I'll wait for Todd to approve, but overall this looks reasonable to me 👍

2022-02-07 22:34 UTC, twschiller commented
I merged with main (there was a conflict in how auth errors are handled since I merged in Federico's error banner PR). 

Here's the results of QA. Looks like there's one last gotcha we have to deal with:

- [x] Set scope in workshop
- [x] Set scope as part of sharing. See my commit. I had to remove the "scope" condition from the `hide` prop. Once I did this it worked properly
- [x] Set scope before saving as New Blueprint
- [ ] Save as Personal Extension without setting scope. This works? But you also get a red error toast that you don't have access to the scope. It looks like the Save Wizard is making a request to update the blueprint it shouldn't be?

2022-02-08 02:04 UTC, twschiller approved these changes
@BALEHOK Merging this in because I need the auth changes for the Rollbar PR I'm working on. Please see my comment on the Save as Personal Extension bug

2022-02-08 02:04 UTC, merged