Feature/2251 add icons
pixiebrix/pixiebrix-extension pull request #2599
Opened 2022-02-05 02:20 UTC by mnholtz

This adds icons to Grid View and Table View installable items.

- [ ] Add extension type icon to possible default icons available

2022-02-08 03:30 UTC, twschiller commented on src/options/pages/blueprints/InstallableIcon.tsx
> +  return faPuzzlePiece;
Could we just keep the faCube for now in this PR?

2022-02-08 03:32 UTC, twschiller commented
@BALEHOK could you help review? This doesn't need to be perfect, we just need to get a icons in so we can do the other UI/information hierarchy changes

2022-02-08 18:23 UTC, BALEHOK requested changes

2022-02-08 18:23 UTC, BALEHOK commented on src/options/pages/blueprints/tableView/TableRow.tsx
> +      <td>{getInstallableIcon(installable)}</td>
`TableRow` can use the hook, no need to pass `getInstallableIcon` via props

2022-02-09 11:35 UTC, BALEHOK approved these changes

2022-02-09 15:43 UTC, merged