#1759: Never ask permission to access pixiebrix.com
pixiebrix/pixiebrix-extension pull request #2609
Opened 2022-02-06 03:46 UTC by fregante

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1759
- Also related: https://github.com/pixiebrix/pixiebrix-extension/issues/575

This is particularly an issue for new users who will install PixieBrix, try it on our website and immediately experience a repeated prompt.

2022-02-06 21:30 UTC, twschiller commented on src/utils/permissions.ts
> +    remove(permissions.origins, (origin) => pbDomainRegex.test(origin));
Our general policy is to try to avoid mutating arguments in functions. (Pure functions are easier to reason about). You cave a few options here: 1) clone, 2) use immer, 3) use spread with filter to avoid mutating the origins

- [ ] Don't mutate arguments

2022-02-06 21:31 UTC, twschiller commented on src/utils/permissions.ts
> +const pbDomainRegex = patternToRegex("https://*.pixiebrix.com/*");
Should we attempt to use the content scripts entry of the manifest? getManifest isn't async so we wouldn't hit problems with Firefox user actions

Would also have the benefit of working better in development

2022-02-06 21:31 UTC, twschiller requested changes
Don't mutate function arguments

2022-02-07 03:53 UTC, fregante commented
Both done

2022-02-07 12:46 UTC, twschiller approved these changes

2022-02-07 13:02 UTC, merged