#2603 logs badge
pixiebrix/pixiebrix-extension pull request #2705
Opened 2022-02-11 20:00 UTC by BALEHOK

Closes #2603 

This is a draft to review the approach to Logs.

Problem: current behavior of Logs polling and displaying is hard to grasp, difficult to maintain and extend.
- `LogContext` holds `unread` entries and `refresh` and `clear` handlers. `LogContextWrapper` allows overriding the handlers with a custom implementation. This doesn't seem to be a scalable solution. The context itself is marked deprecated.
- `useLogEntries` hook does multiple things: polls the log entries from storage, holds all the entries, holds displayed entries, filters them for view, selects paginated entries for the current page, updates `unread` entries in the `LogContext`. It also sets the `refresh` and `clear` handlers in the context.

Proposed change:
- `LogContext` holds all the entries fetched from the storage, and displayed entries;
- `ContextLogs` wrapper manages the context is responsible for polling new entries from storage (by MessageContext) and synchronization of all and displayed entries.
- `useLogEntriesView` is responsible for logs presentation in the table, pagination, and filtering.

ToDo:
- [ ] remove debug logs
- [ ] update Options page

2022-02-13 22:00 UTC, twschiller commented
@BALEHOK I think the split your propose makes sense. I'm good with getting a PR in with the exact approach, but think we should consider using this to test our some ideas for the broader refactoring work

> LogContext holds all the entries fetched from the storage, and displayed entries

Would it make sense to move this to Redux (a log slice?) This is sort of the classic example of information that needs to be available across multiple components that shouldn't know about each other

Could it also make sense to use RTK to wrap the log calls. It would then manage the state, including isFetching, etc.

Aside from the log entries themselves, the relevant state would be
- activeContext: MessageContext
- lastReadTimestamp: number

> ContextLogs wrapper manages the context and is responsible for polling new entries from storage (by MessageContext) and synchronization of all and displayed entries.

I think polling is OK for now. 

In the future we should probably move to an event listener approach.  This would be on:
- [appendEntry](http://github.com/pixiebrix/pixiebrix-extension/blob/37a6183b11a808b416d097d0dc789a214a6da53a/src/background/logging.ts#L120-L120)

I don't think the IDB interface itself [exposes any event listeners for writes](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase)

The gotcha of the listener based approach is it would be the devtools needing to listen to an event that's occurring in the background page. There's a couple approach: 1) the devtools could tell the background page which context it wants to listen for, 2) the devtools could listen to all new entries and filter them itself. We could also decide what's included in the event (e.g., just the log id, or the content of the append)

> useLogEntriesView is responsible for logs presentation in the table, pagination, and filtering.

This is OK, but I think it makes sense to switch over to the React Table hooks at this point instead of implementing our own version. It has affordances for pagination, filtering, etc.

2022-02-14 13:10 UTC, BALEHOK commented
@twschiller
> Would it make sense to move this to Redux (a log slice?)
The only concern of mine is the case when we would like to get (poll and show) data for several MessageContexts on the same page. Hypothetically this is possible. Managing multiple active contexts is easier with React Context (each Context has its own active message context).

2022-02-14 15:07 UTC, twschiller commented
> The only concern of mine is the case when we would like to get (poll and show) data for several MessageContexts on the same page. Hypothetically this is possible. Managing multiple active contexts is easier with React Context (each Context has its own active message context)

At a given time, I think only one would be polling (or listening)? With Redux, you have two options: 1) just have the contexts keyed by extension, 2) have a single active log entries and clear it out when switching between extensions

With approach 1, you'd just write a selector for the active context. Only potential downside of approach would be keeping logs in memory that you don't need (if there's a lot of logs). Approach 2 seems totally OK though

I'm fine with either approach, though have a preference for Redux since it also helps standardize how actions/callbacks works across components

2022-02-15 15:39 UTC, twschiller commented on src/components/logViewer/ContextLogs.tsx
> +  displayedEntries: LogEntry[];
This naming is confusing to me. From the type it's not obvious what a displayedEntry would be vs. an allEntry

Even reading the code, I'm not able to quickly tell? It has something to do with either the loading state or the messageContext?

When would a caller want to use allEntries vs. displayedEntries?

2022-02-15 15:41 UTC, twschiller commented on src/components/logViewer/useLogEntriesView.ts
> +  const { allEntries, displayedEntries } = useContext(LogContext);
See comment on LogContext. I'm not following what allEntries is vs. displayedEntries

2022-02-15 15:43 UTC, twschiller requested changes
In general this looks good. I think I'm missing something on the naming, though? I'm not sure what the allEntries vs. displayedEntries distinction is?

2022-02-15 16:24 UTC, BALEHOK commented on src/devTools/editor/tabs/logs/NavItemBadge.tsx
> +      (x) => Number(x.timestamp) > lastTimestamp
This was transferred from `useLogEntries`, from the `LogEntry` I can say that `timestamp` is a string.

2022-02-15 16:41 UTC, BLoe commented on src/devTools/editor/panes/EditorPane.tsx
> +const EditorPane: React.FunctionComponent<{
Why did you split this into two components?

2022-02-15 16:42 UTC, BALEHOK commented on src/components/logViewer/ContextLogs.tsx
> +  displayedEntries: LogEntry[];
As I understand the idea about the log table is to show available entries, keep track of new entries, but not update the table, only display the number of new entries.

2022-02-15 16:57 UTC, BLoe commented on src/devTools/editor/panes/EditorPane.tsx
> +const EditorPane: React.FunctionComponent<{
Sorry, not following, why did that require a separate component here?

2022-02-15 17:05 UTC, BLoe commented on src/components/logViewer/ContextLogs.tsx
> +export const ContextLogs: React.FunctionComponent<ContextLogsProps> = ({
`ContextLogs` is a really unintuitive name to me here. Can we use something like `LogProvider` or `LogContextProvider`?

2022-02-15 19:01 UTC, BALEHOK commented on src/components/logViewer/ContextLogs.tsx
> +export const ContextLogs: React.FunctionComponent<ContextLogsProps> = ({
`Provider` totally makes sense to me. This thing provides logs for a given MessageContext. Maybe this is not very important for the naming thouhg and `LogProvider` will do (or `LogContextProvider`)

2022-02-15 20:25 UTC, twschiller commented on src/components/logViewer/ContextLogs.tsx
> +  displayedEntries: LogEntry[];
I would be OK moving forward as long as we comment allEntries and displayedEntries so that it's clear how each is supposed to be used

The "displayed" terminology is a confusing because it doesn't take into item level or pagination. 

The following might be a little bit less confusing?
- allEntries -> availableEntries
- displayedEntries -> entries

The names don't matter as much about having clear documentation on the props in the type

2022-02-15 20:25 UTC, twschiller commented on src/components/logViewer/ContextLogs.tsx
> +    if (isLoading) {
Why is this check necessary here?

2022-02-15 21:14 UTC, BALEHOK commented on src/devTools/editor/panes/EditorPane.tsx
> +const EditorPane: React.FunctionComponent<{
Formik provides the element. To fetch the logs I need to build MessageContext. MessageContext is built based on the element (id and blueprint id). The MessageContext should be the same object (by ref) regardless of changes of the Formik state (i.e. when I type, context doesn't change). This can be achieved in multiple ways, one of them is to use `useMemo`, but can't do that inline in jsx, hence another component.

2022-02-16 10:25 UTC, BALEHOK commented
Draft version of Redux state management.

2022-02-16 23:00 UTC, BLoe reviewed
Just a few comments here. I like where this is headed overall though!

2022-02-16 23:00 UTC, BLoe commented on src/devTools/editor/tabs/logs/NavItemBadge.tsx
> +      (x) => Number(x.timestamp) > lastTimestamp
Let's change the data type here to number. I searched for all references in the code, and it's actually cast to string when set and then cast to number everywhere in the app it's used 🤦

2022-02-16 23:00 UTC, BLoe commented on src/devTools/store.ts
> +store.dispatch(logActions.pollLogs());
Is there any way we can fix this type also? It's ok if not, not a huge deal.

2022-02-17 07:10 UTC, BALEHOK commented on src/components/logViewer/logSlice.ts
> +    setContext(state, { payload: context }: { payload: MessageContext }) {
Hm, I see no difference.

Method, recognises the type of state
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3116723/154423350-7864334e-1537-4967-a8ee-2eacb877aae5.png">

Arrow function, doesn't infer the type of argument without the explicit hint:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3116723/154423573-9dcdd963-275f-4b4b-a35b-1a15adcbf19c.png">

I'd keep the existing method signature for the sake of consistency (and also it look better to me).

2022-02-17 08:07 UTC, BALEHOK commented on src/devTools/store.ts
> +store.dispatch(logActions.pollLogs());
yes, there is. insanely tricky to find, not obvious in its effect, but super simple to implement
need to fix the type of middleware `as const`
https://github.com/pixiebrix/pixiebrix-extension/pull/2705/files#diff-97441eb7506529f53e2cc5ffd512a150a32e82583b9d2c3541f0223191049bf6R105

2022-02-17 08:14 UTC, BALEHOK commented on src/devTools/editor/tabs/logs/NavItemBadge.tsx
> +      (x) => Number(x.timestamp) > lastTimestamp
Good call! I created a separate issue https://github.com/pixiebrix/pixiebrix-extension/issues/2762

2022-02-17 15:44 UTC, twschiller approved these changes

2022-02-17 15:44 UTC, merged