Feature/2679 blueprints page performance
pixiebrix/pixiebrix-extension pull request #2759
Opened 2022-02-17 01:31 UTC by mnholtz

- [ ] Add groupby headings to virtualized GridView
- [ ] Investigate other performance wins

2022-02-19 04:19 UTC, fregante commented
My understanding is that we're using `react-virtualized-auto-sizer` to only render visible elements, but we're not using the `List` component that the [documentation](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md) suggests, which is what limits the rendering of invisible elements. 

It appears that every element is rendered on load because:

- the rendering delay depends on the list length ("All blueprints" takes far longer than "The Pixies Blueprints")
- a `console.log` in `TableRow` is printed for every single element of the list on startup

2022-02-24 20:50 UTC, mnholtz commented on src/options/pages/blueprints/BlueprintActions.tsx
> +  } = useSelector(appApi.endpoints.getAuth.select());
@BALEHOK wanted to bring up this consideration that todd mentioned:
> What gets returned when the data is fetching? Undefined?

I couldn't find the answer to this question after > 20min of research. I could dig deeper, but wondered if you knew the answer to this.

2022-02-25 21:34 UTC, twschiller commented on src/options/pages/blueprints/BlueprintActions.tsx
> +  } = useSelector(appApi.endpoints.getAuth.select());
The easiest way to check this is to just try it out. On your backend just add a sleep(10 seconds) and see what happens

2022-02-25 21:34 UTC, twschiller commented on src/options/pages/blueprints/BlueprintActions.tsx
> +      ...(actions.viewShare
Instead of using both a ternary and hide, let's just use the hide field?

2022-02-25 21:35 UTC, twschiller commented on src/options/pages/blueprints/BlueprintActions.tsx
> +      ...(actions.reinstall
Same comment as above - just use the hide prop for this?

2022-02-25 21:39 UTC, twschiller commented on src/options/pages/blueprints/gridView/GridView.tsx
> +    setListKey(uuidv4);
This should be `setListKey(uuidv4())` with parens

This happens to work because it's using the `prev => next` signature of setListKey. But it's clearer to just pass the value directly

2022-02-25 21:41 UTC, twschiller commented on src/options/pages/blueprints/listView/ListView.tsx
> +  const flatRows = [];
This is OK. You could use rows.flatMap here to write this in functional style

2022-02-25 21:41 UTC, twschiller commented on src/options/pages/blueprints/listView/ListView.tsx
> +    setListKey(uuidv4);
Same comment as other use

2022-02-25 21:43 UTC, twschiller commented on src/options/pages/blueprints/useInstallableActions.ts
> +  const reinstall = useCallback(() => {
We might consider writing these as one useMemo returning a dictionary of function instead of a useCallback for each

2022-02-25 21:45 UTC, twschiller commented on src/options/pages/blueprints/gridView/GridView.tsx
> +// Expands react-table grouped rows recursively, and groups
Write using method documentation syntax: `/**`

2022-02-25 21:46 UTC, twschiller commented on src/options/pages/blueprints/gridView/GridView.tsx
> +function expandGridRows(
This would be a good method to write tests for

2022-02-25 21:46 UTC, twschiller commented on src/options/pages/blueprints/gridView/GridView.tsx
> +      return "isGrouped" in row ? 43 : minCardSizeInPixels;
Where is 43 coming from?

2022-02-25 21:47 UTC, twschiller commented on src/options/pages/blueprints/gridView/GridView.tsx
> +  const minCardSizeInPixels = 215;
Let's lift the magic constants out to module level constants. E.g, MIN_CARD_HEIGHT_PX, HEADER_ROW_HEIGHT_PX

2022-02-25 21:48 UTC, twschiller commented on src/options/pages/blueprints/listView/ListView.tsx
> +  const rowSizeInPixels = 67;
Don't use size. Use height or width unless its a square

2022-02-25 21:49 UTC, twschiller approved these changes
Performance-wise, this is working well. I left some comments on code readability

2022-02-26 01:25 UTC, mnholtz commented on src/options/pages/blueprints/gridView/GridView.tsx
> +    setListKey(uuidv4);
Oops! my mistake. Although that's interesting why it still works.

2022-02-27 01:53 UTC, fregante approved these changes
I can confirm that the performance is 💯 on my end as well

2022-02-27 01:58 UTC, fregante commented on src/options/pages/blueprints/gridView/GridView.tsx
> +// Expands react-table grouped rows recursively, and groups
More info: https://www.jetbrains.com/help/webstorm/creating-jsdoc-comments.html

2022-02-28 11:47 UTC, BALEHOK requested changes

2022-02-28 11:47 UTC, BALEHOK commented on src/options/pages/blueprints/gridView/GridView.tsx
> +              />
The GridCard component is memoized.
1. Does it actually give a performance gain?
2. Just to make sure, the object reference of `row.original` doesn't change between renders, so the memorization works.

2022-02-28 11:47 UTC, BALEHOK commented on src/options/pages/blueprints/listView/ListGroupHeader.tsx
> +export default React.memo(ListGroupHeader);
This component seems to be very basic, why use memorization?

2022-02-28 11:47 UTC, BALEHOK commented on src/options/pages/blueprints/useInstallableActions.ts
> +  const reinstall = useCallback(() => {
I agree, a single `useMemo` or no memoization.

2022-02-28 21:38 UTC, mnholtz commented on src/options/pages/blueprints/BlueprintActions.tsx
> +  } = useSelector(appApi.endpoints.getAuth.select());
@twschiller I tried this out. The data always had status "fulfilled" after shutting down the server, i think because RTK query keeps data in the cache [while there are still active subscribers to an endpoint?](https://redux-toolkit.js.org/rtk-query/usage/cache-behavior#:~:text=Data%20is%20kept%20in%20the%20cache%20as%20long%20as%20at%20least%20one%20active%20subscriber%20is%20interested%20in%20that%20endpoint%20%2B%20parameter%20combination.) I'm pretty sure using `select()` doesn't create a subscriber, but I assume that the `useGetAuthQuery` in App.tsx does?

2022-02-28 22:13 UTC, merged