#2770 Fix text fields showing the workshop message when a user types mustache syntax
pixiebrix/pixiebrix-extension pull request #2820
Opened 2022-02-22 22:48 UTC by BLoe

Fixes #2770.

Instead of blocking the field with the workshop message, I moved the template checking into the main validation logic so the field will just show an error message instead.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2801308/155232575-969fb33f-a8e1-4f60-bd7e-01f05b967537.png">

2022-02-22 23:00 UTC, twschiller commented on src/devTools/editor/validation/validateStringTemplates.ts
> +    for (const prop in block.config) {
I think this needs to recurse through the config object?

2022-02-22 23:01 UTC, twschiller commented on src/devTools/editor/validation/validateStringTemplates.ts
> +        const propNamePath = `${index}.config.${prop}`;
This should use the [joinName](http://github.com/pixiebrix/pixiebrix-extension/blob/7175bad4863a6a1e0b7ed9716729b4b06140b838/src/utils.ts#L51-L51) method to centralize the formik field path logic

2022-02-23 03:17 UTC, twschiller commented on src/components/fields/schemaFields/BasicSchemaField.tsx
> +      error={error}
👍

2022-02-23 03:21 UTC, twschiller commented
I think this approach makes sense. We need to tweak the error copy though because it's too technical. (We can't assume people know mustache vs. nunjucks). Could you reach out to @orliesaurus on terminology based on how he's explaining in the Page Editor guide? 

To confirm my understanding:
- What is shown to for fields that contain mustache when upgrading from v2 to v3? It's shows as clean until they touch the field?

2022-02-23 15:14 UTC, BLoe commented on src/devTools/editor/validation/validateStringTemplates.ts
> +    for (const prop in block.config) {
Yep, you're right

2022-02-23 15:15 UTC, BLoe commented
>What is shown to for fields that contain mustache when upgrading from v2 to v3? It's shows as clean until they touch the field?

Yes, exactly. As long as you don't edit the field it will stay as a mustache template and work fine. Once you make an edit, it will change to nunjucks and show the error if the field contains mustache syntax.

2022-02-23 20:29 UTC, BLoe commented
@twschiller Here's what it looks like with an updated, simpler error message and a link to Orlando's docs page:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/2801308/155402970-16f079f0-c1db-4791-83b4-c55cc3219ea5.png">

2022-02-23 20:31 UTC, BLoe commented on src/components/form/FieldTemplate.tsx
> +            dangerouslySetInnerHTML={{ __html: getErrorMessage(error) }}
@twschiller This seems kind of sketchy since who knows what kind of error message might end up here from whatever is using the `FieldTemplate`. This allowed me to put a link inside the error message string and store it as a `string` in the `FormikErrorTree`. Should I figure out another way to handle this instead? I could remove the link or leave it in as a raw text url that isn't "linkified."

2022-02-24 10:06 UTC, BALEHOK commented on src/components/form/FieldTemplate.tsx
> +            dangerouslySetInnerHTML={{ __html: getErrorMessage(error) }}
As a rule of thumb, you avoid `dangerouslySetInnerHTML` unless it's absolutely necessary.
If you opt for it, it's a good practice to [sanitize](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/utils/sanitize.ts#L27) before inserting. And please leave a comment, why you have to `dangerouslySetInnerHTML` here ;)

2022-02-24 11:43 UTC, fregante commented on src/components/form/FieldTemplate.tsx
> +            dangerouslySetInnerHTML={{ __html: getErrorMessage(error) }}
What if the user types `<p>` and the error contains that? This error and related HTML can end up in any logs and we don't want to also render those. 

Since this is currently the only place where the HTML is rendered, it can instead contain code like:

```js
{error.message === 'Invalid string template') ?
	<>${error.message}. <a href="">Learn more etc</a> :
	error.message}
```

Or even a more generic `<RenderedError error={error}/>` component where we can add more context to any error anywhere. Perhaps the extra HTML can be stored on the error itself when throwing it:

```js
const error = new Error('Invalid string template');
error.contextualHelp = <>You can <a>learn more</a></>
throw error;
```

2022-02-24 14:54 UTC, twschiller commented on src/components/form/FieldTemplate.tsx
> +            dangerouslySetInnerHTML={{ __html: getErrorMessage(error) }}
I agree with @BALEHOK  and @fregante 

We should not have arbitrary HTML (especially unsanitized) in error messages. If we do want to include a link, it should either be 1) a property on the error, or 2) we linkify any URLs in the error message

Does Formik support objects for errors? 

If Formik does not support error objects, I think to move forward on this particular issue (which is a rare issue), I think it'd be OK to just show the unlinkified URL. We can then open a ticket to address the problem more generally

2022-02-24 17:45 UTC, BLoe commented on src/components/form/FieldTemplate.tsx
> +            dangerouslySetInnerHTML={{ __html: getErrorMessage(error) }}
The `FormikErrorTree` type is restricted to `string` for the leaf values in the tree. I'll just leave it as an un-linkified url for now.

2022-02-24 17:57 UTC, BLoe commented
Should be good to go here on changes @twschiller

2022-02-25 01:02 UTC, twschiller commented
There's a bug where under the Object K:V table, there's an [object] error message

![image](https://user-images.githubusercontent.com/1879821/155633567-e0c9143d-d3ac-4bfe-914c-2289f55e0b16.png)

Also happens for the tour bricks

![image](https://user-images.githubusercontent.com/1879821/155633652-e65cd703-7db1-4dc0-9ebb-93206b2aed13.png)

I think you need to only show the error if it's a string?

2022-02-25 01:04 UTC, twschiller commented on src/devTools/editor/validation/validateStringTemplates.ts
> +  for (const prop in config) {
Prefer `const prop of Object.keys(config)` here

2022-02-25 01:06 UTC, twschiller requested changes
See bug showing [error] on nested fields

2022-02-28 18:05 UTC, twschiller approved these changes

2022-02-28 19:02 UTC, merged