#2557 part 3 - Move blueprint options tab
pixiebrix/pixiebrix-extension pull request #2859
Opened 2022-03-02 16:39 UTC by BLoe

This is part 3 of #2557.

* Move blueprint options tab to the recipe in the sidebar, remove from extension config panel
* Use separate, local formik state for blueprint options

_Draft status:_
* Saving recipe options is not yet implemented

2022-03-02 20:10 UTC, BALEHOK approved these changes
Looks good. Maybe we can mark the `BlueprintOptionsTab` as deprecated to indicated that it is going to be removed?

2022-03-02 20:19 UTC, BLoe commented
Good idea, I can start marking some things as deprecated going forward for this stuff.

2022-03-11 16:16 UTC, BLoe commented
@BALEHOK @twschiller Open to suggestions on how to add test coverage to this, what do you guys think makes sense?

2022-03-11 19:57 UTC, twschiller commented on src/pageEditor/hooks/useRemoveRecipe.ts
> +  return useCallback(async (recipe: RecipeDefinition) => {}, []);
NIT: Use console.warn in here?

2022-03-11 20:02 UTC, twschiller commented
Encountering some bugs:

This one without any options defined just hangs:
![image](https://user-images.githubusercontent.com/1879821/157950395-b200fce3-c140-4c25-8c2b-73ee5e07559a.png)

This one is complaining about root? Might be because it's a v1 blueprint. (We don't need to support v1 blueprints in the Page Editor though)
![image](https://user-images.githubusercontent.com/1879821/157950454-5f06dd5b-aee8-468e-86bd-ee4a22e6fdf0.png)

```
apiVersion: v1
kind: recipe
metadata:
  id: "@todd/options-test"
  version: 1.0.2
  name: Blueprint Options test
  description: Drafts context menus for creating drafts
options:
    schema:
        template:
            type: string
            description: Note template for creating a new draft
            default: |
                {{{ selectionText }}}
                Copied from: {{{ documentUrl }}}
        tacos:
            type: string
            enum:
                - Yes pleasE!
    uiSchema:
        template:
            ui:widget: textarea
extensionPoints:
  - id: "@pixiebrix/context-search"
    label: Create Draft from selection
    config:
      title: 'Create Draft: %s'
      action:
        - id: "@pixiebrix/template"
          outputKey: text
          config:
              template: "@options.template"
        - id: drafts/create
          config:
              text: "@text"
```

2022-03-11 20:08 UTC, twschiller commented on src/pageEditor/panes/RecipePane.tsx
> +  const [layoutKey, setLayoutKey] = useState(1);
What is the layoutKey? Provide a comment for what it's for

2022-03-11 20:08 UTC, twschiller commented on src/pageEditor/panes/RecipePane.tsx
> +    setLayoutKey(layoutKey * -1);
Why multiply by negative 1?

2022-03-11 20:08 UTC, twschiller commented on src/pageEditor/panes/RecipePane.tsx
> +    setLayoutKey(layoutKey * -1);
Comments on how the layoutKey works would be helpful

2022-03-11 20:09 UTC, twschiller commented on src/pageEditor/panes/RecipePane.tsx
> +        onClick() {
NIT: use arrow syntax

2022-03-11 20:10 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      setIsSaving(false);
This need to be in a try/finally. Otherwise this can get stuck a saving state on any errors

2022-03-11 20:11 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +  boolean
Return an object instead of a tuple. Having boolean flags around is hard to work with because you have to look at the implementation to see what the flag means

2022-03-11 20:13 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      const updateRecipeResponse = await updateRecipe({
You can call `unwrap` to make it actually throw an error if it fails

2022-03-11 20:13 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +          message: errorMessage,
NIT: just pass the error message directly

2022-03-11 20:14 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +        if (isEmpty(newOptions.schema?.properties)) {
NIT: prefer ternary operator in cases like these were both code paths assign to the same variable

2022-03-11 20:17 UTC, twschiller commented on src/pageEditor/sidebar/RecipeEntry.tsx
> +  const isDirty = useMemo(() => {
Per the articles Aleksandr posted, this likely doesn't need to be in useMemo

The check is quick and since it returns a boolean downstream components don't benefit from reference equality

2022-03-11 20:18 UTC, twschiller commented on src/pageEditor/sidebar/RecipeEntry.tsx
> +    RootState,
I'm surprised you have to write the type on this. Doesn't it just get inferred from the selector?

2022-03-11 20:19 UTC, twschiller commented on src/pageEditor/sidebar/RecipeEntry.tsx
> +    return hasDirtyElements || hasDirtyOptions;
Can this just be a a selector based on state (which has activeRecipeId, dirtyElements, dirtyOptions)?

2022-03-11 20:21 UTC, twschiller commented on src/pageEditor/tabs/RecipeOptions.tsx
> +            console.error(
This should throw an error instead of just logging one

2022-03-11 20:22 UTC, twschiller commented on src/pageEditor/tabs/RecipeOptions.tsx
> +      <Container>
NIT: define as a constant outside of RecipeOptions

2022-03-11 20:24 UTC, twschiller commented on src/pageEditor/tabs/RecipeOptions.tsx
> +  const updateRedux = useDebouncedCallback(
There's a helper component [Effect](http://github.com/pixiebrix/pixiebrix-extension/blob/1815a3e6544ff6ec2c24256e6bae242afa60b9a5/src/pageEditor/components/Effect.tsx#L28-L28)

You might use that here?

2022-03-11 20:27 UTC, twschiller requested changes
See comment - unable to get it to work for QA

2022-03-14 13:41 UTC, BALEHOK commented on src/components/tabLayout/EditorTabLayout.tsx
> +  tabName: string;
Simply `name`?

2022-03-14 20:06 UTC, BLoe commented on src/pageEditor/panes/RecipePane.tsx
> +  const [layoutKey, setLayoutKey] = useState(1);
This is actually causing problems, I'm going to refactor it anyway

2022-03-14 23:58 UTC, BLoe commented on src/pageEditor/tabs/RecipeOptions.tsx
> +            console.error(
This is copied exactly from `EditorPane`. Should I change it to `throw` there as well?

2022-03-15 16:22 UTC, twschiller commented on src/pageEditor/tabs/RecipeOptions.tsx
> +            console.error(
Yes, I think it makes sense to. Otherwise we wouldn't get error telemetry from it

2022-03-15 16:29 UTC, twschiller commented
Low priority: The "noOptions" check is inaccurate for hand-coded options that don't define properties

![image](https://user-images.githubusercontent.com/1879821/158425596-303ce125-030c-4719-a894-36d875bc1d07.png)

2022-03-15 16:29 UTC, twschiller approved these changes

2022-03-15 19:52 UTC, merged