Upstream the app’s getErrorMessageWithAxiosSupport
pixiebrix/pixiebrix-extension pull request #2866
Opened 2022-03-04 09:15 UTC by fregante

From https://github.com/pixiebrix/pixiebrix-app/blob/30bd4e9d9170be96fbd9866af220015b572cb991/pixiebrix-app/src/helpers/errors.ts#L6-L15

2022-03-04 09:58 UTC, fregante commented
I'm going to try merge all of these into one tomorrow unless you have more input.

2022-03-05 12:31 UTC, twschiller commented
> I'm going to try merge all of these into one tomorrow unless you have more input. Generally I wonder why are these errors so deep in objects/array instead of being just {message: "Error"}? Can this be fixed in the app?

It's a bit tricky. Some of those exist to handle Django Rest Framework field error response format in general vs. DRF field error for a specific field on a specific endpoint vs. a non-field response error vs. another error

I will document why each of those exist w/ example payloads, so we can think about how to consolidate. On the long term, there's also changes we need to make to make things more consistent on our backend. (However, this method must also support other APIs)

2022-03-06 09:51 UTC, BALEHOK commented on src/errors.ts
>    if (isErrorObject(error)) {
Looks a little bit confusing to me:
the `warn` states it's "a non-Error" and then goes the check for `isErrorObject(error)`.

2022-03-06 12:55 UTC, fregante commented on src/errors.ts
>    if (isErrorObject(error)) {
First we check whether it's an instance of Error. If it isn't, it could just be an object like `{message: "Something happened", type: "Error"}`, which is probably a serialized error object. These objects should not be thrown but rather they should be deserialized first. This probably doesn't happen, but we need this log here to make sure.

2022-03-06 14:11 UTC, twschiller commented
@fregante here's the PR in the app project which covers some errors: https://github.com/pixiebrix/pixiebrix-app/pull/1318

I don't know where the "__all__" would be coming from

2022-03-08 04:29 UTC, twschiller commented
Here's the APP PR for standardizing error shape: https://github.com/pixiebrix/pixiebrix-app/issues/1330

Our JS client code should:
1. Look at error code
2. If it's a 400, then interpret as field names and non_field_errors
3. If it's a 4XX, look for detail property
4. Otherwise status text / code is the best we can probably reliably do

2022-03-19 08:04 UTC, fregante reviewed
Should be ready for merge

2022-03-19 08:04 UTC, fregante commented on src/errors.ts
> +    errorError.stack = `Error: ${syncErrorMessage}\n    at unknown (${originalError.filename}:${originalError.lineno}:${originalError.colno})`;
🆕 Mentioned in https://github.com/pixiebrix/pixiebrix-extension/issues/2826#issuecomment-1064717200

Unfortunately not available in `PromiseRejectionEvent`s.

Let's see if Rollbar is able to parse this correctly.

2022-03-19 14:27 UTC, twschiller commented on src/errors.ts
> -    // messenger boundary because. Can't use "name" like we do for serialized errors because Events don't have a name
> In neither case there's a type property.

I'm confused how it could be a PromiseRejectionEvent but not have a type property. PromiseRejectionEvent is a subtype of Event, which has a type property. https://developer.mozilla.org/en-US/docs/Web/API/Event/type

> I reverted this to a plain instanceof check just like the

I'm OK with this, and we can adjust other code accordingly if it's a problem

2022-03-19 14:59 UTC, fregante commented on src/errors.ts
> -    // messenger boundary because. Can't use "name" like we do for serialized errors because Events don't have a name
I mean that this piece of code was written to catch serialized PromisedRejectionEvents but even if this were to somehow happen, the type property would not be preserved. The screenshots show how ErrorEvent and PromiseRejectionEvent look after serialization (either with JSON.stringify or with serializeError). 

To test this you can use something like `serializeError(new PromiseRejectionEvent()).type === undefined`

2022-03-19 15:35 UTC, twschiller commented
@fregante I added the standard DRF error contract so that errors from our API are handled properly

However, I don't think the getErrorMessage correctly takes into account the use of the code's [enrichRequestError](http://github.com/pixiebrix/pixiebrix-extension/blob/4348b3aea930ed8e6fdcaf1d6dd9663051d06d45/src/services/requestErrorUtils.ts#L106-L106) method.

I think it might need to call [selectAxiosError](http://github.com/pixiebrix/pixiebrix-extension/blob/4348b3aea930ed8e6fdcaf1d6dd9663051d06d45/src/services/requestErrorUtils.ts#L86-L86)

However, to use that you'll need to clean up circular dependencies

2022-03-19 15:36 UTC, twschiller requested changes
I wrote out the DRF error message selection

See comment on handling enrichRequestError/selectAxiosError

2022-03-19 20:17 UTC, twschiller approved these changes

2022-03-19 20:21 UTC, merged