Move `@/options/store` to `@/store/store` (it's unrelated to the opti…
pixiebrix/pixiebrix-extension pull request #2936
Opened 2022-03-12 07:48 UTC by fregante

Part of:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2276
- https://github.com/pixiebrix/pixiebrix-extension/pull/2384
- https://github.com/pixiebrix/pixiebrix-extension/issues/2935

2022-03-12 18:09 UTC, twschiller requested changes
The options page and page editor have two different store configurations (e.g., because the Page Editor has a form builder slice). Here's the page editor store: http://github.com/pixiebrix/pixiebrix-extension/blob/09613df2831c95ec59e291726b63fd71781c2df6/src/pageEditor/store.ts#L77-L77

The sidebar app is currently using the options store. I think the correct way to go would be to have the sidebar app define its store that has only relevant slices for the sidebar app. E.g., the workshop slices, installedPage, etc. are not relevant

2022-03-14 11:15 UTC, BALEHOK commented
I don't think we should pull app specific configuration for the app to a shared folder. The `RootState`, store, persistor are defined for the Options app and should not be used in other apps (like PageEditor). Same applies to the PageEditor's store.

This has a lot to do with the directory structure: grouping stuff by their function (put in the same directory everything related to the store from all the apps) vs grouping by the domain (keep in the same directory everything related to the app, including store, pages, and components). I believe the latter is more maintainable. So Options store stays under `options` directory, PageEditor store stays under `pageEditor`. The common logic these stores use goes under `@/store`.

2022-03-14 12:29 UTC, twschiller commented
Thanks, @BALEHOK. To sum up:

- The reusable slices go in the `@store/` directory
- Each React app (options, pageEditor, sidebar) has their own store configuration file

From a search of useSelector, it looks like the extensionsSlice might be the only Redux slice used by the sidebar:

![image](https://user-images.githubusercontent.com/1879821/158172214-59e81166-5b03-4781-aeb7-a6a801d9e113.png)

2022-03-14 13:33 UTC, fregante commented
@BALEHOK Correct. This PR only tentatively moved the file because it already _is_ shared so the directory structure would match that. 

Since now it has come up that it doesn't have to be shared, I'll follow @twschiller's suggestion

@twschiller I'll give it a try

2022-03-16 10:42 UTC, fregante commented
Ok I duplicated the options store and dropped everything unrelated to the sidebar, including `routerMiddleware` which doesn't seem to be used in the pageEditor either. The sidebar seems to still work:

<img width="403" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/158572232-97dfbf88-54b4-441e-a152-267071b6a5ee.png">


As for `getSidebarStore` I'm not sure about the way forward, I had left this comment:

https://github.com/pixiebrix/pixiebrix-extension/blob/51d4669935812cc98baf495fb472166237ee03ed/src/sidebar/SidebarApp.tsx#L25-L26

2022-03-16 13:52 UTC, twschiller commented on src/sidebar/store.ts
> +      predicate: (getState, action) => !action.type.includes("logs/polling"),
This predicate won't do anything since we aren't using the logSlice in the store

- [ ] Remove unnecessary logger predicate

2022-03-16 13:53 UTC, twschiller commented on src/sidebar/store.ts
> +export type RootState = LogRootState & {
The LogRootState won't be in the sidebar shape since we aren't including the logSlice in the store (and don't need to include it, as the sidebar won't be displaying log information)

2022-03-16 13:57 UTC, twschiller commented on src/sidebar/store.ts
> +    options: persistReducer(
I was expecting to see the sidebar slice from [slice.ts](http://github.com/pixiebrix/pixiebrix-extension/blob/F/lint/options-store-location/src/sidebar/slice.ts#L36-L36) added to the Redux store. Currently it's being using in [React's useReducer](http://github.com/pixiebrix/pixiebrix-extension/blob/F/lint/options-store-location/src/sidebar/SidebarApp.tsx#L55-L55)

Are you still planning to do that?

2022-03-16 13:58 UTC, twschiller commented
> The lint rule highlights this context mismatch, which makes me think that function is currently not working as expected: it returns a `panels` array (in the current context) but the panels are only ever set in the content script.

Yes, the current behavior does look wrong. I would think that getSidebarStore would always just return an empty state

2022-03-16 20:48 UTC, twschiller approved these changes
@fregante Take a look at my commit. My initial testing seems to all be working as expected

One bonus side effect is that the panel loads faster

2022-03-16 22:47 UTC, merged