#2928 Simplify blueprint saving logic
pixiebrix/pixiebrix-extension pull request #2996
Opened 2022-03-22 19:09 UTC by BLoe

Closes #2928

2022-03-22 20:17 UTC, BALEHOK requested changes
Please add unit tests for saving logic.

2022-03-22 20:17 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +  const allRecipeElements = [...cleanRecipeExtensions, ...dirtyRecipeElements];
The naming is a little bit confusing to me: Extensions and Elements mixed together to make Elements.

2022-03-22 20:17 UTC, BALEHOK commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +          await create({ element, pushToCloud: false });
Doesn't this save every element in the Redux (including all the changed elements) even if it doesn't belong to the recipe?

2022-03-22 20:17 UTC, BALEHOK commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      );
it probably is more optimal to combine these 3 actions into a single one

2022-03-23 14:09 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +  const allRecipeElements = [...cleanRecipeExtensions, ...dirtyRecipeElements];
Even more confusing is the fact that later in the function `cleanRecipeExtensions` is used to form an all the `IExtensions` array.

2022-03-25 15:25 UTC, BLoe commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +        updateRecipeResponse = await updateRecipe({
For right now, yes. Once we add the "create recipe" functionality, this will have to create a new recipe in some cases instead.

2022-03-25 15:51 UTC, BLoe commented on src/pageEditor/panes/save/saveHelpers.ts
> +  const allRecipeElements = [...cleanRecipeExtensions, ...dirtyRecipeElements];
Ok, adjusted the naming here too.

2022-03-25 15:53 UTC, BLoe commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +          await create({ element, pushToCloud: false });
Yeah I'll fix this, thanks

2022-03-25 16:00 UTC, twschiller commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      );
That might be hard to do since options and editor are different slices? 

Agree it could make sense to combine resetRecipeMetadataAndOptions and updateRecipeMetadataForElements into a single reducer method

2022-03-25 16:11 UTC, BLoe commented on src/pageEditor/panes/RecipePane.tsx
> +      async onClick() {
I don't think I really know what the difference is here in this case. I guess I was thinking that making the click handler async and then awaiting the save function would make it less possible that a user could click the save button multiple times in quick succession and cause problems, but I don't actually know if that's how this works.

Do you think it makes more sense to leave this as a synchronous click handler and call `void saveRecipe()` instead?

2022-03-25 16:18 UTC, BLoe commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
This logic is different though. I only want to overwrite options in the draft if the options form state has a value. Your code here would remove all the options from a blueprint if I just open it and save without changing any options, since there will not be any options in the form state in this case.

2022-03-25 16:23 UTC, BLoe commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      );
The first action is in the other slice, yes. For the second and third, I could combine them, sure, but I still need to use the third one separately by itself for the general page editor reset button. Does it still make sense to combine them if they are not always called together in the same order?

2022-03-28 18:17 UTC, BLoe commented
QA checklist:
    * Add extension to a blueprint, leave the “keep local copy” option un-checked, ensure the extension is moved to the blueprint and no copy is left behind
    * Add extension to a blueprint, check the “keep local copy” option, ensure the extension is moved to the blueprint, and that a copy of the extension is kept independent as well
    * For both of the above, ensure saving works properly after making the change
        * Don’t keep copy, save
        * Keep copy, save

2022-03-28 18:54 UTC, BALEHOK commented on src/pageEditor/panes/save/useRecipeSaver.ts
> +      );
Didn't notice the actions are from different slices. It's ok.

2022-03-28 18:57 UTC, BALEHOK commented on src/pageEditor/panes/RecipePane.tsx
> +      async onClick() {
There's no magic behind `onClick` handlers, by default it will not await the returned promise. The signature of the method is `() => void`, let's follow this type definition and explicitly state that we disregard the async nature of the action here.

2022-03-28 19:03 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
Oh, do you mean that `options.schema` can have no properties and then you want to set `draft.options` to `undefined`? Now I got it, but is it really necessary? Can it work fine with:
```suggestion
    if (options) {
      draft.options = options;
    }
```

2022-03-28 19:16 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
^ can't show the wrong version though.
If that is important and the loop doesn't change, maybe it makes sense to report the name of the faulty extension together with its version?

2022-03-28 19:18 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
alternatively `find` can help, instead of `some`

2022-03-28 19:19 UTC, BALEHOK commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
it just reads better in my opinion

2022-03-28 19:21 UTC, BALEHOK approved these changes
All good, just a few suggestions that can improve readability.

2022-03-28 21:37 UTC, BLoe commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
I refactored this a bit 👍

2022-03-28 21:41 UTC, BLoe commented
@twschiller @BALEHOK I refactored the extensions apiVersion check and error handling in the save recipe function to be a little more concise.

2022-03-28 21:41 UTC, BLoe commented on src/pageEditor/panes/save/saveHelpers.ts
> +    }
I added a comment here and above the metadata part explaining the empty state.

2022-03-29 15:06 UTC, merged