#2906 JQuery Reader brick shows incorrect preview for trigger in eventTarget root mode
pixiebrix/pixiebrix-extension pull request #3015
Opened 2022-03-23 09:56 UTC by BALEHOK

Fixes #2906

2022-03-25 00:59 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +        Output previews are not supported for blocks with inherited rootMode and
Change copy to:

> Output Preview not supported because this brick's Root Mode is "Inherit" and the Trigger's Target Mode is "Event Target". Run the Trigger to see the output on the Output tab

2022-03-25 01:01 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +    blockRootMode === "inherit" &&
I don't think this condition is correct? I think it needs to check if the extension point is a trigger?

2022-03-25 01:02 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +  const extensionPointDefinition: any = extensionPoint.definition;
Let's avoid assigning to `any` here. Check if it's a trigger definition

- [ ] Avoid any

2022-03-25 01:03 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +  const blockRootMode = blockConfig.rootMode ?? "inherit";
Would be helpful to comment that this defaults to inherit due as described in documentation for BlockConfig.rootMode

2022-03-25 01:07 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +      // Note: not possible when extensionPoint's targetMode equals "targetElement"
Don't silently do the wrong behavior. If targetElement is undefined this will pass along undefined which downstream will cause the document to be used

At least in the comment indicate which check is preventing this from happening

2022-03-25 01:10 UTC, twschiller commented on src/contentScript/pageEditor.ts
> +    // Not 100% accurate, since we're looking for an element in the document,
I don't understand the comment. Won't this code path will only ever be used when the is root is the document?

The "closest" terminology is misleading. It would be $safeFind relative to the event target. In JQuery closest actually means the opposite, searching the ancestors: https://api.jquery.com/closest/

2022-03-25 01:11 UTC, twschiller commented on src/pageEditor/tabs/effect/BlockPreview.tsx
> +    blockRootMode === "inherit" &&
If you place a single button, the message is showing:

![image](https://user-images.githubusercontent.com/1879821/160035310-f22db578-7d3e-46e1-95ad-a0003dba08e6.png)

2022-03-25 01:12 UTC, twschiller requested changes
See comments about checking if the extension point is a trigger. The current behavior is incorrect for buttons (and potentially other extension points)

2022-03-25 16:29 UTC, BALEHOK commented on src/contentScript/pageEditor.ts
> +    // Not 100% accurate, since we're looking for an element in the document,
I added the comment mainly because of this code: https://github.com/pixiebrix/pixiebrix-extension/blob/756208b2286a83c576af71ac7c3041961648b3a1/src/extensionPoints/triggerExtension.ts#L331

If my understanding is correct the element may not be exactly the one returned by `$findSafe`.

2022-03-25 19:16 UTC, twschiller commented on src/contentScript/pageEditor.ts
> +    // Not 100% accurate, since we're looking for an element in the document,
Thanks for the link. If the selector is unique, it will always be the same element

The code you linked is to handle a gotcha with event targets during propagation:
- Takes the element that generated the DOM event (e.g., click)
- Finds the trigger target

The reason we have to do this is supposed we have:
```
<button id="foo"><span>abc</span></button>
```

If the triggerSelector is `#foo", when the user clicks if they click on the span part of the button (or maybe an icon on the button), the target will be the span during the event propagation

2022-03-28 10:25 UTC, BALEHOK commented on src/pageEditor/extensionPoints/elementConfig.ts
> +    type: ExtensionPointType;
The property `type` is actually there on the `FormState.extensionPoint.definition` , but wasn't included in the type definition and was assigned by `fromNativeElement` methods.
Maybe we can drop the `type` on the root level of `FormState`?

2022-03-28 10:26 UTC, BALEHOK commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +  type: "menuItem";
Should this type be called `MenuItemFormState`?

2022-03-28 16:15 UTC, BLoe commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +  type: "menuItem";
If we're going to update the naming, should we just change the entire thing to "button"/Button or "actionButton"/ActionButton or something like that? "menuItem" is not that much more accurate than "action" imo.

2022-03-28 16:18 UTC, BLoe commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +type PanesExtensionState = BaseExtensionState & Except<PanelConfig, "body">;
Typo here `Panes` --> `Panel`

2022-03-28 16:19 UTC, BLoe commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +type Extension = BaseExtensionState & Except<ContextMenuConfig, "action">;
Why is this just called `Extension`? Should it be `ContextMenuExtensionState`?

2022-03-28 18:48 UTC, BALEHOK commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +type Extension = BaseExtensionState & Except<ContextMenuConfig, "action">;
It should `ContextMenuExtensionState` :)

2022-03-29 00:32 UTC, twschiller commented on src/pageEditor/extensionPoints/elementConfig.ts
> +    type: ExtensionPointType;
> Maybe we can drop the type on the root level of FormState?

Let's keep it on the root level for this PR. Can refactor FormState in a separate PR later

2022-03-29 00:33 UTC, twschiller commented on src/pageEditor/extensionPoints/formStateTypes.ts
> +  type: "menuItem";
My vote would be for ButtonFormState. But let's not do in this PR

2022-03-29 00:44 UTC, twschiller approved these changes

2022-03-29 00:44 UTC, merged