#2919 Fixing trace entries for skipped bricks
pixiebrix/pixiebrix-extension pull request #3117
Opened 2022-04-07 12:12 UTC by BALEHOK

Closes #2919 

The skipped brick now creates a Trace Entry rather than Trace Exit
1. Trace Entry contains the required data such as timestamp and block config.
2. It seems to be more logical

2022-04-07 22:28 UTC, twschiller commented on src/pageEditor/tabs/editTab/EditTab.tsx
> +        if (traceRecord != null && !blockNodesHaveTraces) {
NIT: it's safe to set blockNodesHaveTraces to true multiple times. You don't have to check for !blockNodesHaveTraces

2022-04-07 22:29 UTC, twschiller commented on src/runtime/reducePipeline.ts
> +    // There's no corresponding trace entry for a skipped block
👍

2022-04-07 22:31 UTC, twschiller commented
Overall this looks good. It looks like the rendered args isn't working though?:

![image](https://user-images.githubusercontent.com/1879821/162330225-e934c47e-d696-4782-a071-dbc9c6686f21.png)

2022-04-07 22:32 UTC, twschiller requested changes
See comment on Rendered input not showing

2022-04-08 12:57 UTC, twschiller commented on src/runtime/reducePipeline.ts
> +      output: previousOutput as JsonObject,
I'm confused by this - wouldn't this be the output of the previous brick? If the brick is skipped, it won't have any output. (But it will have a rendered input)

2022-04-08 17:14 UTC, BALEHOK commented
Output of a skipped brick:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/3116723/162490061-b0b5c699-2fc8-4f63-9b41-857e682f3cf1.png">

2022-04-08 20:05 UTC, twschiller approved these changes

2022-04-08 20:05 UTC, merged