use useGetMeQuery endpoint for organizations
pixiebrix/pixiebrix-extension pull request #3165
Opened 2022-04-12 00:36 UTC by mnholtz

Fixes #3130

2022-04-12 01:00 UTC, twschiller commented
@BALEHOK could you help take a look?

2022-04-12 10:07 UTC, BALEHOK requested changes

2022-04-12 10:07 UTC, BALEHOK commented on src/options/pages/blueprints/useInstallableViewItems.tsx
> +  } = useGetMeQuery();
All the auth data is stored in the Auth slice. So you don't really need to call a query but rather select the organizations from Redux state.
``` javascript
const organizations = useSelector(selectOrganizations);
```

``` javascript
export const selectOrganizations = (state: AuthRootState) =>
  selectAuth(state).organizations;
```

Although the naming of the auth state properties `organization` and `organizations` might cause errors, maybe we could call them in a more distinguishable way.

2022-04-12 12:31 UTC, twschiller commented on src/options/pages/blueprints/useInstallableViewItems.tsx
> +  } = useGetMeQuery();
Thanks, @BALEHOK. An extra bit of context here is that the screen is wrapped in [RequireAuth](http://github.com/pixiebrix/pixiebrix-extension/blob/255255e7e05c31a35dcd5c62d22fd771b434504a/src/auth/RequireAuth.tsx#L57-L57), so the Me query will be available from the cache after the initial authentication

2022-04-12 16:42 UTC, mnholtz commented on src/options/pages/blueprints/useInstallableViewItems.tsx
> +  } = useGetMeQuery();
Selecting happens to be more clean/legible, so let's go with that. Also, for whatever reason `useGetMeQuery` was going through a loading state after all.

2022-04-12 16:54 UTC, BALEHOK commented on src/types/contract.ts
> +export type MeOrganization =
This is no longer needed.

2022-04-12 16:54 UTC, BALEHOK commented on src/auth/authSelectors.ts
> +  selectAuth(state).organizations;
@mnholtz Can we actually use `organizations` instead of `organization`?

2022-04-12 16:54 UTC, BALEHOK commented on src/options/pages/settings/SettingsPage.tsx
> +  const organization = useSelector(selectOrganizations);
If this is a legitimate change, pls rename the variable to `organizations`

2022-04-12 20:14 UTC, mnholtz commented on src/auth/authSelectors.ts
> +  selectAuth(state).organizations;
@BALEHOK I'm confused about this comment. Did you mean to say you want to use `organization` instead?

2022-04-13 11:07 UTC, twschiller commented on src/auth/authSelectors.ts
> +  selectAuth(state).organizations;
This be be related to an old version of the commit? https://github.com/pixiebrix/pixiebrix-extension/pull/3165#discussion_r848659812

There might have been a version where one side (the variable name) had a trailing "s", but the other side (the property access on the state didn't?)

2022-04-14 10:21 UTC, BALEHOK commented on src/auth/authSelectors.ts
> +  selectAuth(state).organizations;
The Auth state has 2 properties: `organization` and `organizations`.

This change basically replaces the existing usage of `organization` for ` organizations` (which is a different property of the state and `/me` response). `organization` was used by SettingsPage (`src/options/pages/settings/SettingsPage.tsx`). Thus the question: can we actually replace the usage of `organization` for `organizations`, can we drop `organization` entirely?

Happy to discuss this in Slack.

2022-04-14 17:50 UTC, mnholtz commented on src/auth/authSelectors.ts
> +  selectAuth(state).organizations;
Ahhh, I see. Got it.

2022-04-15 08:52 UTC, BALEHOK approved these changes

2022-04-15 08:52 UTC, BALEHOK commented on src/options/pages/blueprints/useInstallableViewItems.tsx
> +          source: getSharingType(installable, organizations ?? [], scope),
It's not required to check `organizations` for `null`. It's guaranteed to be an array.
See: https://github.com/pixiebrix/pixiebrix-extension/blob/744a87d0126dc7fb91559f8ef4fca2e3ee3cd1f7/src/auth/authSlice.ts#L32:L34

2022-04-15 17:03 UTC, merged