#3126 Fix RTK error type in base query
pixiebrix/pixiebrix-extension pull request #3167
Opened 2022-04-12 19:25 UTC by BALEHOK

Closes #3126

2022-04-12 19:27 UTC, twschiller commented on src/services/api.ts
> +        error: JSON.parse(JSON.stringify(error)),
Why not use serializerError here?

2022-04-18 17:51 UTC, twschiller commented on src/telemetry/reportError.ts
> +      typeof error === "string" ? error : serializeError(selectError(error)),
In what cases were we seeing a string error?

The selectError method gracefully handles strings by wrapping them in an error object: http://github.com/pixiebrix/pixiebrix-extension/blob/810f9b4f61e8e82e3560cf5ecdebe0ec7f29873e/src/errors.ts#L526-L526

2022-04-18 17:52 UTC, twschiller commented on src/pageEditor/ErrorBanner.tsx
> +    ? `Authentication error: ${getErrorMessage(accountError)}`
👍

2022-04-18 17:56 UTC, twschiller commented on src/auth/RequireAuth.tsx
> +    (meError as AxiosError)?.response?.status === 401 ||
NIT: this is the same condition as above. Let's put as one check:

```
const isUnauthenticated = (meError as AxiosError)?.response?.status === 401
```

2022-04-18 17:57 UTC, twschiller commented on src/auth/RequireAuth.tsx
> +  // RequireAuth only knows how to handle auth errors. Rethrow any other errors
👍

2022-04-18 18:00 UTC, twschiller commented on src/components/ErrorBoundary.tsx
> +        <Centered>
I don't think we want this change. I'm assuming you changing it to be consistent with the old ErrorPage?

Let's keep left aligned for now and we'll follow up with error screen styling

2022-04-18 18:01 UTC, twschiller commented on src/errors.ts
> +function selectNetworkErrorMessage(error: unknown): string {
Update the return type to be `string | null` to indicate that this method can return null if the error is not a network error

2022-04-18 18:02 UTC, twschiller commented on src/errors.ts
> +  // For examples of DRF errors, see the pixiebrix-app repository:
The "For examples of DRF errors" comment should stay on selectServerErrorMessage since the link is showing examples of 4XX error patterns

2022-04-18 18:04 UTC, twschiller commented on src/errors.ts
> -  // For examples of DRF errors, see the pixiebrix-app repository:
Should this method ever be called if response is null? If not, we should throw an error here if response is null?

Or, if we're relying on `safeGuessStatusText(response.status)` to return null, we should document this expectation

2022-04-18 18:05 UTC, twschiller requested changes
Overall this is in good shape. Left comments on code readability and explaining control flow/relationship between methods in places

2022-04-18 18:19 UTC, BALEHOK commented on src/telemetry/reportError.ts
> +      typeof error === "string" ? error : serializeError(selectError(error)),
The string error was coming from `useFetch` - `notify.error`. Regardless, you're right that the logic for strings handling here is not correct.

2022-04-18 18:41 UTC, twschiller commented on src/components/ErrorBoundary.tsx
> +        <div className="p-3">
👍

2022-04-18 18:59 UTC, twschiller approved these changes

2022-04-18 19:00 UTC, twschiller commented
![image](https://user-images.githubusercontent.com/1879821/163860842-082f4d25-0f71-467d-b649-f5cbee9b2286.png)

2022-04-18 19:00 UTC, merged