#2999 Add additional Page Editor success telemetry events
pixiebrix/pixiebrix-extension pull request #3203
Opened 2022-04-19 15:26 UTC by BALEHOK

Closes #2999

2022-04-19 16:02 UTC, BLoe approved these changes
Just a question about one of the events, seems fine otherwise 👍

2022-04-19 16:59 UTC, twschiller commented on src/pageEditor/toolbar/ReloadToolbar.tsx
> +    });
> Should we report the event before the actual run and then report success/failure outcome? Or is this intended to be the success event?

Thanks for the question, Ben. This should be before the `run`, since this event should capture the run and the error event will capture the error

2022-04-19 17:09 UTC, twschiller commented on src/pageEditor/tabs/editTab/EditTab.tsx
> +  useEffect(() => {
This will re-report the error everything the shape of the form changes. Steps to reproduce:

1) Add businesserror brick to the extension
2) Run the extension
3) Add a JQuery brick (or any other brick) before the business error brick
4) Remove the JQuery brick

You'll see that this effect runs on the pipeline edits

2022-04-19 17:10 UTC, twschiller requested changes
See comment on the error event firing one pipeline edits

2022-04-19 18:42 UTC, BALEHOK commented on src/pageEditor/tabs/editTab/EditTab.tsx
> +  useEffect(() => {
Good catch.
If the index of the node with an error changes, then the whole Formik error object changes. The `useEffect` fired in this case.

2022-04-19 18:53 UTC, twschiller commented on src/pageEditor/tabs/editTab/EditTab.tsx
> +  }, [runId, elementId, sessionId]);
@BALEHOK you should surpress the eslint warning here too

I was curious as to whether or not there's a race condition between the changes in runId and if blockPipelineErrors is updated in time. Did you happen to check that at all?

2022-04-20 15:40 UTC, BALEHOK commented on src/pageEditor/tabs/editTab/EditTab.tsx
> +  }, [runId, elementId, sessionId]);
Going to add a couple of tests for the hook...

2022-04-20 19:38 UTC, twschiller approved these changes

2022-04-20 19:38 UTC, merged