#2865: Various notification improvements
pixiebrix/pixiebrix-extension pull request #3531
Opened 2022-05-30 16:59 UTC by fregante

- Working on #2865

## Fix Notification timer (it was being ignored)

Fixed: All the notifications without a specified duration would last 2 seconds regardless of length

## Always place close button on the right + less `margin-right`

### Before

<img width="410" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/171035335-fe638efe-1fb5-4833-bbf5-9ba64ff9e103.png">

### After

<img width="459" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/171035272-a6b86243-f9ee-448f-b1f9-45f62d2f8840.png">

2022-05-30 17:56 UTC, fregante commented on src/utils/notify.tsx
> +  return Math.max(
## Fix Notification timer (it was being ignored)

Fixed: All the notifications without a specified duration would last 2 seconds regardless of length

2022-05-30 17:56 UTC, fregante commented on package.json
> -    "@types/notifyjs-browser": "0.0.0",
## Drop outdated types (requires review)

I think that Notify.js’ types are somehow part of the public Alert brick’s config and the whole object was being passed _as was_ to the notifier. However we kind of broke that month ago when we dropped the library. Now I'm making the last step of replacing the `className` setting with just `type`. There's no migration path and I don't think it was ever necessary since error events should use `error` type, and so on…

2022-05-30 17:56 UTC, fregante commented on src/utils/notify.tsx
> +    <span className={styles.message}>{message}</span>
## Always place close button on the right + less `margin-right`

### Before

<img width="410" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/171035335-fe638efe-1fb5-4833-bbf5-9ba64ff9e103.png">

### After

<img width="459" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/171035272-a6b86243-f9ee-448f-b1f9-45f62d2f8840.png">

2022-05-30 17:56 UTC, fregante commented on src/utils/notify.tsx
> +    style: { marginLeft: `calc(var(${SIDEBAR_WIDTH_CSS_PROPERTY}, 0) * -1)` },
## Keep notifications centered even with sidebar open


### Before

This covers our own UI

<img width="830" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/171040326-3596fc02-2d54-435e-8c99-233698cab594.png">


### After

Keeps the notification out of the sidebar, which could theoretically have its own notifications

<img width="833" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/171040309-e838a1b8-adf9-49b9-b433-96de1c0bd86a.png">


### Demo

https://user-images.githubusercontent.com/1402241/171040321-214f0d21-16df-42b2-89a5-c1c2154e9ffd.mov

2022-05-30 17:56 UTC, fregante commented on src/utils/notify.tsx
> -export function notifyResult(
Dropped, `showNotification` takes its place. `extensionId` wasn't used and now it just matches that function

2022-05-30 21:25 UTC, twschiller commented on src/extensionPoints/menuItemExtension.ts
> +        showNotification({ ...DEFAULT_ACTION_RESULTS.success, ...onSuccess });
@fregante changing the the API breaks this. This was an affordance for menu extension authors to customize the style/configuration of the notifications

I don't think anyone ever used the feature in production, but I'm going to have to double-check before merging in the PR

2022-05-30 21:26 UTC, twschiller commented on package.json
> -    "@types/notifyjs-browser": "0.0.0",
> Now I'm making the last step of replacing the className setting with just type.

It's probably fine, but I'd have to see if anyone (probably not) is using the following affordance in production: https://github.com/pixiebrix/pixiebrix-extension/pull/3531/files#r885082918

2022-05-30 22:02 UTC, twschiller requested changes
@fregante I need to double-check this before merging: https://github.com/pixiebrix/pixiebrix-extension/pull/3531#discussion_r885083250

But had a question for you in that comment

2022-05-31 00:35 UTC, fregante commented on src/extensionPoints/menuItemExtension.ts
> +        showNotification({ ...DEFAULT_ACTION_RESULTS.success, ...onSuccess });
I forgot to comment on this, but I think this never worked. Didn't the order of the parameters here guarantee that the user's message and className properties would always be overridden by the DEFAULT_* object?

2022-05-31 00:37 UTC, fregante commented on package.json
> -    "@types/notifyjs-browser": "0.0.0",
That's correct. When I changed library months ago I mapped the `className` to the `type` property because that's how our code was using the library.

2022-05-31 01:30 UTC, twschiller commented on src/extensionPoints/menuItemExtension.ts
> +        showNotification({ ...DEFAULT_ACTION_RESULTS.success, ...onSuccess });
> Didn't the order of the parameters here guarantee that the user's message and className properties would always be overridden by the DEFAULT_* object?

I think you're right. I probably had misread the lodash documentation and never tested it manually with the overrides

https://lodash.com/docs/4.17.15#merge `Source objects are applied from left to right. Subsequent sources overwrite property assignments of previous sources.`

2022-05-31 01:39 UTC, twschiller approved these changes

2022-05-31 01:41 UTC, twschiller commented on package.json
> -    "@types/notifyjs-browser": "0.0.0",
> That's correct. When I changed library months ago I mapped the className to the type property because that's how our code was using the library.

Re-read some of our old documentation. With the old library you could pass props for controlling whether it was dismissible, etc. It wasn't very well documented and wasn't exposed in the Page Editor, though

2022-05-31 01:44 UTC, merged