#3601 - Fix bug with brick modal results disappearing
pixiebrix/pixiebrix-extension pull request #3602
Opened 2022-06-07 20:55 UTC by BLoe

## What does this PR do?

- Fixes #3601 

## Discussion

- The trade-off here is the tag list scrolls horizontally at narrower widths. I don't think it's that bad though, and I think it's better than figuring out how to make the icons/labels wrap in a non-ugly way.

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer @twschiller

2022-06-07 21:12 UTC, twschiller commented
This is happening for me:

![image](https://user-images.githubusercontent.com/1879821/172483502-7dc6466e-0060-4401-a341-5aaaf8d9c486.png)

2022-06-07 21:14 UTC, twschiller requested changes
See comment on unnecessary scroll based

2022-06-08 00:40 UTC, BLoe commented
@twschiller I think the scrollbars should be fixed now, let me know if you're still seeing issues.

2022-06-08 01:58 UTC, fregante commented on src/components/brickModal/TagList.module.scss
> +  min-width: 160px;
I think this is a magic number that only works with the current tag names and your fonts/text rendering. I think `min-content` is the right keyword to use, but I'd double check. 

Once that's set I don’t think you need 100% either, the width can be increased via `flex-grow` or its `display:grid` equivalent.

2022-06-08 01:58 UTC, fregante commented on src/components/brickModal/TagList.module.scss
> +  display: inline-flex;
If the parent is flex or grid, this shouldn't make a difference. `inline-*` elements aren't meant for layout

2022-06-08 01:58 UTC, fregante commented on src/components/brickModal/BrickModal.tsx
> +                        columnWidth={(width - 15) / RESULT_COLUMN_COUNT} // 15px for the scroll bar width
Scrollbars vary across systems: macOS defaults to 0, Windows 17px if I remember correctly. Does this module require a width set in pixels?

2022-06-08 01:58 UTC, fregante commented on src/components/brickModal/BrickModal.module.scss
> +    max-width: 1220px;
👍

2022-06-08 02:10 UTC, twschiller commented
@BLoe - working better. One NIT would be the placement of the scroll bar relative to the padding

![image](https://user-images.githubusercontent.com/1879821/172515902-5606af25-8978-45aa-a057-1e02a2288820.png)

One problem I'm experience when scrolling with the wheel is that the first scroll works, but continuing to trying to move the mouse wheel does nothing. Not sure if it's related to this issue. Or we can create a separate ticket

Re: Windows, let's make sure we have @orliesaurus test this out in a release build

2022-06-08 02:11 UTC, twschiller approved these changes
See other comment

2022-06-08 02:43 UTC, fregante commented
> the first scroll works, but continuing to trying to move the mouse wheel does nothing

Probably related to the second point in https://github.com/pixiebrix/pixiebrix-extension/issues/3574

This PR doesn't change the behavior for me in that regard

2022-06-08 02:45 UTC, fregante commented
Ooops I misclicked the "Update branch" button sorry 😅

2022-06-08 03:51 UTC, fregante commented
The most problematic part is Bootstrap’s layout primitives here. More often than not we're fighting them rather being helpful. Bootstrap layouts are meant for text/documents and not for interfaces. Specifically here they use `flex-wrap` on the `Row` which causes the right "column" to wrap. Interfaces shouldn't wrap.

The problem becomes much less severe by just replacing the `row` class with `d-flex` for example (still not good, but better than "empty")


## Code on `main`

<img width="886" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/172527751-9df84435-91ca-478a-aeee-65bdd7e8ed5f.png">

## s/row/d-flex/

<img width="887" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/172527771-b4c5b8f1-6a84-4fe8-98b0-38dd8d19aa49.png">

2022-06-13 20:12 UTC, merged