Integrated Paginated Table in CustomBricksCard
pixiebrix/pixiebrix-extension pull request #3628
Opened 2022-06-08 13:19 UTC by abdullah4244

Fixes #3593 
@twschiller I have modified PaginatedTable to support RowProps in case if we want to add any click event on entire row , or to override row styles or providing custom class to row
needed this as CustomBricksCard had custom styles for table row on hover and also click Event attached to entire row

2022-06-08 13:59 UTC, twschiller commented
Thanks @abdullah4244. Will need a couple small changes:

- [ ] Hide the "filter" records control in the paginated table footer. (Because the filtering/search) is done by the search bar up top
- [ ] Show a loading indicator during brick load (currently the table says no records found). Perhaps you can copy the [AsyncCard](https://github.com/pixiebrix/pixiebrix-app/blob/c0ca3b334504a0689b3c66da5f9bf18af5d6b6dd/pixiebrix-app/src/components/AsyncCard.tsx#L17-L17) component over from the app project

2022-06-08 14:04 UTC, abdullah4244 commented
> Thanks @abdullah4244. Will need a couple small changes:
> 
> * [ ]  Hide the "filter" records control in the paginated table footer. (Because the filtering/search) is done by the search bar up top
> * [ ]  Show a loading indicator during brick load (currently the table says no records found). Perhaps you can copy the [AsyncCard](https://github.com/pixiebrix/pixiebrix-app/blob/c0ca3b334504a0689b3c66da5f9bf18af5d6b6dd/pixiebrix-app/src/components/AsyncCard.tsx#L17-L17) component over from the app project

couple of questions
 remove filterRecord for this PaginatedTable instance used in customBricksCard or for every instance i.e to be used in extension 
 and i think search bar isn't working correctly as intended

2022-06-08 15:26 UTC, fregante requested changes

2022-06-08 15:26 UTC, fregante commented on src/components/paginatedTable/PaginatedTable.tsx
> +            <td className="d-block w-100">
Table elements shouldn't have `display: block` and do not need `width: 100%`

2022-06-08 15:51 UTC, twschiller commented on src/components/paginatedTable/PaginatedTable.tsx
> +            <td className="d-block w-100">
@fregante Thanks for the comment. This PR is moving some code over from the app. And that class name is there: https://github.com/pixiebrix/pixiebrix-app/blob/c0ca3b334504a0689b3c66da5f9bf18af5d6b6dd/pixiebrix-app/src/components/PaginatedTable.tsx#L255-L255

Out of scope of this PR to make any changes to the PaginatedTable structure/layout itself

2022-06-09 17:31 UTC, abdullah4244 commented on src/components/paginatedTable/PaginatedTable.tsx
> +            <td className="d-block w-100">
@fregante @twschiller and paginatedTable footer is sticky now i.e it keeps it view with horizontal scroll , not providing width to it will break that and we kind of can't provide width to element if it's not block ,flex or inline-block

2022-06-09 21:14 UTC, twschiller approved these changes
![image](https://user-images.githubusercontent.com/1879821/172945690-374372e5-09e9-4a9e-b3b3-f5702f9c4f6f.png)

2022-06-09 21:15 UTC, merged