Use plain elements to avoid style fights
pixiebrix/pixiebrix-extension pull request #3923
Opened 2022-07-31 07:19 UTC by fregante

I'm happy that most of the issues described in https://github.com/pixiebrix/pixiebrix-extension/issues/3574 were fixed 🎉 

## What does this PR do?

Closes https://github.com/pixiebrix/pixiebrix-extension/issues/3574

- addresses the last point about the hover state  text (removing it)
- avoids using BS components unnecessarily
	- `ListGroup.Item` did nothing and was not wrapped by `ListGroup`
	- `Card` was being used only for its border
	- both component’s styles were being specifically overridden by local styles
- adds focusability to the element (a11y), actually allowing the `:focus` style that was defined but unused

## Discussion

- I wanted to make the Add button smaller and always visible, but I'm sure you wouldn't have liked it, so I left it unchanged
- I equalized the x/y spacing of the cards

## Before

<img width="924" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/182014681-67125f0e-b99e-4e83-8d0c-3c1293080ef6.png">

## After

<img width="924" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/182014683-dd49ef7e-8d62-4918-b7eb-0d84adbd4678.png">

## Future Work

- [ ] Turn into one column in small windows

2022-07-31 07:31 UTC, fregante reviewed
~~Jest tests are failing and I'm not sure why. This is mostly a style/classes change. Help? 😃 ~~

2022-07-31 07:31 UTC, fregante commented on src/components/addBlockModal/BlockGridItem.module.scss
> +  &:not(:hover) .addButton {
Instead of overriding by default (`display: none`) and then re-setting it on :hover (`display: whatever`), we should use `:not(:hover)` to just set the "off" style once.

2022-07-31 07:31 UTC, fregante commented on src/components/addBlockModal/BlockGridItem.tsx
> +    className={styles.root}
These attributes were required by the lint. We're basically reconstructing a `button` without triggering a React runtime error due to the nested button

2022-08-01 02:15 UTC, BLoe commented on src/components/addBlockModal/BlockGridItem.tsx
> +    className={styles.root}
Yep, we've done this in other places as well!

2022-08-01 02:27 UTC, BLoe requested changes
It looks like you removed the "View Details" text, the `<span/>` on like 66 in the "before" part of the diff here. Do you mind adding that back please? I didn't see any mention of the change in your PR here and I don't think we want to remove it.

2022-08-01 02:29 UTC, BLoe commented
Sorry, I just went back and looked at the linked issue (#3574), I see the change is mentioned there. Is it possible to only hide this text at smaller widths? I think we'd like to keep it at least on larger widths for now.

2022-08-01 02:50 UTC, BLoe commented on src/components/addBlockModal/BlockGridItem.tsx
> +    role="button"
The reason tests are failing is that neither `<ListGroup.Item/>` nor `<Card/>` set any role to `button` on any of the nested divs that were being rendered before. There's a utility function in tests to add a brick that looks for anything with the role `button` and naively picks the first one and clicks it, assuming the `Add` button is the only actual button visible on the "screen" in the test.

https://github.com/pixiebrix/pixiebrix-extension/blob/019e214a7081c5f2e269a27305b123de7a5c855f/src/pageEditor/panes/EditorPane.test.tsx#L214

2022-08-01 02:58 UTC, fregante commented
> It looks like you removed the "View Details" text

I dropped it because it's redundant, every link on the web points to "more details". This is akin to overlaying the text "Switch to tab" when hovering a browser tab

![tabs](https://user-images.githubusercontent.com/1402241/182062661-a4b5feca-9b82-4e34-99f2-069e97f2147e.gif)

Also it's not clear how "View details" is linked to the action itself given that it receives no hover, it looks like dead text:

![before](https://user-images.githubusercontent.com/1402241/182062893-b28bd83f-23e3-4b1d-a8c1-cf4fd792a878.gif)

If we were to go down the rabbit hole and add a hover style, then it would feel like a different link to the larger button which _also_ receives a hover style 😬 

"View details" is also similar to "Click here", which [isn't the best way to link text.](https://granicus.com/blog/why-click-here-links-are-bad/) Underlining the title would be a common alternative:

![text](https://user-images.githubusercontent.com/1402241/182063486-b1576d8e-6761-4678-9bbc-0cc19e70de47.gif)

These are all the reasons why it'd be better to drop it.

2022-08-01 17:53 UTC, icugideon commented
Hi
So, @fregante made a very great point there.  

A generic Card list `on-click` interaction would be to Open/or dig deep into the current element to view or perform other interactions/actions. We surfaced the "+ add" as a quick action for the current card element, the "view details" text link on the other hand is redundant.

I believe,
* underlining the current card element title "on-hover" as mentioned or 
* having the Card list `on-click` interaction
to open/or dig deep into the current element, would be much better.

I could fix up what the interaction would look like on Figma - if more clarification is required.

2022-08-01 18:15 UTC, fregante commented
> * having the Card list `on-click` interaction
>   to open/or dig deep into the current element, would be much better.

I think that's what already happens, right? I'm not sure I understand otherwise

2022-08-01 18:17 UTC, icugideon commented
> > * having the Card list `on-click` interaction
> >   to open/or dig deep into the current element, would be much better.
> 
> I think that's what already happens, right? I'm not sure I understand otherwise

Yes. Apparently, that's the implementation we have currently - Just checked.

2022-08-02 20:26 UTC, BLoe commented
Ok great, thanks @icugideon, it sounds like you're on board with this change then? I'm going to unblock the PR here 🚀

2022-08-02 22:52 UTC, BLoe approved these changes

2022-08-03 02:19 UTC, merged