#3936 Improve messaging around missing permissions for HTTP requests
pixiebrix/pixiebrix-extension pull request #4013
Opened 2022-08-12 15:38 UTC by BALEHOK

## What does this PR do?

- Fixes #3936
- Validates permissions to request the configured URL

## Demo

Annotation message
<img width="1224" alt="Screen Shot 2022-08-12 at 5 31 19 PM" src="https://user-images.githubusercontent.com/3116723/184390192-4c166dfb-236e-41e2-a97f-162b8a68f8be.png">

Trace error
<img width="1227" alt="Screen Shot 2022-08-12 at 5 31 36 PM" src="https://user-images.githubusercontent.com/3116723/184390297-e53270e9-4fc0-4f1f-b7b4-abaa3e0e2b02.png">

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer @BLoe

2022-08-12 15:40 UTC, BALEHOK commented on src/components/errors/getErrorDetails.tsx
> -  // TODO: https://github.com/pixiebrix/pixiebrix-extension/issues/3613
This issue is closed

2022-08-12 15:42 UTC, BALEHOK commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
`error.response` is (almost) always defined, this branch triggered instead of permissions one

2022-08-12 15:52 UTC, fregante commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
I think we moved these down there just a couple of months ago. Can you use git blame to find out why? Maybe this change would trigger an old bug

2022-08-12 16:08 UTC, BALEHOK commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
Looks like it was moved to this file from requestErrorUtils
https://github.com/pixiebrix/pixiebrix-extension/pull/3014/files#diff-1d4d8e5c4765d77e50cfc4aa934c10eaf30710a4d23d6bc936ece013db9d294eR52

And it was in this order since the creation of requestErrorUtils
https://github.com/pixiebrix/pixiebrix-extension/pull/2624/files#diff-1699e7a857954885ff58ff4f3e442429913bd21215c58378961846eb90cb1873R116

cc @twschiller

2022-08-12 16:24 UTC, fregante commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +    await Promise.all(this.permissionCheckPromises);
I'm not super convinced about this pattern but I think there's no a better solution unless you move the logic out of the class itself. For example by specifically tracking the visitBlock calls outside the class — but I suppose this isn't as easy to do.

2022-08-12 16:24 UTC, fregante commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +      this.permissionCheckPromises.push(permissionCheckPromise);
Below this line, are you also going to await permissionCheckPromise? This way visitBlock will itself return a promise that can be awaited by its caller. I'm not sure if this is useful right now but I'd still do it to maintain the expectations from the caller's point of view.

2022-08-12 17:59 UTC, BALEHOK commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +      this.permissionCheckPromises.push(permissionCheckPromise);
This is the problem Todd and I touched on briefly a couple of weeks ago. There's PipelineVisitor, a class that knows how to traverse all the blocks in a pipeline including sub pipelines. In certain cases it should be synchronous. In other situations (like this one) we want `visitBlock` to be async, which means the `visitPipeline` (a method, that calls `visitBlock` for each block of the pipeline) has to be async making the PipelineVisitor async.
Options are:
1. Have sync PipelineVisitor and do tricks like this one.
2. Have 2 versions of PipelineVisitor, sync and async.
3. Check the actual return value of the `visitBlock` and `visitPipeline` and await in case of Promise.

2022-08-12 21:02 UTC, twschiller commented on src/analysis/analysisVisitors/baseAnalysisVisitors.ts
> +  run(extension: FormState): void {
👍

2022-08-12 21:04 UTC, twschiller commented on src/blocks/transformers/httpGet.ts
> +    super(
👍

2022-08-12 21:04 UTC, twschiller commented on src/blocks/transformers/remoteMethod.ts
> +  static BLOCK_ID = validateRegistryId("@pixiebrix/http");
👍

2022-08-12 21:15 UTC, twschiller commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
> error.response is (almost) always defined, this branch triggered instead of permissions one

My understanding of how permissions interacts with API calls is:
- If the remote server has a CORS policy, Chrome will block the request due to the failed CORS pre-flight check unless the it's in browser.permissions.contains. If it's blocked the error.response will be `undefined` (because the actual request isn't made)
- Some requests can sneak through without permissions if the server doesn't have CORS set

In the 2nd situation, the permissions check isn't what would have caused the request to fail, so it would be misleading to return that as the error

What situation are you trying to fix the error message of with this change?

2022-08-12 21:22 UTC, twschiller commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +                "Insufficient browser permissions to make request. Specify an Integration to access the API, or add an Extra Permissions rule to the extension.",
👍

2022-08-12 21:25 UTC, twschiller commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +      this.permissionCheckPromises.push(permissionCheckPromise);
> Have sync PipelineVisitor and do tricks like this one.

I'm OK with this hack in this PR approach for now

I suspect long term we'll end up with "2. Have 2 versions of PipelineVisitor, sync and async."

2022-08-12 21:27 UTC, twschiller requested changes
Looks good, I think we need to undo the enrichBusinessErrors change though: See comment here: https://github.com/pixiebrix/pixiebrix-extension/pull/4013/files#r944863486

2022-08-15 07:59 UTC, fregante commented on src/analysis/analysisVisitors/requestPermissionAnalysis.ts
> +      this.permissionCheckPromises.push(permissionCheckPromise);
> visitPipeline has to be async making the PipelineVisitor async

Might be worth mentioning in a code comment, including a link to your own comment

```
https://github.com/pixiebrix/pixiebrix-extension/pull/4013#discussion_r944690969
```


> I suspect long term we'll end up with "2. Have 2 versions of PipelineVisitor, sync and async."

Sounds good

2022-08-15 08:02 UTC, fregante commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
> Maybe this change would trigger an old bug

We should probably also mention this in a code comment to avoid changes in the future.

2022-08-15 08:46 UTC, BALEHOK commented on src/utils/enrichAxiosErrors.ts
>    if (error.response) {
It seems to work in different way though.
This is the request made by 
<img width="889" alt="Screen Shot 2022-08-15 at 10 04 06 AM" src="https://user-images.githubusercontent.com/3116723/184599417-a624da82-f8c2-4f4a-ae48-566aa4e6a85e.png">

The error object that we get from AXIOS does have a response (`tRes` == typeof error.response). The body can be actually parsed and read, the message reads `Network error` (the `error` is saved to `temp2` var)
<img width="1081" alt="Screen Shot 2022-08-15 at 10 04 46 AM" src="https://user-images.githubusercontent.com/3116723/184599608-9d37ae70-be59-467a-a190-f995f52b2acd.png">


HTTP block config:
<img width="1224" alt="Screen Shot 2022-08-15 at 10 08 39 AM" src="https://user-images.githubusercontent.com/3116723/184599520-af6b2066-5a94-45d2-ace0-ee308604056a.png">

The error is misleading however, I agree. It's not the browser (extension) permissions that block the request, but a server configuration.

2022-08-15 17:09 UTC, twschiller commented on src/utils/enrichAxiosErrors.ts
> +  if (error.response != null && error.response.status !== 0) {
👍

2022-08-15 17:10 UTC, twschiller approved these changes

2022-08-15 17:13 UTC, merged