#2273: Cancel all observers when extension is removed in extensionPoint.
pixiebrix/pixiebrix-extension pull request #4108
Opened 2022-08-24 08:09 UTC by jcforest

removeExtensions method is called when user select the extension in the sidebar.

## What does this PR do?

- Closes #2273 

## Reviewer Tips

@twschiller left comment on `removeExtensions` method of TriggerExtensionPoint. However after some debugging, I found that when extension is removed, the triggered observers are not cleared in extensionPoint.

## Discussion

- Do we have any side-effects if we cancel observers in removeExtensions method? 
- Another thing to discuss is I found a case that when we remove trigger extension (which is already running) in the page editor, it clears extension and cancel Observers in the current tab. However it doesn't cancel observers in the different tabs. Thus trigger is still running on different tabs until refresh. Is this case that we need to fix? 

## Checklist

- [ ] Designate a primary reviewer @twschiller

2022-08-24 19:32 UTC, twschiller commented
> However it doesn't cancel observers in the different tabs. Thus trigger is still running on different tabs until refresh. Is this case that we need to fix?

Thanks for raising that. I don't think we need to handle in this PR

This also comes up if the user uninstalls from the Blueprints Screen: https://github.com/pixiebrix/pixiebrix-extension/blob/21f8fc0ba474b922cdadace337846122d55b7e96/src/options/pages/blueprints/useInstallableViewItemActions.ts#L184-L184. There we call reactivateEveryTab, which I think ends up calling syncExtension on each extension point

2022-08-24 19:34 UTC, twschiller commented on src/extensionPoints/triggerExtension.ts
> +    this.cancelObservers();
I think it's only safe to cancel the observers if all of the extensions attached to the extension point are removed.

PixieBrix supported named extension points e.g., `@todd/my-trigger-extension-point` that multiple trigger extensions can be attached to

Say extension A and extension B are attached to it, and you start editing (or remove) extension B. The observer I think still needs to be attached so extension A still works

2022-08-24 19:36 UTC, twschiller commented on src/extensionPoints/triggerExtension.ts
> +    this.cancelObservers();
Did you figure out what the call the _runTrigger was still seeing the extension in `this.extensions` even after it's removed? https://github.com/pixiebrix/pixiebrix-extension/blob/21f8fc0ba474b922cdadace337846122d55b7e96/src/extensionPoints/triggerExtension.ts#L433-L433

2022-08-24 19:37 UTC, twschiller requested changes
See comment here: https://github.com/pixiebrix/pixiebrix-extension/pull/4108/files#r954226042

2022-08-25 08:46 UTC, jcforest commented
@twschiller I found an issue and fixed it. 
It was

2022-08-26 01:04 UTC, twschiller commented on src/contentScript/lifecycle.ts
> -  const extensionPoint = _installedExtensionPoints.find((x) => x.id);
🤦

2022-08-26 01:04 UTC, twschiller commented on src/extensionPoints/triggerExtension.ts
> +    // We need to cancelObservers in order to stop the trigger when extension is selected.
This comment is no longer relevant

2022-08-26 01:13 UTC, twschiller approved these changes
Checked out the branch and tested it ❤️ 

![image](https://user-images.githubusercontent.com/1879821/186795554-00df592e-192f-4c41-857b-291233b9e893.png)

2022-08-26 01:14 UTC, merged