#3504: Quickbar cant be closed by clicking outside
pixiebrix/pixiebrix-extension pull request #4114
Opened 2022-08-24 19:46 UTC by jcforest

## What does this PR do?

- Closes #3504 

## Reviewer Tips

- Upgraded kbar library version to "^0.1.0-beta.36"

## Checklist

- [ ] Designate a primary reviewer

2022-08-24 19:47 UTC, twschiller commented
@fregante could you help review?

2022-08-25 03:46 UTC, fregante commented
We already have this component and is named KBarToggle because it has to be customized.

I think we have two options:

- update our Toggle to match any Portal updates
- make sure that our Toggle can actually coexist with the Portal: does the feature overlap? Does it conflict? It should avoid any duplicate features. 

It's best to Blame the line to find out why I added the KBarToggle component to have more context (I'm not a React dev so it might have not been the best solution to begin with)

2022-08-25 03:51 UTC, fregante commented on package.json
> +    "kbar": "^0.1.0-beta.36",
By the way we're already using the latest version:

- https://github.com/pixiebrix/pixiebrix-extension/pull/3772

package.json isn't sometimes updated by dependabot because the semver range is still valid, but the lockfile points to the new value.

2022-08-25 07:32 UTC, jcforest commented on package.json
> +    "kbar": "^0.1.0-beta.36",
ok no worries. i just updated the package.json file as well

2022-08-25 07:34 UTC, jcforest commented
@fregante 
I removed KBarToggle Component that is modeling the `KBarPortal` form `kbar` library and implement the save/restore selection logic when open/hide QuickBar logic in the KBarComponent itself.

2022-08-26 15:21 UTC, fregante commented
I can't review on the implementation. As long as this works it's good for me:

- responds to cmd-k
- responds to global chrome shortcut set in chrome://extensions
- same as above, but on a domain without pre-existing conditions
- responds correctly after multiple invocations
- preserves/restores the text selection on the page after closing

2022-08-26 16:14 UTC, twschiller commented
Looks good overall, any idea what's going on with the border on LinkedIn?

Screenshots in the wild:

PixieBrix homepage:
![image](https://user-images.githubusercontent.com/1879821/186948051-0e11897a-47f3-4184-95cd-5b38ee949ff3.png)

LinkedIn: Not sure what's going on with the border?
![image](https://user-images.githubusercontent.com/1879821/186947884-2d8e1a48-1cf9-4721-bfd6-b5fbdda65d9a.png)

ESPN:
![image](https://user-images.githubusercontent.com/1879821/186947953-a1e1e71e-4e4e-4d99-acfb-2c2a5d0ff3e0.png)

2022-08-26 16:18 UTC, twschiller commented on src/components/quickBar/QuickBarApp.tsx
> +      <KBarPositioner style={{ zIndex: MAX_Z_INDEX }}>
See comment, I think we might need to wrap in a shadow root here

2022-08-26 16:19 UTC, twschiller requested changes
@jcforest see comment, I think we need to wrap the portaled components in a shadow root so that the style are properly isolated from the host page

2022-08-26 16:24 UTC, fregante commented on src/components/quickBar/QuickBarApp.tsx
> +      <KBarPositioner style={{ zIndex: MAX_Z_INDEX }}>
Ah yeah that's what we were doing with the local toggle implementation. KBarPortal breaks out of the dom shadow. "Portal" means "leave the current dom tree, and place the children somewhere else."  

This is why can't use the portal element.

2022-08-26 21:26 UTC, twschiller commented on src/components/quickBar/QuickBarApp.tsx
> +      <KBarPositioner style={{ zIndex: MAX_Z_INDEX }}>
We think we got it working putting the root inside the animator. Seems to be resilient to page styles so far

2022-08-26 21:39 UTC, twschiller commented
@jcforest I noticed in this version of the quickbar, the entry doesn't auto-focus, so you you have to click into the input to start typing. See Loom: https://www.loom.com/share/ae559fbb34f04b4e9d4ab9b72937e4c9

On main, I see the following behavior:
1. The first time you open the quickbar, the input is not focused
2. On subsequent shows it's focused

Presumably related to how we initialize the quickbar? https://github.com/pixiebrix/pixiebrix-extension/blob/feature%2F3504-quickbar-cant-be-closed-by-clicking-outside/src/components/quickBar/QuickBarApp.tsx#L146-L146

cc @corinnemayans (for UX triaging)

2022-08-28 08:30 UTC, fregante commented
> On `main`, I see the following behavior:
> 
> 1. The first time you open the quickbar on a page, the input is not focused

Note: This seems to happen when we don't have permissions to the website yet. It works correctly if the content script was already on the page.

2022-08-28 11:39 UTC, fregante requested changes
> On `main`, I see the following behavior:
> 
> 1. The first time you open the quickbar on a page, the input is not focused

On `main` it only happens when the content script isn't pre-injected (e.g. on a new website without permissions)

In this PR this issue happens at every invocation, the field is never focused.

2022-08-29 13:01 UTC, twschiller commented
> In this PR this issue happens at every invocation, the field is never focused.

@jcforest for this PR we need to ensure it's working if PixieBrix already has access to the page. We don't need to handle the other case Federico is mentioning in this PR (can open a separate ticket)

2022-08-29 19:48 UTC, twschiller approved these changes
Paired with @jcforest on the focus issue with our CSS gate. @fregante I think you need to re-review since you had requested changes

2022-08-29 19:51 UTC, fregante commented on src/components/Stylesheets.tsx
> +   * Chrome doesn't focus on the hidden elements so we want to make sure that component is rendered after the stylesheets are loaded.
Good find!

2022-08-29 20:39 UTC, merged