#3946: Add Salesforce unique selectors
pixiebrix/pixiebrix-extension pull request #4191
Opened 2022-08-31 08:45 UTC by jcforest

## What does this PR do?

- Closes #3946 

## Discussion

@fregante Is there any specific reason that you added `data-aura-rendered-by` to `UNSTABLE_SELECTORS` list [here](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/nativeEditor/selectorInference.ts#L67)? 

## Checklist

- [ ] Designate a primary reviewer

2022-08-31 08:46 UTC, jcforest commented
@twschiller @fregante I created PR here and still need to polish more however I'd like to hear feedback from you about this PR.

2022-08-31 09:12 UTC, fregante commented
> @fregante Is there any specific reason that you added `data-aura-rendered-by` to `UNSTABLE_SELECTORS` list [here](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/nativeEditor/selectorInference.ts?rgh-link-date=2022-08-31T08%3A45%3A00Z#L67)?

You can find out by following the commit on that line:

https://github.com/pixiebrix/pixiebrix-extension/commit/e7f1c6e96d1e3df96252797472898e3d1c3fa092#diff-b47f1bf1cb091c4cf74c73c060dda15e4157c34e828676587f054d7468937b02L166

The selector was part of the original blacklist so you'd have to ask @twschiller.

2022-08-31 18:34 UTC, twschiller commented
> The selector was part of the original blacklist so you'd have to ask @twschiller:

@jcforest while those selectors are unique, the are not reliable selectors. "Aura" is the UI framework used by Salesforce. Like emberjs, it adds attributes for which the values are valid on a single page load

![image](https://user-images.githubusercontent.com/1879821/187753427-2d91faf5-9c37-46f7-a5eb-7201a963ec75.png)

2022-08-31 18:35 UTC, twschiller requested changes
@jcforest let's connect on Zoom today to discuss the specification and approach

2022-09-01 02:42 UTC, jcforest commented
@twschiller When do we inject pageScript? 

The interesting point is the selector created from `safeCssSelector` function passes `requreSingleElement` validation [here](https://github.com/pixiebrix/pixiebrix-extension/blob/dadda478584d06d2015c7bbc3d98b42da07b035b/src/nativeEditor/selector.ts#L197) but it doesn't find the element with same selector in the pageScript.  (https://github.com/pixiebrix/pixiebrix-extension/blob/dadda478584d06d2015c7bbc3d98b42da07b035b/src/nativeEditor/selector.ts#L199)

2022-09-01 03:25 UTC, twschiller commented
> @twschiller When do we inject pageScript?

It's injected via the lifecycle file that runs when the contentScript is injected: https://github.com/pixiebrix/pixiebrix-extension/blob/e09c6e28eeaab3f1e1403b1ceb5cefd491302d7b/src/contentScript/lifecycle.ts#L54-L54

2022-09-02 07:34 UTC, jcforest commented
@jcforest To recap our call, here's what we need for this PR:

 Run selector generation from the content script instead of the page script when framework is not provided (to avoid the Salesforce issue with differences in selection behavior)
 Define a constant SALESFORCE_SELECTOR_HINTS, with properties for the following:
- Selector to determine if the site is a Salesforce lightening interface (i.e., if the heuristics should be applied), i.e., the "site rule"
- Array of selector patterns to denylist, e.g., patterns including the data-aura-rendered-by attribute
- Array of known good selector patterns
- Array of known good stable anchors on the page
 Modify the inference to take into account these site-specific rules if the site rule matches (in addition to the general rules)
 In the PR demo/writeup, please include examples of selectors generated for fields/parts of the salesforce interface
After this PR, we'll then choose another strategic SaaS application, e.g., Zendesk. Once we have a set of site heuristics, we'll work toward providing these from our serve so we can keep them up-to-date

2022-09-02 07:40 UTC, jcforest commented
@twschiller I updated PR as we discussed.

2022-09-02 19:08 UTC, twschiller commented on src/contentScript/nativeEditor/selectorInference.ts
> +export interface SITE_SELECTOR_HINT {
Types should follow PascalCase, SiteSelectorHint

2022-09-02 19:09 UTC, twschiller commented on src/contentScript/nativeEditor/selectorInference.ts
> +    SITE_NAME: "Salesforce",
Object property names should be camelCase

2022-09-02 19:09 UTC, twschiller commented on src/contentScript/nativeEditor/selectorInference.ts
> +const SELECTOR_HINTS: SITE_SELECTOR_HINT[] = [
👍 Constants as ALL_CAPS with snake

2022-09-02 21:14 UTC, twschiller approved these changes
Definitely a step in the right direction. Things I noticed: 

- We probably also need to make the change to the "container" branch of selectElement
- Inference is still slow on Salesforce for certain elements (likely just due to the page depth), so may want to show a progress indicator at somepoint so the user knows something is happening

2022-09-03 02:39 UTC, merged