#113: Update to Webpack 5
pixiebrix/pixiebrix-extension pull request #421
Opened 2021-06-03 16:52 UTC by fregante

Closes #113 

This appears to build and I'm pushing it here to double-check on the PR. I still need to test it and possibly refine it further. There are a lot of moving parts so it's taking a long while.

2021-06-03 19:37 UTC, fregante reviewed
Hallelujah CI passes

2021-06-03 19:59 UTC, fregante commented
The extension runs, but please do a quick run through to ensure it's not broken in some obvious ways.

2021-06-03 20:12 UTC, twschiller requested changes
Getting some errors when running the extension on pages. Looks like one of these is related to the path changing for the css files?:

Denying load of chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/icons.css. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

In general, a good way to test big changes is by just running through the https://docs.pixiebrix.com/quick-start-guide quickly

2021-06-03 20:12 UTC, twschiller commented on browsers/webpack/webpack.base.js
> -        parser: { amd: false },
@fregante What was the reason for removing this? I had originally added this since having lodash overwrite window._ breaks sites running older versions of lodash

2021-06-03 20:12 UTC, twschiller commented on scripts/webpack.scripts.js
> +      chokidar: false,
Could you clarify what you mean by "and find web-only entry points for each" means? Not familiar with it

2021-06-03 20:29 UTC, fregante commented on scripts/webpack.scripts.js
> +      chokidar: false,
https://github.com/mozilla/nunjucks/blob/fd500902d7c88672470c87170796de52fc0f791a/nunjucks/src/node-loaders.js#L34-L38

The filename and option suggest that this file, which is required and bundled into PixieBrix, is actually meant to be run on Node. Some packages offer browser-only packages without all of this cruft so that's what I'll look for.

Sub-dependencies like this were resolvable at some point because some other package downloaded them, but I suppose that these changes resurfaced this (unnecessary) dependency mismatch.

2021-06-03 20:29 UTC, fregante commented on browsers/webpack/webpack.base.js
> -        parser: { amd: false },
Sorry I blindly removed this line since it was deprecated:

```
Module not found: ValidationError: Invalid parser object. Json Modules Plugin has been initialized using a parser object that does not match the API schema.
 - parser has an unknown property 'amd'. These properties are valid:
   object { parse? }
```

I pushed a tentative solution for this. It compiles but I haven't run it.

2021-06-04 02:26 UTC, twschiller commented on scripts/webpack.scripts.js
> +      chokidar: false,
I think I understand now -- e.g., you'd find an entry point to nunjucks that doesn't reference the node-loaders module. That would prevent webpack from looking for chokidar in the first place, so we wouldn't have to explicitly tell webpack not to resolve it. Is my understanding correct?

For the sake of expediency, I'd also be ok marking things as `false` to get the build to pass after we do a quick check like you did to make sure they're not going to cause a problem

2021-06-04 02:29 UTC, twschiller commented on browsers/webpack/webpack.base.js
> -        parser: { amd: false },
Thanks, I can help show you how to test it. I think you just find a page where the PixieBrix contentScript is loaded and see if it set `window._` or not.

To do that, you could just click the PixieBrix extension icon in the Chrome toolbar on any page to trigger the browser action, which will inject the contentScript and the side bar

2021-06-04 02:41 UTC, fregante commented on scripts/webpack.scripts.js
> +      chokidar: false,
That’s correct. The current code already builds and should match more or less what existed before, so dependency-wise it shouldn’t need further changes in this PR (I’d rather merge the upgrade first, and only then do optimizations). 

I’ll run the extension today and see what’s missing.

2021-06-04 02:44 UTC, fregante commented
Something that confused me are the CSS files actually. It appears that most CSS files appear both at the entry point and inside the CSS folder. 

Also there’s a CopyPlugin configuration in the prod files that copied everything from src, unchanged. What was the reason for that?

2021-06-04 03:24 UTC, twschiller commented
> Also there’s a CopyPlugin configuration in the prod files that copied everything from src, unchanged. What was the reason for that?

From `browsers/chrome/webpack/webpack.dev.js`:
```
{
   from: path.resolve(chromeRoot, "src"),
},
{
   from: path.resolve(chromeRoot, "..", "src"),
},
```

The first one ends up copying over the `browsers/chrome/background.html` file which differs by browser because the Firefox distribution have the gapi script tag

The second one copies over `browsers/src` files which has the html files and also the CSS for those files, which for whatever historic reasons I wrote directly in there vs. referencing it from an entry point so that webpack would build it. So short answer: no great reason for the CSS files

2021-06-04 11:27 UTC, fregante commented on browsers/webpack/webpack.base.js
> -        parser: { amd: false },
1. I clicked the button
2. The sidebar appeared on the page
3. `window._` is undefined in the `top` frame in the console
3. `window._` is undefined in content script extension in the console

I also verified that **without `amd: false`**, `window._` is a function in both context, so it fixes this issue.

However I think that this is breaking `notify.js`, so I will probably just drop the UMD from its bundle and adjust it to work correctly. The file is dated 2015 anyway.

2021-06-04 19:38 UTC, fregante commented
Everything seems to be fine now. I don't see any errors other than https://github.com/pixiebrix/pixiebrix-extension/issues/428, which also appears on `main`

2021-06-05 19:22 UTC, twschiller commented
Testing now

> However I did not encounter the HMR issue described in #113. Was that at build time or runtime?

Will see if it's actually an issue. On package install, I get a peer dependency warning:

npm WARN webpack-extension-reloader@1.1.4 requires a peer of webpack@^4 but none is installed. You must install peer dependencies yourself.

2021-06-05 19:26 UTC, twschiller approved these changes

2021-06-05 19:26 UTC, merged

2021-06-06 03:31 UTC, fregante commented
Yeah that dependency was meant to be removed as discussed in https://github.com/pixiebrix/pixiebrix-extension/issues/113#issuecomment-853204206, but I left it in so I can properly document what will replace it.