Feature/4245 playground recovery
pixiebrix/pixiebrix-extension pull request #4249
Opened 2022-09-07 17:35 UTC by mnholtz

## What does this PR do?

- Closes #4245 
- Depends on https://github.com/pixiebrix/pixiebrix-app/pull/2250
- Instead of implementing an installation link for Playground blueprints (as described in the issue), this adds an `onUpdate` event listener on browser tabs that will install starter blueprints if the user visits/refreshes a Playground page.

## Reviewer Tips

- Take a look mainly at changes to `starterBlueprints.ts`. Lots of additional refactoring was done to support this feature. The tests in `starterBlueprint.test.ts` describe expected behavior for first-time installs.

## Discussion

- Is there any reason why adding an `onUpdate` event listener would not be ideal?

## Demo

https://user-images.githubusercontent.com/36575242/188942640-8ec3c902-2cd8-439f-be1e-c9c174c9402a.mov

## Future Work

- We decided that we'd like to modify the Webflow Playground pages to include a more helpful message if the Playground blueprint installation still fails.

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer @fregante

2022-09-07 18:42 UTC, BLoe approved these changes
The naming here is slightly hard to follow, but it's not too bad and it's all contained in this file, nothing is exported. You could possibly add some jsdoc comments on the functions to help explain the flow of things, and also to clarify what the boolean return values mean.

2022-09-07 18:42 UTC, BLoe commented on src/background/starterBlueprints.ts
> +    reportError(error);
What is going to be returned from this function when it catches an error? I think `void` will be coerced to `false`, but that's not really clear from looking at the code. Can we please return false here explicitly to make it more clear?

2022-09-07 19:00 UTC, fregante commented on src/background/starterBlueprints.ts
> +    reportError(error);
TypeScript in [loose mode](https://github.com/pixiebrix/pixiebrix-extension/issues/775) misses a lot of such warnings. It should have complained that the signature is `boolean` but there's no `return` here.

2022-09-08 06:41 UTC, fregante requested changes

2022-09-08 06:41 UTC, fregante commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
_I think my comment got lost:_

This listener will run `installStarterBlueprints` every time the playground is opened, for any number of open tabs, and every time a new page is visited within the playground. Given it contains some async getter/setters, this will certainly cause trouble (as well as unnecessary computation)

How about this pattern:

```js
async function initStarterBlueprints() {
	if (await isInstalled()) {
		return
	}

	if (await shouldInstall() || await onPlayGroundOpen()) {
		install()
	}
}

async function onPlayGroundOpen() {
	return new Promise(resolve => {
		const listener = (id, info, tab) => {
			if (tab?.url?.startsWith(PLAYGROUND_URL)) {
				browser.tabs.onUpdated.removeListener(listener)
				resolve(true) 
			}
		}

		browser.tabs.onUpdated.addListener(listener) 
	})
}

```

To note:

- initStarterBlueprints is only run once and may be "pending" forever, or until the user opens the playground

2022-09-08 14:34 UTC, BLoe commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
The function will run, but I think the check on line 54 prevents any blueprint from being installed twice, right? What kind of trouble are you imagining this will cause? Can you explain how your code example here avoids that trouble?

2022-09-08 15:00 UTC, fregante commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
`browser.tabs.onUpdated` fires a lot of times with all kinds of updates, even favicon updates, status updates, url updates.

1. `installStarterBlueprints` is called the first time
2. It starts an API call via `getStarterBlueprints`
3. `installStarterBlueprints` is called a second time while the API call is still in progress
4. It starts another API call

At this point line 54 hasn't been reached yet, so any logic there is futile.

My example avoids the trouble because it does call `installStarterBlueprints` every time the event happens; the listener is only used **once** to resolve a promise, and then the listener is removed.

2022-09-08 15:03 UTC, fregante commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
> What kind of trouble are you imagining this will cause? 

Some possibilities:

- each client reporting the same error multiple times on line 112
- each client making multiple unnecessary calls to the server, further slowing the server down
- `loadOptions` being called twice simultaneously, and then `saveOptions` overriding each other (race condition, almost exactly what was described in https://github.com/pixiebrix/pixiebrix-extension/issues/4073)

2022-09-08 16:03 UTC, mnholtz commented on src/background/starterBlueprints.ts
> +    reportError(error);
Thanks for catching this Ben! This was indeed a mistake.

2022-09-08 17:29 UTC, mnholtz commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
@fregante I'm not sure the pattern you suggested fits the needs of the feature, unless I'm misunderstanding your pseudocode. `initStarterBlueprints` will run only once per extension launch. Therefore, the conditional `if (await shouldInstall() || await onPlayGroundOpen()) {` will also be run only once. Subsequent visits to the Playground page after uninstalling Playground blueprints will not work. I'm actually not sure why the event listener is being re-added in the pseudocode if the conditional is run only once anyways.

We need users to always have Starter Blueprints installed for them when visiting the Playground page. In this case, I think I might go with a locking pattern in order to solve the concerns you outlined above.

2022-09-08 17:50 UTC, fregante commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
> initStarterBlueprints will run only once per extension launch

That's right. 

> We need users to always have Starter Blueprints installed for them when visiting the Playground page

I didn't think about that, although it would only be hit if they visit the playground, delete the blueprint, and then visit the playground again — all while never quitting the browser.

I guess it's fine to debounce it though, that would work.

2022-09-08 18:09 UTC, BLoe commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
Thanks for the discussion Federico! Yeah, debounce sounds good to me also.

2022-09-08 18:53 UTC, mnholtz commented on src/background/starterBlueprints.ts
> +      void installStarterBlueprints();
Yeah thanks federico! Great considerations here

2022-09-08 18:59 UTC, fregante approved these changes
![filipino-traditional-fisherman-boats-philippines-135762770](https://user-images.githubusercontent.com/1402241/189203980-21ff8bfb-9973-4cbb-8fee-cc63fb66e8fc.jpg)

2022-09-08 18:59 UTC, fregante commented on src/background/starterBlueprints.ts
> +async function installBlueprints(
To ensure that it's not called _undebounced_ (as it currently is on line 150), we can prepend `_` to the name. I generally inline the function in the `debounce()` call but for long once it's less readable.

```suggestion
async function _installBlueprints(
```

2022-09-08 18:59 UTC, fregante commented on src/background/starterBlueprints.ts
> +  const installed = await installStarterBlueprints();
While unlikely, it _could_ be called next while `browser.tabs.onUpdated` also fires. It doesn't hurt to use the debounced version everywhere to avoid these _leaks_

2022-09-08 23:36 UTC, merged