Avoid reporting bare Network Errors to Rollbar
pixiebrix/pixiebrix-extension pull request #4253
Opened 2022-09-08 19:51 UTC by fregante

## What does this PR do?

- Stops reports of `Network Error` to Rollbar

## Discussion

- The browser does not add further information to these errors, they most likely are a consequence of user error (e.g. due to a flaky connection, wifi captive portal, wrong address, …)
- The aggregation of these errors however could lead to the discovery of new bugs when spikes occur — I'm not sure they'd be useful in that case either though
- Opened on notification by @johnnymetz regarding the high amount of bug reports on Rollbar

## Checklist

- 😣 Add tests
- [x] Designate a primary reviewer: @johnnymetz

2022-09-08 19:57 UTC, johnnymetz approved these changes
Nice, this is one of the higher frequency rollbar items: https://rollbar.com/pixiebrix/pixiebrix/items/2546/

2022-09-08 20:36 UTC, BLoe requested changes
Sorry to block here, but I just want to make sure we review this change from a product standpoint and double check that the trade off is worth it.

2022-09-08 20:44 UTC, fregante commented
Sure. Merge only when confirmed. Either way it can be easily reverted.

2022-09-09 17:37 UTC, BLoe approved these changes
Good to go here for now 👍

2022-09-09 17:37 UTC, merged