#4280: monkeypatch JQuery calls to QSA use non-native :has
pixiebrix/pixiebrix-extension pull request #4281
Opened 2022-09-13 23:15 UTC by twschiller

## What does this PR do?

- Closes #4280 
- Monkey patches QSA calls from JQuery to avoid regression in Chrome 105

## Checklist

- [ ] Add tests: no way to automatically test 😢 
- [ ] Designate a primary reviewer: @fregante

2022-09-13 23:23 UTC, BLoe approved these changes
Assuming this passes QA and functions correctly, the code looks good to me 👍 

To be clear, I'm not really sure how `Object.assign` works with functions like that, so definitely should have Federico take a look also 😅

2022-09-14 02:58 UTC, fregante requested changes
The CS side looks about right, but I don’t know about the page script. 

It’s unfortunate to see that Chrome launched this without double checking a library used by half the internet 🥲

2022-09-14 02:58 UTC, fregante commented on src/pageScript/pageScript.ts
> +import "@/utils/jqueryHack";
Page script is injected in the website context, so this will presumably break any new website using the new selector.  I don’t think we need to fix this, assuming we don’t run the user’s selectors in this file.

2022-09-14 03:02 UTC, fregante commented on src/utils/jqueryHack.ts
> +const originalFind = $.find;
In these cases I’d probably just use a .js file

2022-09-14 03:03 UTC, fregante commented
> To be clear, I'm not really sure how Object.assign works with functions like that

`$.find` is a function with additional properties, like:

```js
function find() {}
find.yo = 123
```
Object.assign copies those properties onto a new function.

2022-09-14 03:14 UTC, fregante commented on src/contentScript/contentScript.ts
> +import "@/utils/jqueryHack";
I'd probably move this to the core  bundle so we don't wrap it two times. We should limit the amount of imports/logic in this file to near zero.

2022-09-14 09:51 UTC, twschiller commented on src/pageScript/pageScript.ts
> +import "@/utils/jqueryHack";
> will presumably break any new website using the new selector

What is the sequence where you think it would break the user's site? Our page script includes its own copy of JQuery, so we're not modifying the site's JQuery

And the patched version of `$.find` runs synchronously, so any calls to `document.querySelectorAll` be the page would be using the unpatched QSA

2022-09-14 10:12 UTC, fregante approved these changes

2022-09-14 10:12 UTC, fregante commented on src/pageScript/pageScript.ts
> +import "@/utils/jqueryHack";
> Our page script includes its own copy of JQuery

> so any calls to `document.querySelectorAll` be the page would be using the unpatched QSA

👍 I didn't see that it was immediately resetting them this morning. Looks safe then, but are we running the user jQuery selectors here? Where?

2022-09-14 11:07 UTC, twschiller commented
> but are we running the user jQuery selectors here

See uses of requireSingleElement in the pageScript file. The most frequent place it's still called from is GET_COMPONENT_INFO from the contentScript when selecting an element in the Page Editor to generate a selector

2022-09-14 11:07 UTC, merged