#4082: Implement multi-element selection popover
pixiebrix/pixiebrix-extension pull request #4282
Opened 2022-09-14 02:34 UTC by jcforest

## What does this PR do?

- Part of  #4082 

## Reviewer Tips

- Implemented 1 - 4.b in this [notion](https://www.notion.so/pixiebrix/Multi-element-Selector-Inference-15c6836a77d948f686398eef9e1b2e6e#d56295151721421cb615a7d7d8c166e3)

## Discussion

- Have some issues with styling of SwitchButtonWidget in React shadow root
- I introduced safeMultiCssSelector method for selecting selector for multi-elements rather than update the original safeCssSelector in order to reduce the code/test changes.
- 

## Demo
![Screen Shot 2022-09-14 at 10 33 06 AM](https://user-images.githubusercontent.com/10625864/190045505-8b6d7b52-6d88-4d19-bb65-16de1ddd0b3c.png)

## Future Work

- Still need to work on the automatic multi-element selector logic

## Team Coordination

_Leave all that are relevant and check off as completed_

## Checklist

- [ ] Designate a primary reviewer @twschiller @BLoe @fregante

2022-09-14 03:30 UTC, fregante commented on src/contentScript/nativeEditor/selectorInference.ts
> +export function safeMultiCssSelector(
This function looks like a copy-paste with minor modifications. I haven't checked yet, but would it make sense to alter the original function instead? Otherwise we have identical logic in two parts. 

Ignore if the intent is to migrate all usage to this function in the near future.

2022-09-14 03:30 UTC, fregante commented on src/components/SelectionToolPopover.tsx
> +    <ReactShadowRoot mode="open">
Can this be closed? I don't remember if it makes a difference in style conflicts but I don’t think we ever need open roots

2022-09-14 03:30 UTC, fregante commented on src/components/SelectionToolPopover.stories.tsx
> + */
So much copy right 😜

2022-09-14 03:30 UTC, fregante commented on src/components/SelectionToolPopover.module.scss
> +  height: fit-content;
Aren't both of these already the default with position:fixed?

2022-09-14 11:40 UTC, fregante commented
I noticed your branch is 10 days behind. You might want to ensure you update it locally before starting to work in order to avoid issues. A merge commit is fine now though, no rebase  👌

2022-09-14 18:50 UTC, BLoe reviewed
Looks pretty good so far, just had some comments and suggestions. I'm curious about the TODO part and what's left to be done on this PR vs. a followup PR?

2022-09-14 18:50 UTC, BLoe commented on src/pageEditor/fields/SelectorSelectorWidget.tsx
> +  >((x) => x.settings.selectionTools);
I think TS can infer the type here, no?

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/types.ts
> +export type SelectMode = "element" | "container" | "multi-elements";
Sorry to be picky here, but can we call this new one `multi-element` without the "s"?

2022-09-14 18:50 UTC, BLoe commented on src/components/SelectionToolPopover.tsx
> +              </FormLabel>
If you want, you could use `FieldTemplate` here. See [FieldEditor](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/components/formBuilder/edit/FieldEditor.tsx#L301-L307) for an example of how to use it with `SwitchButtonWidget`. Our custom widgets like this one are mostly intended to be used with `FieldTemplate` or `ConnectedFieldTemplate`.

If what you have here is working, then this isn't 100% necessary though. Up to you.

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/elementPicker.ts
> +            : uniq([...targets]);
```suggestion
          const result = uniq(compact([...targets, target]))
```
I think this would work also if you want to simplify the ternary operator.

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/elementPicker.ts
> +              "One or more selected elements are not contained with the root container"
```suggestion
              "One or more selected elements are not contained within the root container"
```

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/elementPicker.ts
> +        console.debug("////", value);
```suggestion
```
debug code

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/elementPicker.ts
> +        // Do not allow select the multi-element selection popup.
```suggestion
        // Do not allow the user to select the multi-element selection popup.
```

2022-09-14 18:50 UTC, BLoe commented on src/contentScript/nativeEditor/elementPicker.ts
> +          tagName: elements[0].tagName, // Will first element tag will be enough/same for all elemtns?
```suggestion
          tagName: elements[0].tagName, // Will first element tag be enough/same for all elements?
```

2022-09-14 18:51 UTC, fregante commented on src/components/SelectionToolPopover.tsx
> +      <Stylesheets href={[bootstrap, switchStyle, custom]}>
The stylesheets are loaded as URLs, not as CSS modules, so they need to be injected via `link` tag. 

Stylesheets loaded this way aren’t applied synchronously, so a plain link tag would let the content appear unstyled for a moment (FOUC). 

I suppose we could import the stylesheet as string and inject it via a (supposedly-)synchronous `style` tag, but that means we have to figure out how to unbundle the CSS anyway (or else large sheets will further fatten our JS bundles)

The Stylesheet component ensures that there’s no flash of unstyled content and that the sheets are loaded consistently and correctly (we did it in a few different ways before)

2022-09-14 18:52 UTC, fregante commented on src/components/SelectionToolPopover.tsx
> +      <Stylesheets href={[bootstrap, switchStyle, custom]}>
For this specific component I suppose that some style can be turned into a CSS module, but not Bootstrap's style.

2022-09-14 19:18 UTC, jcforest commented on src/contentScript/nativeEditor/selectorInference.ts
> +export function safeMultiCssSelector(
yes, they're almost same except the param accepts the multiple elements. for now i'm introducing new function and eventually will migrate into one and update the test suite as well

2022-09-14 19:19 UTC, BLoe commented on src/contentScript/nativeEditor/selectorInference.ts
> +export function safeMultiCssSelector(
This also makes it harder to review the diff on the PR

2022-09-14 19:20 UTC, jcforest commented on src/components/SelectionToolPopover.tsx
> +    <ReactShadowRoot mode="open">
I think it has no differences between open and close in this PR.

2022-09-14 19:22 UTC, jcforest commented on src/components/SelectionToolPopover.module.scss
> +  height: fit-content;
nice catch

2022-09-14 19:22 UTC, jcforest commented on src/components/SelectionToolPopover.stories.tsx
> + */
nice catch

2022-09-14 19:23 UTC, jcforest commented on src/components/SelectionToolPopover.module.scss
> +}
👍

2022-09-14 19:23 UTC, BLoe commented
>I introduced safeMultiCssSelector method for selecting selector for multi-elements rather than update the original safeCssSelector in order to reduce the code/test changes.

@jcforest I don't think I agree that this tradeoff is worth it. I'd rather we modify the copied function to handle multi-selector mode, or extract the common logic into another function. I don't think this reduces the test changes required, because you would need to write new tests for your separate function anyways if you really wanted to keep the test coverage at the same %, right?

2022-09-14 19:32 UTC, jcforest commented on src/components/SelectionToolPopover.tsx
> +      <Stylesheets href={[bootstrap, switchStyle, custom]}>
@BLoe I tried that but it didn't work inside react shadow.

2022-09-14 19:34 UTC, jcforest commented on src/pageEditor/fields/SelectorSelectorWidget.tsx
> +  >((x) => x.settings.selectionTools);
I'm not sure actually. i follow the same pattern for `excludeRandomClasses`

2022-09-14 19:35 UTC, jcforest commented on src/contentScript/nativeEditor/types.ts
> +export type SelectMode = "element" | "container" | "multi-elements";
sure

2022-09-14 19:57 UTC, BLoe commented on src/components/SelectionToolPopover.tsx
> +      <Stylesheets href={[bootstrap, switchStyle, custom]}>
Ah interesting, okay 🤷

2022-09-14 19:59 UTC, BLoe commented
> @jcforest I don't think I agree that this tradeoff is worth it. I'd rather we modify the copied function to handle multi-selector mode, or extract the common logic into another function. I don't think your implementation reduces the test changes required, because you would need to write new tests for your separate function anyways if you really wanted to keep the test coverage at the same %, right?

Ah, sorry, I see that you commented just before I posted this. If you are definitely going to merge the functions and update tests in a future PR, then I suppose this is alright for right now.

2022-09-14 20:03 UTC, jcforest commented on src/components/SelectionToolPopover.tsx
> +              </FormLabel>
ok. we can use that

2022-09-14 20:13 UTC, BLoe commented on src/pageEditor/fields/SelectorSelectorWidget.tsx
> +  >((x) => x.settings.selectionTools);
Ah, sorry, I missed one thing you need. There's a pattern we follow elsewhere that can simplify this. Take a look at [`ExtensionsRootState`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/store/extensionsTypes.ts#L29). If you create a new type called `SettingsRootState` in the settings type file, following the same pattern, then you can write your selector as:

```
const excludeRandomClasses = useSelector(({ settings }: SettingsRootState) => settings.excludeRandomClasses);
```

If you do this, then please also modify [`RootState`](https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/pageEditor/pageEditorTypes.ts#L181) to use the new root state type instead of the explicit `settings` field in the `&` part of that type. I can show you what I mean if this doesn't make sense.

2022-09-14 20:14 UTC, BLoe commented on src/pageEditor/fields/SelectorSelectorWidget.tsx
> +  >((x) => x.settings.selectionTools);
If you don't want to do this in this PR it's not a big deal, we can make this change in a follow up PR as well.

2022-09-16 18:45 UTC, jcforest commented
@twschiller @BLoe @fregante 
I implemented all features for multi-element selection except one unresolved issue. 
It's SwitchButtonWidget style issue. Any ideas how to fix that? 
![Screenshot at Sep 17 02-44-44](https://user-images.githubusercontent.com/10625864/190709779-8bb56779-2580-453a-8775-75da10b9a39b.png)

BTW, please review my PR again.

2022-09-20 01:50 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.module.scss
> +.popover-wrapper {
👍

2022-09-20 01:50 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.stories.tsx
> +export default {
👍

2022-09-20 01:52 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.stories.tsx
> +export default {
Looks like the style is not being injected into the story? If that's hard to do, please leave a code comment on why the story is unstyle

![image](https://user-images.githubusercontent.com/1879821/191149791-204f4e58-ba2b-4a84-a62d-5733e88021f4.png)

2022-09-20 01:52 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.tsx
> +  useEffect(() => {
👍

2022-09-20 01:53 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.tsx
> +              title={`Selection Tool: ${matchingCount} matching Elements`}
* Lowercase "Elements"
* Use the `pluralize` helper

2022-09-20 01:54 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.tsx
> +                <FormLabel className="align-middle mx-3">
The vertical alignment of the label is off: 
![image](https://user-images.githubusercontent.com/1879821/191150135-f2323e15-2ca0-4fc7-b3a1-9b9ce55c7dcb.png)

2022-09-20 01:55 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.tsx
> +        <Draggable>
👍

2022-09-20 01:55 UTC, twschiller commented on src/components/selectionToolPopover/SelectionToolPopover.tsx
> +  const [enabled, setEnabled] = useState(false);
Clarify the variable name, e.g., multiEnabled

2022-09-20 01:56 UTC, twschiller commented on src/contentScript/nativeEditor/insertButton.tsx
> -    selected = await userSelectElement({
👍

2022-09-20 01:57 UTC, twschiller commented on src/contentScript/nativeEditor/types.ts
> +  isMulti?: boolean;
👍

2022-09-20 01:57 UTC, twschiller commented on src/options/pages/settings/ExperimentalSettings.tsx
> +                Detect and Support Multi-element Selector :{" "}
No space before colon

2022-09-20 01:58 UTC, twschiller commented on src/options/pages/settings/ExperimentalSettings.tsx
> +                Toggle on to support multi-element selector.
Change to "Toggle on to support multi-element selection tool". Exclude the period at the end to match the text of the other entries

2022-09-20 02:03 UTC, twschiller commented on src/contentScript/nativeEditor/elementPicker.ts
> +          // TODO: Discuss if it's worth to include stableAncestors for multi-element selector
@jcforest Yes, we need to take into account stableAncestors where possible for multi-selection. What is the challenge of support the stable selector? There's two options

1. Find the common ancestor of the selected elements, and find a common stable ancestor
2. For each element, find the stable ancestor and consider in the generalization logic

2022-09-20 02:04 UTC, twschiller commented on src/contentScript/nativeEditor/elementPicker.ts
> +          tagName: elements[0].tagName, // Will first element tag be enough/same for all elemtns?
The tag might not be the same for all elements. However, for now it's fine to just use the first tag name. (It's just shown in the UI dropdown in the selector selector field)

2022-09-20 02:09 UTC, twschiller requested changes
See Loom on Slack: https://pixiebrix.slack.com/archives/D03ULB7RGNQ/p1663638575503029

- There’s no overlays on the selected elements
- The multi-element switch doesn’t seem to do anything (it doesn't disable multi-selection mode)

2022-09-20 12:37 UTC, twschiller commented
@jcforest Let me know when this is ready for re-review. Looks like the lint checks are failing

2022-09-20 19:57 UTC, twschiller approved these changes
![image](https://user-images.githubusercontent.com/1879821/191352636-a6618163-8f49-424e-8a89-82ffcc0f7fde.png)

2022-09-20 19:57 UTC, merged