#427: Don't include hash when generating the pattern
pixiebrix/pixiebrix-extension pull request #460
Opened 2021-06-09 11:58 UTC by fregante

Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/427

Changes:

- The generated pattern no longer includes the hash
- The patterns are validated and converted following WebExtensions’ logic rather than generic glob/pattern logic
- The code has been changed to convert and match all patterns at once since [webext-patterns](https://github.com/fregante/webext-patterns) can create a single regex from multiple patterns

What didn't change:

- The hash is still included in the pattern if the user manually specifies it.

If we preserve the current support for hash, we _might_ have issues, especially around `contentScript.register` (native vs polyfill). If we instead drop support, do we just silently ignore it?

For the record, I tried a pattern with a has in `content_scripts.matches` in both Chrome and Firefox in a test extension. Both detected the permission (i.e. it's "valid") but then they do never inject the content script (regardless of hash in the current tab)

2021-06-09 23:22 UTC, twschiller commented on src/blocks/available.ts
> +export function testMatchPatterns(url: string, ...patterns: string[]): boolean {
I don't think it makes sense to use the spread/varargs pattern on this method. 

All the call sites are passing through an array, so they get forced to use the spread operator too. Keeping it as an array argument is simpler

2021-06-09 23:28 UTC, twschiller commented on src/blocks/available.ts
> +    // Try them one at a time to find the broken one
👍

2021-06-09 23:32 UTC, twschiller requested changes
- [x] change from varargs in function signature to array argument

2021-06-10 17:43 UTC, fregante commented on src/blocks/available.ts
> +export function testMatchPatterns(url: string, ...patterns: string[]): boolean {
You're right! Now I'm not sure why I made the change.

> it gives flexibility to add additional optional positional arguments later

Given it's a private function, changing the signature _only when/if needed_ is not a problem, especially thanks to TypeScript.

2021-06-10 18:41 UTC, twschiller commented on src/blocks/available.ts
> +  url: string = document.location.href
I haven't tested this, but I don't think you can use `document.location.href` as the default value here because that will be the href at the time module is first loaded?. Instead I think the defaulting needs to happen in the body of the method so it evaluates to the href at the time of the check

2021-06-10 18:44 UTC, twschiller requested changes
See comment at https://github.com/pixiebrix/pixiebrix-extension/pull/460/files#diff-eac63ff5e6ec2c32c7e307dfd48630ef0f533898aebd2e2afdf9612ce2c52beaR29, I'm not sure the change is the correct behavior if there's a page navigation

2021-06-10 19:03 UTC, fregante commented on src/blocks/available.ts
> +    // Try them one at a time to find the broken one
By the way, if you think it's best, I'll just use a single loop instead of nesting try/catch

```js
    for (const pattern of patterns) {
      try {
        re = patternToRegex(pattern);
      } catch (ex) {
        throw new BusinessError(
          `Pattern not recognized as valid match pattern: ${pattern}`
        );
      }
    }
```

2021-06-10 19:09 UTC, merged