Prefer `await` to `.then()`
pixiebrix/pixiebrix-extension pull request #487
Opened 2021-06-12 20:29 UTC by fregante

More context about these PRs in #484 

---

Incomplete. This is requires changes that are a little more "substantial", especially when working around `runtime.onMessage`’s weird API. The solution to that is the `_runBlockAction` you see below, which splits the filter (`runBlockAction`) away from the actual handler

Context: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/652

It's easy to lose track of promises when using .then, especially when one would expect a promise to be awaited but instead it's lost in its own callback, including its errors.

2021-06-12 20:29 UTC, fregante commented on src/devTools/context.ts
> +  return value as TResult;
This is an example of how much more linear a then-less function can be

2021-06-13 13:50 UTC, twschiller commented
I agree we should be using `await` where it's cleaner. The only place we can't is locations between a user action (e.g., button click) and a browser permissions request. When using async/await, Firefox loses track of the fact the call stack is a result of a user action

2021-06-13 13:53 UTC, twschiller commented on src/devTools/context.ts
> +  return value as TResult;
That's a cool way of doing it! - haven't looked into common patterns with `Promise.race` much

2021-06-13 13:56 UTC, fregante commented
> The only place we can't is locations between a user action (e.g., button click) and a browser permissions request

Indeed I found those comments immensely useful. Once we put eslint on the CI I will exclude those cases from the rule.

> Let's discuss whether or not it makes sense to fix everything at once

I'm already at a good point for this specific PR. It's a relatively large change but files can be looked at one at a time. Unfortunately the diffs won't be super helpful, except maybe on split view, ignoring whitespace.

> prefer the boy scouts approach

I'm not sure how it applies here since the intent is to clean up the playground and discover tripping hazards along the way 😃

2021-06-13 15:19 UTC, fregante commented on src/devTools/context.ts
> +  return value as TResult;
No worries, I'm here for that! 

async/await really helps avoiding _promise-based callback hell_ and while scanning the code these days I found several code paths that went nowhere due to `.then` and `.catch`. I haven't changed these, but there's [an ESLint rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md) I'll suggest you run at some point to find these functions and ensure that they are voluntary (at that point you can mark them with `await` or `void`). This is something only you can do with certainty

2021-06-13 15:21 UTC, fregante commented
Don't look at this code yet, I will be testing and reviewing it in a bit.

2021-06-13 17:47 UTC, fregante reviewed
I reviewed the code carefully and tested the extension a bit. I fixed some bugs and reverted some changes that were slightly unrelated.

2021-06-13 17:47 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
Unless you're somehow running this function without giving access to the variables in this file, if `chrome` exists then `browser` also exists.

2021-06-13 17:47 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
Also can you clarify who calls `externalSendMessage`?

From what I gather, this is only ever called when all of these conditions are true:

- on Chrome
- on `externally_connectable` pages (i.e. app.pixiebrix.com)
- on code run in the unsafe context (the page itself, outside content scripts)

Does this extension inject this file into the "unsafe" world of `app.pixiebrix.com` and then communicates with itself?

2021-06-13 17:47 UTC, fregante commented on src/devtools.ts
> -  // const sidebar = await browser.devtools.panels.elements.createSidebarPane("Data Viewer");
This comment no longer seems to apply. `sidebar` is always an `object` and the rest of the function works. I tested this out as for some reason exactly this piece of code seemed not to work but I just had to open a brand new tab instead of refreshing the page and devtools.

I will look into the reliability/speed of the dev tools and content script injection+communication across contexts.

2021-06-13 17:47 UTC, fregante commented on src/pageScript/protocol.ts
> +  window.addEventListener("message", messageHandler);
This diff looks a bit "off" because I moved the handler from inline to the top level, to avoid unnecessary nesting and potentially duplicate listeners.

2021-06-13 17:47 UTC, fregante commented on src/contrib/uipath/localProcess.ts
> +      (async () => {
This is a little awkward, but it's the price to merge this callback with promised code. Using `async` below lets us unwrap the many .then and .catch calls within it.

2021-06-13 19:44 UTC, twschiller commented on src/blocks/combinators.ts
> +            await sendDeploymentAlert({
We don't want to await this, as the main thread shouldn't block on sending the alert

- [ ] Remove await and add comment clarifying expectation that the main thread doesn't block on call to sendDeploymentAlert

2021-06-13 19:52 UTC, twschiller commented on src/services/hooks.ts
> +      const result = await browser.permissions.request(permissions);
@fregante Here's a place we'll need to keep an eye on when this code is run on Firefox. I think using await here might make Firefox lose its information about whether or not the user initiated the current call chain

2021-06-13 20:03 UTC, twschiller commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
app.pixiebrix.com communicates with the extension via the methods lifted in `external.ts`:

https://github.com/pixiebrix/pixiebrix-extension/blob/00542fac4e664185d9b8f74eb5c720c557f2f837/src/messaging/external.ts#L52

So `function externalSendMessage` will get executed by app.pixiebrix.com's code. Chrome will make the `chrome` namespace to it because it's `externally_connectable`. The extension does not inject a contentScript into app.pixiebrix.com to communicate with itself

I can't remember if/how this would have been working on Firefox (i.e., if I had poly-filled the external messaging somehow)

2021-06-13 20:13 UTC, twschiller requested changes
Overall this looks good, there's just one spot in `combinator.ts` where I don't think we should introduce an await

There's also potentially a spot where I'm not sure if adding an `await` will break the Firefox user trusted event tracking in the permission request flow

Tried to provide historical context for your other questions/remarks

2021-06-14 04:34 UTC, fregante commented on src/devTools/context.ts
> +  return value as TResult;
By “voluntary” I meant “intentional” 😅

2021-06-14 05:32 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
I can't find how that happens. For this function to be called by the site, it would need to appear in `script.js`, right? But it doesn't:


<img width="491" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/121843480-7fa8c280-cd0c-11eb-85bb-3c4c711a0007.png">


external.ts and externalProtocol.ts are not inside script.js

<img width="681" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/121843464-77508780-cd0c-11eb-9508-811f1aca4b15.png">

2021-06-14 05:34 UTC, fregante commented on src/blocks/combinators.ts
> +            await sendDeploymentAlert({
I restored the previous code and added `void` to mark it as intentional as suggested by the rule https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md

2021-06-14 16:48 UTC, twschiller commented on src/blocks/combinators.ts
> +            void sendDeploymentAlert({
Interesting, TIL: https://stackoverflow.com/questions/55558875/void-before-promise-syntax

2021-06-14 16:53 UTC, twschiller commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
There's two scripts per frame:

- `contentScript.ts`: the content script. Runs in a separate JS context as the page
- `script.ts`: the "page script" (not a formal WebExtensions API concept). Injected by the content script and can pull information from the `window` or other JS context. The content script sends it messages (e.g., `detectFrameworks`)

The externalSendMessage is referenced from contentScript.ts via:

```js
import "@/contentScript/externalProtocol";
```

2021-06-14 16:53 UTC, twschiller approved these changes

2021-06-14 16:53 UTC, merged

2021-06-14 17:06 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
> Runs in a separate JS context as the page

Is this injected via script tag? Or do you mean it's a regular content script?

2021-06-14 17:14 UTC, twschiller commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
It's not a regular content script. Relevant code locations are (the code organization is really confusing, I had to follow some references to find it):

* https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/messaging/chrome.ts#L18: the messaging protocol / infrastructure between the contentScript and pageScript
* https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/lifecycle.ts#L44: where the script gets added to the page

2021-06-14 17:34 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
Script.js gets injected via script tag, but contentScript.js doesn’t, does it?

2021-06-14 17:58 UTC, twschiller commented on src/blocks/combinators.ts
> +            await sendDeploymentAlert({
I like the `void` syntax  also as a way to get the readability benefits of `.catch(reportError)` while having the unhandled promise rejection logic actually handle the errors

2021-06-14 18:00 UTC, twschiller commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
Correct, the content script injects `script.js` via a script tag. It has to be in order to get access to the page's JS context I believe

The contentScript is injected via the manifest and dynamic-content-scripts

2021-06-14 18:04 UTC, fregante commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
So externalSendMessage is never called. Content scripts have access to the regular sendMessage API, without extension ID. 

Only script.js and the regular app.pixiebrix.com code would have to use `chrome.runtime.sendMessage(id, message)`

2021-06-15 02:28 UTC, twschiller commented on src/background/protocol.ts
> +  return browser.runtime.sendMessage(extensionId, message, options);
`externalSendMessage` gets called by our web app, which is has the extension's codebase as a dependency

`script.js` doesn't have access to `chrome.runtime` because it's running in the JS context of the 3rd party webpage

Can clarify further on our call tomorrow