Clean `selectError`
pixiebrix/pixiebrix-extension pull request #489
Opened 2021-06-13 06:30 UTC by fregante

Replacing #488, I might add similar code changes here

Related:

I saw a few simple `reportError(error)` calls across the code, I wonder if they could all be dropped in lieu of just letting the `unhandledrejection` handlers catch it. I don't think that there's any advantage in catching an error that doesn't otherwise affect nearby code (e.g. it's not awaited at all). Example:

```js
setUninstallURL().catch((err) => {
  reportError(err);
});
```

2021-06-13 06:31 UTC, fregante commented on src/telemetry/logging.ts
> +  if (exc?.message && exc?.type === "unhandledrejection") {
The previous condition for this was equivalent to:
```suggestion
  if (!(exc instanceof Error) && exc?.type === "unhandledrejection") {
```

But I think that maybe this makes more sense as sets the message only if it doesn't already exist

2021-06-13 18:06 UTC, fregante commented on src/background/contextMenus.ts
> +    }).catch(reportError);
Promises always have a single value or error

2021-06-13 19:29 UTC, twschiller commented
> I saw a few simple `reportError(error)` calls across the code, I wonder if they could all be dropped in lieu of just letting the `unhandledrejection` handlers catch it. I don't think that there's any advantage in catching an error that doesn't otherwise affect nearby code (e.g. it's not awaited at all).

The historical context behind those calls is IntelliJ's built-in code analyzer complain about calling a method that returns a promise but ignores the result. So I added the `.catch` pattern in those cases

I agree there's no functional benefit to not just letting the top-level `unhandledrejection` handle it. 

The main benefit I see is making it obvious when reading the code that the method is being run asynchronously and won't be handled by any surrounding error handling

Thoughts?

2021-06-13 20:21 UTC, twschiller approved these changes

2021-06-13 20:24 UTC, twschiller commented on src/background/contextMenus.ts
> +    }).catch(reportError);
Can't remember why I was using unary here - think I had just read an article on the dangers of passing naked methods around as callbacks (to map, etc.)

2021-06-13 20:27 UTC, twschiller commented on src/telemetry/logging.ts
> +function selectError(exc: any): SerializedError {
We should avoid using `any` as the parameter type in signatures, as that breaks type-checking within the method. This should be `unknown` and then perform the necessary type checks/casts within the method

- [ ] Don't use "any" in method signature

2021-06-13 20:30 UTC, twschiller requested changes
Let's avoid using `any` in a method signature since it breaks Typescript checks within the method (it should be `unknown` instead)

As part of reviewing eslint rules, we'll want to include enabling rules about restricted Typescript types

2021-06-14 03:55 UTC, fregante commented on src/telemetry/logging.ts
> +function selectError(exc: any): SerializedError {
I used it here since `as any` is required in two places inside it due to duck typing. I'll use it there

2021-06-14 17:05 UTC, twschiller commented on src/telemetry/logging.ts
> +function selectError(exc: any): SerializedError {
My general principle is to try to limit the "blast radius" of type assertions. So moving the cast to `any` or the ts-ignore to the smallest part that's required (either the expression, or a single statement)

Having the `any` in the signature makes it easier for developers to introduce errors into the method in the future, because Typescript won't provide checking for new code

In this particular case, I don't think it's a big deal either way. I more wanted to use this an an opportunity to align on the general philosophy. As you can see from the existing code, I don't have a great way to clean up the body of the method 🤷

2021-06-15 14:30 UTC, twschiller approved these changes

2021-06-15 14:30 UTC, merged