#3059: Upgrade to RJSF5
pixiebrix/pixiebrix-extension pull request #4913
Opened 2022-12-30 07:03 UTC by fregante

## What does this PR do?

- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/3059

https://github.com/rjsf-team/react-jsonschema-form/blob/main/docs/5.x%20upgrade%20guide.md

## Reviewer Tips

- Migration details in https://github.com/rjsf-team/react-jsonschema-form/blob/main/docs/5.x%20upgrade%20guide.md

## Discussion

RJSF 5 is about be released as stable so I thought it'd make sense to start looking into upgrade to it as part of the CSP/MV3 ticket above.

## Future Work

- [ ] Attempt to replace ajv 6 with CloudFlare’s validator in our repo
- [ ] Potentially upstream it (could be a substantial amount of work)

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer

2022-12-30 09:18 UTC, fregante commented on package.json
> +    "@rjsf/validator-ajv6": "^5.0.0-beta.15",
I'm only updating rjsf here, not the validator. Let's ensure it works first and then move to CloudFlare’s validator, not ajv 8

2022-12-30 09:18 UTC, fregante commented on src/components/formBuilder/preview/FormPreviewBooleanField.tsx
> +const RjsfBooleanField = getDefaultRegistry().fields.BooleanField;
- [ ] Double check that this produces the output we expect

According to the upgrade guide, they reduced duplicated code so it's possible that these fields are shared now. Maybe the theme needs to be applied separately though

2023-01-04 15:38 UTC, fregante commented
So this seems to work already. Could you review the code changes, the snapshots and double-check that the document builder works as expected? I did see tests and saw zero issues

2023-01-23 13:35 UTC, twschiller commented
> This might be a good time to re-confirm that we're going to stay on RJSF 

We're staying on RJSF. I don't know of any greener pastures

Looks like they'll be releasing final 5.0 version this month (hopefully): https://github.com/rjsf-team/react-jsonschema-form/issues/3144

2023-01-23 13:59 UTC, twschiller commented
@fregante see here: https://github.com/pixiebrix/pixiebrix-extension/pull/4913#issuecomment-1400379452

I bumped to the latest beta. The story shot changes look fine to me. They just changed the id format for fields

2023-01-23 13:59 UTC, twschiller requested changes
See regressions

2023-11-14 11:17 UTC, fregante reviewed
Bear with me as I pick up this PR after 10 months 😇

2023-11-18 11:31 UTC, fregante reviewed
This PR is now ready for review, but it needs further work on something I wasn't able to figure out.

2023-11-18 11:31 UTC, fregante commented on src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
> +/*
I extracted this to https://github.com/pixiebrix/pixiebrix-extension/pull/6909 in order to make it pass in RJSF 4 first

2023-11-18 11:31 UTC, fregante commented on src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
> +          "ui:enableMarkdownInDescription": true,
Markdown support is still missing. I followed the docs and their tests, but I was unable to make it work.

From a summary check, the test is using our `FieldTemplate` but not `DescriptionField`. The description here is being added as part of `children`, bypassing the DescriptionField (where we even have our own MarkdownLazy parser)

https://github.com/pixiebrix/pixiebrix-extension/blob/960125a5a403ab234d6fb6b161e40d569970bccc/src/components/formBuilder/FieldTemplate.tsx#L52-L59

2023-11-18 11:31 UTC, fregante commented on src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
> -  (Theme as any).widgets.FileWidget = defaultFileWidget;
I think this TODO applies to a lot of parts of our RJSF usage. Let's merge this upgrade first and then work on any optimizations later.

2023-11-18 11:31 UTC, fregante commented on src/components/formBuilder/TextAreaWidget.test.tsx
> +    registry: {} as any,
These types have become quite onerous so I `any`'d it instead.

2023-11-18 11:31 UTC, fregante commented on src/components/formBuilder/preview/FormPreviewArrayField.tsx
> +import { getDefaultRegistry } from "@rjsf/core";
I think this was the solution I found at the time, but you might want to check if it results into what you expect.

2023-11-18 11:31 UTC, fregante commented on src/components/formBuilder/preview/SelectWidgetPreview.tsx
> +const RjsfSelectWidget = RjsfTheme.widgets.SelectWidget;
This file is new. Was it added in this PR to was it a bad merge?

2023-11-24 07:45 UTC, fregante commented on src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
> +          "ui:enableMarkdownInDescription": true,
This is the only failing test

2023-12-04 18:57 UTC, grahamlangford commented on src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
> +          "ui:enableMarkdownInDescription": true,
This is actually not the test that's failing. But I don't like the hacky way we're passing since it's not representative of the actual flow.

2023-12-04 22:00 UTC, grahamlangford approved these changes

2023-12-04 22:02 UTC, twschiller approved these changes

2023-12-04 22:13 UTC, fregante commented
# :shipit:

2023-12-04 23:28 UTC, merged