#5090: Update automation-anywhere/oauth2 integration definition
pixiebrix/pixiebrix-extension pull request #5092
Opened 2023-01-27 20:02 UTC by johnnymetz

## What does this PR do?

- Closes #5090 

## Future Work

- Copy / paste the definition into the [Workshop](chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/options.html#/workshop)

## Checklist

- [x] Designate a primary reviewer: @twschiller

2023-01-27 20:05 UTC, johnnymetz commented on contrib/services/automation-anywhere-oauth2.yaml
> +    authorizeUrl: "{{{ authConfigOrigin }}}/client/oauth/authorize?hosturl={{{ controlRoomUrl }}}&audience=https://controlroom"
@twschiller I added `default` values above so isn't the schema smart enough to substitute the default in here if the value is not defined? Or do I need to use [inverted sections](https://mustache.github.io/mustache.5.html#Inverted-Sections) as you mentioned before?

2023-01-27 21:10 UTC, twschiller requested changes

2023-01-27 21:10 UTC, twschiller commented on contrib/services/automation-anywhere-oauth2.yaml
> +    authorizeUrl: "{{{ authConfigOrigin }}}/client/oauth/authorize?hosturl={{{ controlRoomUrl }}}&audience=https://controlroom"
@johnnymetz you have to use inverted sections

In JSON Schemas, the `default` is a hint for the initial value in forms. The default isn't actually passed in as the value if one is not provided

2023-01-27 21:10 UTC, twschiller commented on contrib/services/automation-anywhere-oauth2.yaml
> +      description: "The AuthConfigApp origin"
Matching naming convention: https://docs.automationanywhere.com/bundle/enterprise-v2019/page/enterprise-cloud/topics/control-room/administration/settings/authconfig-app-enable-oauth2.html

2023-01-30 15:41 UTC, johnnymetz commented
Ready for another review

2023-01-30 16:54 UTC, johnnymetz commented on contrib/services/automation-anywhere-oauth2.yaml
> +  version: 4.0.0
I figured these changes warrant a major version bump. Let me know if you disagree

2023-01-30 18:06 UTC, twschiller commented on contrib/services/automation-anywhere-oauth2.yaml
> +  version: 4.0.0
Doesn't matter too much. Technically the changes are backward compatible, so would also be OK with a minor version bump

2023-01-30 18:08 UTC, twschiller commented on contrib/services/automation-anywhere-oauth2.yaml
> +    authorizeUrl: "{{#authConfigOrigin}}{{{.}}}{{/authConfigOrigin}}{{^authConfigOrigin}}https://oauthconfigapp.automationanywhere.digital{{/authConfigOrigin}}/client/oauth/authorize?hosturl={{{ cont
TIL about the `.`. Where did you find it? I still don't see it in the documentation

2023-01-30 18:09 UTC, twschiller commented on src/services/factory.test.ts
> +  test("custom client ID", () => {
❤️

2023-01-30 18:54 UTC, johnnymetz commented on contrib/services/automation-anywhere-oauth2.yaml
> +    authorizeUrl: "{{#authConfigOrigin}}{{{.}}}{{/authConfigOrigin}}{{^authConfigOrigin}}https://oauthconfigapp.automationanywhere.digital{{/authConfigOrigin}}/client/oauth/authorize?hosturl={{{ cont
https://stackoverflow.com/a/62030327/6611672

2023-01-30 18:56 UTC, johnnymetz commented on contrib/services/automation-anywhere-oauth2.yaml
> +  version: 4.0.0
Changed to a minor version bump

2023-01-30 19:02 UTC, merged

2023-01-30 19:32 UTC, johnnymetz commented on contrib/services/automation-anywhere-oauth2.yaml
> +    authorizeUrl: "{{#authConfigOrigin}}{{{.}}}{{/authConfigOrigin}}{{^authConfigOrigin}}https://oauthconfigapp.automationanywhere.digital{{/authConfigOrigin}}/client/oauth/authorize?hosturl={{{ cont
More context here: https://stackoverflow.com/questions/25320065/what-is-in-mustache