Inform user of failed sidebar injection
pixiebrix/pixiebrix-extension pull request #517
Opened 2021-06-16 12:54 UTC by fregante

A small change I thought about while clicking the action button on special pages without receiving any feedback. This is actually a recurrent issue with extensions that just fail on these pages.

<img width="372" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/122222468-7c643100-cedc-11eb-9ff6-629633b7cfb3.png">

Alternatively we can open the options page in this case, but I don't know if there are other situations where this error (especially in Firefox, since it's not as _exact_) might appear.

2021-06-16 13:39 UTC, twschiller commented on src/background/browserAction.ts
> +    switch ((err as any)?.message) {
Let's avoid the `any` + warning suppression here

Probably the simplest way is with a more-specific cast:
```
switch ((err as {message?: string })?.message) {
```

Also, I think `eslint-disable` disables the warning for the whole block? Let's use `eslint-disable-next-line` where possible to avoid suppressing the warning in other places

2021-06-16 13:45 UTC, twschiller requested changes
See comments on avoiding `any` and reporting the error on Firefox

2021-06-16 13:45 UTC, twschiller commented on src/background/browserAction.ts
> +        break;
Keep the reportError here, or fall through to default to get it?

2021-06-16 13:46 UTC, twschiller commented
I like the idea behind this PR a lot - have had confused users on this. (And also on the fact the dev tools panel doesn't show on restricted sites)

> I tried showing an icon there by adding a favicon but it doesn't appear

Is that code trying to add the icon to the window.alert?

2021-06-16 13:52 UTC, fregante commented
Yeah the dialog seems set up to show an icon, but instead it’s just empty space. I thought it was because the background page doesn’t have a favicon but that doesn’t show the icon either.

2021-06-16 14:14 UTC, fregante commented on src/background/browserAction.ts
> +    switch ((err as any)?.message) {
Since this is a common occurrence I will create/reuse some isError type guard that detects these objects.

2021-06-16 15:04 UTC, fregante commented on src/background/browserAction.ts
> +          // alert('PixieBrix might not work on this page. Try again?');
Since this is a common issue, especially so with MV3 blocking `alert` in Chrome as well, I was thinking about writing a generic module to create a slightly-customizable alert-like dialog, like `webext-alert`. Let me know if you're interested.

<img width="773" alt="Screen Shot 4 Redacted" src="https://user-images.githubusercontent.com/1402241/122244090-cbb35d00-ceee-11eb-9c2d-cb19e0c953f3.png">

2021-06-18 21:04 UTC, twschiller commented on src/background/browserAction.ts
> +          // alert('PixieBrix might not work on this page. Try again?');
A couple other approaches to consider:

## Use Notification API

We already ask for the notifications permission (so the user can create an action that issues one), so we could use that to show an error notification

## Change action style

Another Firefox compatible solution would be to change the style (badge/icon/tooltip) on the action button in to the toolbar. Some relevant APIs:

- https://developer.chrome.com/docs/extensions/reference/browserAction/#method-getBadgeBackgroundColor
- https://developer.chrome.com/docs/extensions/reference/browserAction/#method-setTitle

The main complication would be using setTimeout or a tab activate event to revert back to the "normal" style

Thoughts? If neither of the above look good, happy to use a quick and dirty `webext-alert` implementation. I haven't thought about how we'd want to style it in the future though.

2021-06-19 03:44 UTC, fregante commented on src/background/browserAction.ts
> +          // alert('PixieBrix might not work on this page. Try again?');
Notifications would be nice if the user couldn’t disable them. Unfortunately that means we can’t rely on them to display important messages. 

The action style won’t tell the user what’s wrong, it can just give a little feedback that there was an error without saying what it was. 

`webext-alert` would have minimal styles to look somewhat like an alert and have customizable message, OK button, and CSS. I’ll implement it locally for quicker iteration and extract it later.

2021-06-20 18:58 UTC, twschiller commented on src/background/browserAction.ts
> +          // alert('PixieBrix might not work on this page. Try again?');
> I’ll implement it locally for quicker iteration and extract it later.

Sounds good!

2021-06-21 16:23 UTC, fregante commented
I had [some issues](https://github.com/dasli/Chrome-Manifest-V3-Focus-Group-Sept-2020/issues/12#issuecomment-865010426) implementing that webext-alert, but it boils down to:

- HTML pages can't have inline scripts (for the Okay button to close the popup)
- `chrome.tabs.executeScript` can't inject scripts on `chrome://` pages

These 2 combined mean that we only have 2 solutions (that I can think of):

- local popup.html file + local popup.js file (which only contains `button.onclick = window.close`)
- barebones external HTML page that shows a message received via URL 👈 this is what I implemented, because it's the most straightforward and doesn't require changing the build in any way.

This is the external HTML page:

<details>
<summary>HTML</summary>

```html
<!-- https://github.com/fregante/webext-alert -->
<!DOCTYPE html>
<meta charset="utf-8">
<title>Message</title>
<link rel="stylesheet" href="https://www.unpkg.com/webext-base-css@1.3.1/webext-base.css">
<style>
	body {
		box-sizing: border-box;
		min-height: 100vh;
		margin: 0;
		padding: 1em;

		justify-content: center;
		display: flex;
		flex-direction: column;

		font-size: 14px;
		line-height: 1.5; font-family: system, system-ui, sans-serif;
	}
	div {
		flex-grow: 1;
	}
	button {
		margin-top: 1em;
		margin-left: auto;
	}
</style>

<body>
	<div></div>
	<script>
		try {
			const message = new URLSearchParams(location.search);
			document.querySelector('div').textContent = message.get('message');
			document.title = message.get('title') || document.title;

			// Fit window on Chrome only
			window.resizeBy(0, document.body.scrollHeight - window.innerHeight);
		} catch (error) {
			document.write('There was an error showing this message');
		}
	</script>
	<button onclick="window.close()">Okay</button>
</body>
```


</details>

Here's what it looks like, with some base style for automatic dark mode: https://github.com/fregante/webext-base-css

## Firefox

<img width="532" alt="Screen Shot 35" src="https://user-images.githubusercontent.com/1402241/122794096-144f8980-d2e6-11eb-91d6-93b5e04fb7ce.png">

## Chrome - Regular alert

<img width="532" alt="Screen Shot 34" src="https://user-images.githubusercontent.com/1402241/122794110-17e31080-d2e6-11eb-9658-2b8b9bddbc1e.png">

## Chrome - MV3

<img width="372" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/122794342-54167100-d2e6-11eb-8724-7362b9deabdb.png">

2021-06-22 07:32 UTC, fregante commented
We should keep in mind that this is a last-resort UI.

I also looked into system notification but the API still "works" even if the notification is never shown (e.g. if the user has disabled notifications for Chrome)

In this specific case we could alternatively just open a tab to the options. It won't be what the user expects but it wouldn't be an error message either.

2021-06-23 01:36 UTC, fregante commented on src/background/browserAction.ts
> +        reportError(error);
- Firefox does not catch injection errors so we don't get a specific error message: https://github.com/pixiebrix/pixiebrix-extension/issues/579#issuecomment-866451242
- I moved the reporting only to these _unknown_ cases


If desired:

- [ ] When injection fails, just open a tab with the options instead of showing an alert.

2021-06-23 01:39 UTC, fregante commented
PR ready. If desired:

- [ ] When injection fails, just open a tab with the options instead of showing an alert.

2021-06-23 13:12 UTC, twschiller commented on src/background/webextAlert.ts
> +  const url = new URL("https://webext-alert.vercel.app");
I don't want to reference outside URLs (expect potentially PixieBrix ones) from the extension

Can we just include the page locally in the browser bundle and use `runtime.getURL` to to get the URL for it?

2021-06-23 13:15 UTC, twschiller commented on src/background/browserAction.ts
> +        webextAlert("PixieBrix might not be compatible with this page");
"compatible" is misleading, especially if this is about Firefox blocking access to meta pages. Perhaps: "PixieBrix could not run on the page. Is this a special Firefox page?"

2021-06-23 13:17 UTC, twschiller commented
> the options instead of showing an alert.

One options is to open the options page with a URL parameter (e.g., `error=`) so that the UI can show the error message

Gave feedback here, but I would strongly prefer for the error page to be bundled with the extension:
- https://github.com/pixiebrix/pixiebrix-extension/pull/517#discussion_r657083482

2021-06-23 16:25 UTC, fregante commented on src/background/browserAction.ts
> +        webextAlert("PixieBrix might not be compatible with this page");
I dropped the question because it was being followed by an "Ok" button. Also this error is not currently specific to Firefox, it could happen for any failed injection. 

"The browser didn't allow it"? "PixieBrix wasn't able to open the sidebar"?

2021-06-23 16:28 UTC, fregante commented on src/background/webextAlert.ts
> +  const url = new URL("https://webext-alert.vercel.app");
I mentioned why this was not done: the HTML page needs its own script file and it seemed like adding 2 micro files to the build was a bit much. But maybe that's not so bad. 

Either way I like your idea to show the error in the option page, it's the best solution I think:

- no extra config/file
- local
- matches our style
- opens the options, which the user could find useful too

2021-06-24 13:23 UTC, fregante commented
- [x] Tested in Chrome and Firefox. They both use the options page to show the message, for consistency
- [x] Messages updated

Next:

- [ ] Style. Should it be a modal instead?

## Chrome

![Chrome](https://user-images.githubusercontent.com/1402241/123269696-692f1200-d529-11eb-9a35-b7fd98351aac.gif)

## Firefox

Firefox can't complete the installation, so the gif only shows that the correct page is being opened

![Firefox](https://user-images.githubusercontent.com/1402241/123269700-6a603f00-d529-11eb-9514-e0ee590ea8e7.gif)

2021-06-24 16:36 UTC, twschiller approved these changes
This is a move in the right direction. In the future we'll probably make the error message a modal on the options page instead of a banner to make it impossible to not notice

2021-06-24 16:37 UTC, merged