#3573 Add active blueprint to sidebar telemetry
pixiebrix/pixiebrix-extension pull request #6020
Opened 2023-07-05 22:13 UTC by turbochef

## What does this PR do?

- Fixes #3573
- Get blueprint from the active panel and send it through the telemetry events

## Checklist

- [ ] Add tests
- [ ] Designate a primary reviewer

2023-07-05 22:16 UTC, turbochef commented on src/sidebar/Tabs.tsx
> +      activeBlueprint: activePanel.blueprintId,
I wanted to use `selectEventData` to extract relevant data but I couldn't find a good way to get the actual extension even when I had the `extensionId`. Since the slice only asked for which mod was active I felt this met the requirements.

2023-07-06 14:45 UTC, grahamlangford commented on src/sidebar/Tabs.tsx
> +  }, [activeKey, panels, forms, temporaryPanels]);
This might be better served as a util function in `src/sidebar/utils.tsx`. Also, activePanel could be undefined here since you didn't account for staticPanels.

2023-07-06 16:59 UTC, turbochef commented on src/sidebar/Tabs.tsx
> +  }, [activeKey, panels, forms, temporaryPanels]);
> This might be better served as a util function in src/sidebar/utils.tsx
I'll play with the implementation

> This might be better served as a util function in src/sidebar/utils.tsx. Also, activePanel could be undefined here since you didn't account for staticPanels.
staticPanels are currently only used for the home tab so I didn't want to include it. ActivePanel can also be undefined if the user is building a new sidePanel mod that doesn't have a blueprint yet.

This did remind me to change `activePanel.blueprintId` to `activePanel?.blueprintId` though.

2023-07-06 17:00 UTC, mnholtz commented on src/sidebar/Tabs.tsx
> +    const activeUUID = activeKey.slice(-36);
Instead of slicing the active key, it might be more legible to just apply `eventKeyForEntry` while searching for the panel below. This feels a little error-prone to me.

2023-07-06 17:01 UTC, mnholtz commented on src/sidebar/Tabs.tsx
> +    const activeUUID = activeKey.slice(-36);
In other words, I'd just use activeKey and compare it to the result of `eventKeyForEntry` applied to the panel.

2023-07-06 17:05 UTC, mnholtz commented on src/sidebar/Tabs.tsx
> +  const activePanel = useMemo(() => {
Will this work as intended with `activePanel` placed outside of the `onSelect`? `onSelect` _sets_ the `activeKey`, which is used to re-render `activePanel`. I think the event will get reported with `activeKey` out-of-date?

2023-07-06 17:06 UTC, mnholtz requested changes
I'd like to confirm that the right activePanel is reported `onSelect`, see https://github.com/pixiebrix/pixiebrix-extension/pull/6020/files#r1254701389

To confirm it might be nice to have a unit test to confirm that `reportEvent` was called with the correct data, if possible.

2023-07-06 17:09 UTC, mnholtz commented on src/sidebar/Tabs.tsx
> +  const activePanel = useMemo(() => {
I'd expect to either
1. have the event being reported in a useEffect with `activePanel` as a dependency, or
2. have activePanel be calculated inside `onSelect` using the `eventKey` prop

2023-07-06 17:42 UTC, BLoe commented on src/sidebar/Tabs.tsx
> +  }, [activeKey, panels, forms, temporaryPanels]);
I actually think all of this should probably be in a selector and called with `useSelector`. Even if you still want to use the active tab key, you can just build a composite selector with reselect:

```
const selectActiveTabUUID = createSelector(
  selectSidebarActiveTabKey,
  (activeKey) => {
    ...
  }
);
```

2023-07-06 17:42 UTC, BLoe commented on src/sidebar/Tabs.tsx
> +      activeBlueprint: activePanel.blueprintId,
The sidebar store includes `extensionsSlice`, so you should just be able to use the `selectExtensions` selector with `useSelector()`.

2023-07-06 18:31 UTC, turbochef commented on src/sidebar/Tabs.tsx
> +  // Blueprint of the active panel for telemetry
I should've known that. Just did a ton of renaming. Thanks 👍

2023-07-06 18:51 UTC, grahamlangford commented on src/sidebar/Tabs.tsx
> +  const activePanel = useMemo(() => {
Good callout. I'm pretty sure you're right.

2023-07-06 19:23 UTC, mnholtz commented on src/sidebar/Tabs.tsx
> +      activeBlueprint: activePanel.blueprintId,
I agree with @BLoe, this is probably the way to go if you have time

2023-07-06 21:23 UTC, turbochef commented on src/sidebar/sidebarSelectors.ts
> +  };
@BLoe Is this roughly what you were thinking for that select function? It's kinda chunky because I need to cross-reference the sidebar entries with the extension options.

2023-07-06 21:24 UTC, turbochef commented on src/sidebar/Tabs.tsx
> +    const activeUUID = activeKey.slice(-36);
That makes sense. Thanks

2023-07-06 21:27 UTC, turbochef commented on src/sidebar/sidebarSelectors.ts
> +  };
Technically the lookup map is suboptimal because it gets created on every call but I don't it's a huge perf issue. I can swap over to find if y'all prefer.

2023-07-06 21:27 UTC, turbochef commented on src/sidebar/Tabs.tsx
> +  const activePanel = useMemo(() => {
You're right, I changed it.

2023-07-06 21:42 UTC, turbochef commented on src/sidebar/utils.tsx
>    }
Was already in the process of making some typeguards so I thought I'd apply them.

2023-07-07 13:45 UTC, grahamlangford commented on src/sidebar/sidebarSelectors.test.ts
> +      recipes: recipeStateFactory(),
Why is this needed?

2023-07-07 13:49 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +  panel: any
NIT: I would prefer to use `unknown` over any.

2023-07-07 13:49 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +export function isPanelEntry(panel: any): panel is PanelEntry {
NIT: `unknown` over `any`

2023-07-07 13:49 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +  panel: any
NIT: `unknown` over `any`

2023-07-07 13:49 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +  panel: any
NIT: `unknown` over `any`

2023-07-07 13:49 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +export function isStaticPanelEntry(panel: any): panel is StaticPanelEntry {
NIT: `unknown` over `any`

2023-07-07 14:50 UTC, twschiller commented on src/types/sidebarTypes.ts
> +export function isPanelEntry(panel: any): panel is PanelEntry {
I thought we had a lint rule to ban `any` in parameter lists

2023-07-07 14:51 UTC, twschiller commented on src/types/sidebarTypes.ts
> +export function isPanelEntry(panel: any): panel is PanelEntry {
Here's a lint rule we could use: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md

2023-07-07 15:14 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +  return (panel as BaseExtensionPanelEntry)?.extensionId != null;
This is actually why I wanted this to be typed `unknown`. We should be validating that it's actually an object.

```
if (isObject(panel)) {
    return "extensionId" in panel && panel.extensionId != null
}
return false
```

2023-07-07 15:36 UTC, turbochef commented on src/types/sidebarTypes.ts
> +export function isPanelEntry(panel: any): panel is PanelEntry {
makes sense. updated

2023-07-07 18:10 UTC, mnholtz commented on src/sidebar/sidebarSelectors.ts
> +      isBaseExtensionPanelEntry(sidebarEntry) && sidebarEntry;
Would this cause an error if `isBaseExtensionPanelEntry` ==> `false` because `extensionId` can't be destructured from a boolean?

2023-07-07 18:12 UTC, mnholtz commented on src/types/sidebarTypes.ts
> +  panel: unknown
nit: I think panel could be a union type of the possible panel types, instead of `unknown`

2023-07-07 18:16 UTC, mnholtz approved these changes
Question about possible NPE here: https://github.com/pixiebrix/pixiebrix-extension/pull/6020/files#r1256249853

Also see nit about type `unknown`.

Otherwise approving to unblock you because everything else looks good.

2023-07-07 18:44 UTC, grahamlangford commented on src/sidebar/sidebarSelectors.ts
> +      isBaseExtensionPanelEntry(sidebarEntry) && sidebarEntry;
`extensionId` would be undefined in that scenario, but there wouldn't be an error. (I had to double-check, javascript is weird sometimes)

2023-07-07 18:45 UTC, grahamlangford commented on src/types/sidebarTypes.ts
> +  panel: unknown
Then we'd only be able to pass it something that we _know_ is one of the panel types without TypeScript flagging it. Especially for this typeguard, I don't think that's the behavior we want?

2023-07-07 21:09 UTC, BLoe approved these changes

2023-07-07 22:05 UTC, turbochef commented on src/sidebar/sidebarSelectors.ts
> +      isBaseExtensionPanelEntry(sidebarEntry) && sidebarEntry;
I went ahead and short-circuited on the typeguard so it's a non-issue. It also saves us a potentially unnecessary find.

2023-07-07 22:05 UTC, merged