Use Promisified chrome.* fallback API for consistency
pixiebrix/pixiebrix-extension pull request #621
Opened 2021-06-26 11:02 UTC by fregante

Having written the usual `new Promise etc chrome.runtime.lastError etc` wrapper a thousand times, I published https://github.com/fregante/webext-polyfill-kinda to avoid ever writing that again _in a slightly different way every time._

This helper would be a companion to the regular `webextension-polyfill` since that package purposefully excludes some methods.

Advantages here:

- Just use promises, clearer code
- Always throw real errors and not strings (which was an issue)
- No inconsistencies

2021-06-26 14:35 UTC, fregante commented on src/background/protocol.ts
> -        reject(chrome.runtime.lastError);
It was rejecting with an error-like object

2021-06-26 14:35 UTC, fregante commented on src/blocks/readers/meta.ts
> -          reject(browser.runtime.lastError.message);
It was rejecting with a string

2021-06-26 14:35 UTC, fregante commented on src/options/pages/Settings.tsx
> +      browser.runtime.reload();
Side note: I haven't verified, but it seems a bit early to reload here:

- https://stackoverflow.com/a/15842031/288906
- https://developer.chrome.com/docs/extensions/reference/runtime/#method-requestUpdateCheck


> Requests an immediate update **_check_** be done for this app/extension.

2021-06-27 08:41 UTC, fregante commented on src/background/protocol.ts
> +  const sendMessage = chromeP.runtime.sendMessage;
`callBackground` is only called in Chrome browsers, so the `browser.*` API is still a polyfill, there's no advantage in using it over chromeP

2021-06-27 14:17 UTC, twschiller commented on src/background/protocol.ts
> +  const sendMessage = chromeP.runtime.sendMessage;
I don't think this is true -- callBackground is used for both internal communication with the background page and also the call from the external app.pixiebrix.com. See for example: http://github.com/pixiebrix/pixiebrix-extension/blob/24d6441d8f3bbf72b1d29638511a5eab14c1228c/src/background/navigation.ts#L33-L33

You are correct that callBackground is not used by app.pixiebrix.com in Firefox

I believe the reason why the new code code still works in Firefox is because Firefox exposes the "chrome." API namespace for compatibility reasons

I would have a slight preference for doing something like the following which makes clear the standardized API is only used in the extension context:

```
const sendMessage = isExtensionContext()
    ? browser.runtime.sendMessage
    : chromeP.runtime.sendMessage;
```

2021-06-27 14:24 UTC, twschiller commented on src/contrib/google/auth.ts
> +      return token;
I'm getting a type error here, are you seeing that too? 

![image](https://user-images.githubusercontent.com/1879821/123548195-c5648280-d731-11eb-826d-c0ae8aa0700d.png)

2021-06-27 14:28 UTC, twschiller commented on src/contrib/google/auth.ts
>  export async function resetToken(scopes: string[]): Promise<void> {
Let's remove the unused function for now. It's not complicated enough to keep around

2021-06-27 14:32 UTC, twschiller commented on src/options/pages/Settings.tsx
> +      browser.runtime.reload();
Let's leave as-is, this feature isn't used much (I think only once ever?). Even if this only causes Chrome to check for a new version, when the extension reloads I think it might show the http://github.com/pixiebrix/pixiebrix-extension/blob/24d6441d8f3bbf72b1d29638511a5eab14c1228c/src/options/pages/UpdateBanner.tsx#L26-L26

2021-06-27 14:33 UTC, twschiller requested changes
See comment at https://github.com/pixiebrix/pixiebrix-extension/pull/621/files#diff-a463f373bc5929f8adfc16eaacbb78cdebed7ed3b66a5c3395a72d0231d27519R141

2021-06-27 14:36 UTC, fregante commented on src/background/protocol.ts
> +  const sendMessage = chromeP.runtime.sendMessage;
Ah you're right, I thought this was inside an `external` file and therefore _only_ used to communicate with it.

Ternary restored

2021-06-27 14:41 UTC, fregante commented
> See comment at [#621 (files)](https://github.com/pixiebrix/pixiebrix-extension/pull/621/files#diff-a463f373bc5929f8adfc16eaacbb78cdebed7ed3b66a5c3395a72d0231d27519R141)

If you leave comments on the files, GitHub will let you "Request changes" without adding any further messages as well 👍

2021-06-27 14:42 UTC, fregante commented on src/contrib/google/auth.ts
> +      return token;
Try `npm install` again

I had to add some temporary types to my polyfill because of wrong types:

- https://github.com/fregante/webext-polyfill-kinda/commit/7273111e2164071179542f26fe90fa5bce577ead
- https://github.com/jsmnbom/definitelytyped-firefox-webext-browser/issues/41

For me:

<img width="514" alt="Screen Shot 30" src="https://user-images.githubusercontent.com/1402241/123548795-7c8fe680-d790-11eb-8bb2-d50f5235d3d1.png">

If the type was still wrong, CI would fail I think

2021-06-27 19:28 UTC, twschiller approved these changes

2021-06-27 19:28 UTC, merged