#580: Properly handle runtime connection errors
pixiebrix/pixiebrix-extension pull request #623
Opened 2021-06-26 14:28 UTC by fregante

While working on #621 I noticed that these errors are _probably_ not caught.

Next:

- [ ] Actually run the code

2021-06-26 14:30 UTC, fregante commented on src/chrome.ts
> +    setTimeout(resolve, 0, port);
The code hasn't been tested directly, it's based on this:

<img width="476" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/123516163-ef339000-d6c4-11eb-87d7-54656671316b.png">

- `sync lastError undefined` shows that the lastError that the previous code was looking for was not set in time
- ignore _16_
- `onDisconnect lastError {}` shows that it's available in there (the object actually expands into `{message: "Could not establish connection. Receiving end does not exist."}`)
- `Connected now…` shows that `onDisconnect` is called within the first possible timeout, i.e. almost immediately

2021-06-26 14:30 UTC, fregante commented on src/background/devtools/external.ts
> +      throw new Error(`Error sending devtools notification: ${error.message}`);
`postMessage` does not seem to set `lastError` at all, but it just throws with a proper error, as seen in:

<img width="433" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/123516319-ab8d5600-d6c5-11eb-8fbf-5f825f561f22.png">

2021-06-26 14:30 UTC, fregante commented on src/devTools/protocol.ts
> +    throw error;
It seems that `port` is always returned in order to attach the `onDisconnect` listener. Let me know if you found a way to not return it at all.

2021-06-27 15:00 UTC, fregante commented on src/background/devtools/external.ts
> +      throw new Error(`Error sending devtools notification: ${error.message}`);
I'm unable to test this part in PB because as soon as I refresh the extension or manually `disconnect()` the port in the background, a lot of error pop up in various parts of the extension, from `hasListeners` to `webext-detect-page`, never reading `postMessage` at all.

That actually brought me to reduce the chance of `webext-detect-page` throwing errors by adding caching in the next version: https://github.com/fregante/webext-detect-page/commit/1cc2e123c32b90fb849b2f922a3de5b456757d83

2021-06-28 00:10 UTC, twschiller commented on src/background/devtools/external.ts
>        devtoolsHandlers.set(nonce, [resolve, reject]);
Thant's correct

For the Firefox external messaging, I do the same thing (for both sides): http://github.com/pixiebrix/pixiebrix-extension/blob/463004f75562d12e826348f3a816b594b129ff36/src/contentScript/externalProtocol.ts#L40-L40. 

Not sure why, but for the external page I made separate maps for the fulfilled and rejected callbacks

2021-06-28 01:56 UTC, twschiller commented on src/chrome.ts
> +    setTimeout(resolve, 0, port);
This method doesn't work? https://developer.chrome.com/docs/extensions/reference/runtime#event-onConnect

If it only gets triggered from the other side of the port, you could immediately send back a greeting message, so the initiator knows the port is now working

2021-06-28 02:01 UTC, twschiller commented on src/devTools/protocol.ts
> +    throw error;
Not sure I follow 

If you look at usages of `connectDevtools` it's used in the React hook `useDevConnection`, which is currently used by the devtools React front-end. The port is passed to child components via React's Context: https://reactjs.org/docs/context.html feature

2021-06-28 12:34 UTC, twschiller requested changes
Use onConnect to make connection detection more reliable: https://github.com/pixiebrix/pixiebrix-extension/pull/623#discussion_r659416220

2021-07-01 08:18 UTC, fregante commented on src/devTools/protocol.ts
> +    throw error;
Sorry this comment was probably on the wrong line. I was referring to this piece of code that this PR is deleting:

```js
if (!port) {
	throw new Error("Could not get connection port to background page");
}
```

From what I can tell `chrome.runtime.connect()` _always_ returns `port`. I was asking you if you found a way that causes `connect()` to return undefined instead.

2021-07-01 13:12 UTC, twschiller commented on src/background/devtools/internal.ts
> +    port.postMessage("Port open");
I think this should be following our message structure of `{type: string, payload: string}` to simplify the kinds of messages our code expects to handle

Also, an additional comment on why the "ping back" is necessary would be helpful for future readers

2021-07-01 13:15 UTC, twschiller commented on src/chrome.ts
> +  const deferred = pDefer();
Chose a better name for this variable, e.g., `deferredConnectionPromise` so it's more clear what the use of the variable is. 

It's hard to follow that this promise is what actually gets waited on before the returned value

2021-07-01 13:16 UTC, twschiller commented on src/chrome.ts
> +/** Connect to the extension runtime and throw proper errors if it fails. NOTE: It expects a message from the other side */
Explain why it "expects a message from the other side". That is, it expects a message from the other side in order to determine that the port connection was successfully opened

2021-07-01 13:18 UTC, twschiller commented on src/chrome.ts
> +    await pTimeout(deferred.promise, 1000);
Add a comment explaining why a timeout is necessary here? Is it because onDisconnect doesn't get called if the other end doesn't respond?

2021-07-01 13:19 UTC, twschiller commented on src/devTools/protocol.ts
> +    throw error;
Not that I recall, I think I was just being safe/overcautious while trying to debug a port issue at some point. Feel free to remove

2021-07-01 13:21 UTC, twschiller approved these changes

2021-07-01 13:22 UTC, twschiller commented
@fregante This looks good. I added some suggestions on how to improve the readability of the code for people who come across it in the future. This stuff is hairy, so I'd like to err on the side of over explaining why certain things are there

Go ahead and merge when ready

2021-07-01 15:23 UTC, fregante commented on src/chrome.ts
> +    await pTimeout(deferred.promise, 1000);
Correct. It's only here to catch developer mistakes of not answering the message during `onConnect`. Assuming that the background page is always available, this should only happen within a milliseconds. Sometimes 1, sometimes 90.

2021-07-01 15:25 UTC, fregante commented on src/chrome.ts
> +  const deferred = pDefer();
Dropped the variable, I left the normal resolve/reject. 

Deferreds are to be read as "open promises" where the promise and resolve/reject callbacks exist in the same scope. I used this to allow removing the listeners in `finally`

2021-07-01 15:28 UTC, merged