#6651: Incremental strict null checks adoption: Slice 8
pixiebrix/pixiebrix-extension pull request #6683
Opened 2023-10-22 05:22 UTC by fregante

## What does this PR do?

- Closes #6651 

## Checklist

- [x] Designate a primary reviewer: @grahamlangford

2023-10-22 05:50 UTC, fregante commented on src/analysis/asyncAnalysisQueue.ts
> -        await task();
This should never actually be undefined because this function is only called when the array isn't empty.

`?.` just silences this incongruence while preserving safety.

2023-10-22 05:50 UTC, fregante commented on src/pageEditor/PanelContent.test.tsx
> -    navigationEvent.emit(thisTab.tabId);
The pageEditor is only connected to one tab, so there's no need to pass the tab ID

2023-10-22 05:50 UTC, fregante commented on src/hooks/events.ts
> -export class SimpleEvent<TValue> implements TabEvent<TValue> {
I dropped this duplicate event emitter because it has some null issues and because it's based on a wrong assumption. We already have `SimpleEventTarget`

2023-10-22 05:50 UTC, fregante commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +  onCreateNew = identity,
It appears that these two callback functions act as an input transformer. If they're missing, I assume that the intent is to pass the input unchanged. Please review if this is the intended behavior.

2023-10-22 05:50 UTC, fregante commented on src/pageEditor/tabs/editTab/editorNodes/brickNode/MoveBrickControl.tsx
> +          onClickMoveUp?.();
Adding `?.` is the only change here. `onClick` will never be called here because if it's missing, the button will be `disabled`

The large diff is because I replaced the `&&` with a clearer `empty ? null : JSX` to fix the function's return value.

2023-10-22 05:50 UTC, fregante commented on src/tsconfig.strictNullChecks.json
> -    "./telemetry/dnt.ts",
24 files added manually. Then I ran the `autoAdd` function and it sorted the list, adding a bunch more files 🎉

2023-10-22 05:50 UTC, fregante commented on src/utils/SimpleEventTarget.test.ts
> +});
New tests 🎉

2023-10-23 13:19 UTC, grahamlangford commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +  onCreateNew = identity,
@BLoe Can you take a look at this?

2023-10-23 13:22 UTC, grahamlangford commented on src/tsconfig.strictNullChecks.json
> -    "./telemetry/dnt.ts",
I've experienced weird flake with `autoAdd`, which caused it to add some new files while leaving off files we've added manually. Glad it worked this time. Just wanted to let you know in case you experience the same problem.

2023-10-23 15:41 UTC, BLoe commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +  onCreateNew = identity,
@fregante There is logic in this component that checks these props for `undefined`. If we're setting defaults here instead then we need to refactor more logic in the component to keep the behavior the same. For example, look at the check on line 141.

2023-10-23 15:44 UTC, BLoe commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +  onCreateNew = identity,
Furthermore, this `CreatableAutoSuggest` appears to only be used in one place, in `SelectorSelectorWidget`. I'm not sure if this was used in more places previously, but if we only need to support the one widget, then this whole thing can/should be simplified a TON, and probably all props made required.

2023-10-23 15:48 UTC, BLoe commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +        [styles.notClearable ?? ""]: !isClearable,
Does CSS-modules-with-`cx` conflict with strict null checks? This is a pretty severe degradation of the developer experience here if we need to null-coalesce every CSS module usage every time we use it with `classnames`...

2023-10-23 15:48 UTC, BLoe commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +        [styles.notClearable ?? ""]: !isClearable,
CC @grahamlangford

2023-10-23 15:49 UTC, BLoe commented on src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
> +          [styles.ancestorActive ?? ""]: isAncestorActive,
😢

2023-10-23 15:51 UTC, BLoe commented on src/pageEditor/tabs/editTab/editorNodes/brickNode/MoveBrickControl.tsx
> +          onClickMoveUp?.();
note - diff looks fine if you enable the "ignore whitespace" option

2023-10-23 16:06 UTC, grahamlangford commented on src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
> +        [styles.notClearable ?? ""]: !isClearable,
Also `!` would result in a class of `undefined` being added if it ever actually was undefined.

2023-10-23 16:25 UTC, BLoe requested changes
I think there are further changes needed related to the `CreatableAutoSuggest` widget, but otherwise LGTM

2023-10-23 17:49 UTC, twschiller commented on src/analysis/asyncAnalysisQueue.ts
> -        await task();
NIT: please add comment in the code explaining why it should be safe

2023-10-23 18:18 UTC, BLoe approved these changes
🎸

2023-10-23 18:50 UTC, grahamlangford approved these changes

2023-10-23 21:38 UTC, grahamlangford commented
@fregante, I was looking at the cycles (using the `npm run find-cycles` command from the tool), and I figured out if you add the following files, it unblocks a ton of files with no fixes needed.

```
    "./bricks/types.ts",
    "./types/integrationTypes.ts",
    "./types/loggerTypes.ts",
    "./types/registryTypes.ts",
    "./types/runtimeTypes.ts",
    "./bricks/errors.ts",
    "./errors/businessErrors.ts",
    "./errors/errorHelpers.ts"
```

Gets us from:
<img width="866" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/f8f8deb0-b78b-4d32-9f8c-64f8b56c4ef5">

To:
<img width="883" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/30706330/6140f48d-f904-44fb-9ba1-cc274e8be268">

2023-10-24 05:44 UTC, merged

2023-10-24 05:50 UTC, fregante commented
### This PR added 145 files! 

1307 files to go 😌

2023-10-24 05:55 UTC, fregante commented on src/analysis/asyncAnalysisQueue.ts
> -        await task();
Oops didn't see this comment. Will address in the next slice