fix the sidebar overlapping zendesk
pixiebrix/pixiebrix-extension pull request #7101
Opened 2023-12-11 20:47 UTC by grahamlangford

## What does this PR do?

- Resizes the `body` element when opening the sidebar to fix the sidebar overlapping Zendesk content

## Demo
https://www.loom.com/share/c6d23def161d4f8c9073ea5cff3c6f87

## Checklist

- [ ] Add tests
- [ ] New files added to `src/tsconfig.strictNullChecks.json` (if possible)
- [ ] Designate a primary reviewer

2023-12-11 21:19 UTC, BLoe approved these changes

2023-12-11 23:49 UTC, twschiller commented
@grahamlangford marking as "do not merge" while we asses the functionality

- Zendesk: https://www.loom.com/share/b45488a9ae9a4ceba9bcc94da9821df6?sid=27bd3d6f-6513-4cf6-a365-190e0973d9c1. It shifts the page, but the case action buttons are still under the sidebar

2023-12-12 09:34 UTC, fregante requested changes

2023-12-12 09:34 UTC, fregante commented on src/contentScript/sidebarDomControllerLite.ts
> +    `calc(100vw - var(${SIDEBAR_WIDTH_CSS_PROPERTY}))`,
Why doesn't `width` already follow the size of `html`? 

I don’t think these changes are necessary, at most probably it should be `width: auto` or `width: 100%` if that's the issue.


`100vw` and `100%` will break if there's margin, padding and varying `box-sizing` behaviors.

2023-12-12 09:41 UTC, fregante commented on src/contentScript/sidebarDomControllerLite.ts
> +const TRANSITION_DURATION = "500ms";
```suggestion
const TRANSITION_DURATION = 500;
```

<img width="667" alt="Screenshot 3" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/c19892a3-98b5-4b54-a0f3-39a868ba5caf">

2023-12-12 14:57 UTC, grahamlangford commented on src/contentScript/sidebarDomControllerLite.ts
> +const TRANSITION_DURATION = "500ms";
Interesting, I missed the error in the console, but the animation still works. Originally had it as just 500, but I changed it for the other locations I used it. I'll revert.

2023-12-12 15:05 UTC, grahamlangford commented on src/contentScript/sidebarDomControllerLite.ts
> +    `calc(100vw - var(${SIDEBAR_WIDTH_CSS_PROPERTY}))`,
> Why doesn't width already follow the size of html?

The sidebar is nested under `html` but not under `body` (React Portal)

> I don’t think these changes are necessary, at most probably it should be width: auto or width: 100% if that's the issue.

Tried both of those first. The above is the only thing I've found that fixes the sidebar on Zendesk

> 100vw and 100% will break if there's margin, padding, border and varying box-sizing behaviors.

I'm pretty sure that's unlikely. Width wouldn't impact padding, and I doubt there's many sites out there that set a margin or border on the `body` element. This hasn't caused problems on any sites I've tested against.

2023-12-12 15:30 UTC, grahamlangford commented on src/contentScript/sidebarDomControllerLite.ts
> +    `calc(100vw - var(${SIDEBAR_WIDTH_CSS_PROPERTY}))`,
It might not matter anyway. I didn't take into account the fact that `position: fixed` always uses the viewport as the containing block. The Zendesk footer is `position:fixed`.

I could overwrite that behavior specifically for Zendesk, but it would still cause problems on other pages. @twschiller I don't think there's going to be a good solution. We may be better off closing this PR.

2023-12-12 15:54 UTC, grahamlangford commented
Closing due to issues making the workaround work with `fixed` positioned elements.

2023-12-12 15:54 UTC, closed without merging