#682: Wait for content script before sending external messages
pixiebrix/pixiebrix-extension pull request #714
Opened 2021-07-06 20:30 UTC by fregante

Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/682

Quick and dirty solution to see what you think about the idea.

Problem:

- The app needs to know whether the extension is ready to receive messages

Solution:

- The extension adds an attribute to the `body` after loading

Explanation:

- The app doesn't have access to `PIXIEBRIX_READY_SYMBOL` and other local variables. Either we have a "very public" marker that the extension has loaded (an attribute) or we have to resort to polling via messages + timeouts, probably. Alternative solutions welcome.

If this is accepted, I'll probably turn the poller into a MutationObserver on `body`

2021-07-07 02:25 UTC, twschiller commented on src/contentScript/context.ts
> +  document.documentElement.dataset.pixieBrixReady = "true";
Could we change to `pbReady` or at least `pixiebrixReady`?

Prior art in favor of `pb-ready`: 
* http://github.com/pixiebrix/pixiebrix-extension/blob/38ad8d2c3095766d3fb3b04284fadd81602b75e3/src/extensionPoints/helpers.ts#L23-L23
* http://github.com/pixiebrix/pixiebrix-extension/blob/38ad8d2c3095766d3fb3b04284fadd81602b75e3/src/extensionPoints/menuItemExtension.ts#L71-L71

In favor of `pixiebrix-ready`:
* http://github.com/pixiebrix/pixiebrix-extension/blob/38ad8d2c3095766d3fb3b04284fadd81602b75e3/src/actionPanel/native.tsx#L81-L81

2021-07-07 02:30 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +      (function check() {
A better name would be `postMessageWhenReady`

Any reason to prefer the current syntax, as opposed to separating the method call from the declaration?

```javascript
function check() {}
check();
```

2021-07-07 02:31 UTC, twschiller commented on src/messaging/external.ts
> +const lift = isChrome ? liftBackground : liftExternal;
💯

2021-07-07 02:32 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    if (isExtensionContext()) {
Should this be `expectExtensionContext()` to match our new expectXXX methods?

2021-07-07 02:36 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +          setTimeout(check, 100);
Lift the 100 out to a constant, e.g., POLL_READY_MS? In general, I prefer to have all configuration knobs as constants at the top of the file (and passing them in as defaults for params where it makes sense)

There's this ESLint rule that I don't think is on right now: https://eslint.org/docs/rules/no-magic-numbers

2021-07-07 02:45 UTC, twschiller commented
> Quick and dirty solution to see what you think about the idea.

I think this makes sense for now. One side is going to have to do polling to prevent races. The alternative way of having the page wait for a message from the content script would require the content script to poll, as otherwise there's a race w/ when the message listener is loaded

> If this is accepted, I'll probably turn the poller into a MutationObserver on body

I think it should be straight-forward and nice way to avoid latency. If it's not straight-forward, let's open a new issue and mark it nice to have since this only impacts 1 screen in the app right now

2021-07-07 18:04 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +      (function check() {
This pattern is my go-to for its simplicity, but the code was just a demo. I replaced it with a more "verbose" (in a good way) promise-based solution.

https://github.com/sindresorhus/p-wait-for is a good module to implement polling with a timeout (includes p-timeout, which we already use)

I ended up going with [`one-mutation`](https://github.com/fregante/one-mutation) though

2021-07-07 18:04 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +    if (isExtensionContext()) {
I'll do so in a separate PR

2021-07-07 18:05 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +          setTimeout(check, 100);
`no-magic-numbers` is interesting in theory but implementing it may be annoying, especially when paired with `security/*`. We can try it if you'd like, at least as a warning.

2021-07-07 18:08 UTC, fregante commented
> * The extension needs to be released before the web app is updated (not a problem though since we don't have live FF enterprise deployments)

Correct me if I'm wrong but this new code is only used by the app, so that order requires no further changes:

1. Extension is updated, adds the attribute
2. App is updated, waits for the attribute

The problem however is that if an old extension tries to connect now, it won't be able to because the app **expects** the attribute.

I solved this issue temporarily by _not_ throwing an error on timeout. I left a comment in the code as well.


> * Add maximum wait so that the message fails if the content script is not ready within a certain amount of time. Ideally this would be the same sort of error/message Firefox sends on other messaging errors when using the runtime

Once we drop the temporary backwards compatibility, the timeout will throw a regular error (TimeoutError) in the lifted function. I assume those errors are already handled. If not I can handle them all as part of a separate issue (maybe #263)

2021-07-07 18:22 UTC, fregante commented
This should be good to go now, I cleaned it as much as possible. It's not tested, do you see any issues?

2021-07-07 19:00 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +    // Wait for the extension to load before sending the message
Before the `Promise.race`, I think there needs to be a check to see if the data attribute is already defined. Otherwise, there's a race condition that if the sequence is the following:

1. Content script sets pb-ready on the body
2. The host page call this method
3. The promise fails with the timeout because the mutation observer never see a mutation

- [ ] Check for attribute before initializing mutation observer

2021-07-07 19:02 UTC, twschiller commented on src/contentScript/externalProtocol.ts
> +          setTimeout(check, 100);
I'll create a separate issue with my thoughts on reasonable defaults (e.g., [ignore default values](https://eslint.org/docs/rules/no-magic-numbers#ignoredefaultvalues))

2021-07-07 19:07 UTC, twschiller approved these changes
> I assume those errors are already handled

They're handled it's just more about converting the TimeoutError message into an error that's more user understandable

I think in this case, the app would just show the extension as not being installed (without an error message)

So we're ok to 🚢  as-is

2021-07-07 19:08 UTC, twschiller requested changes
Accidentally clicked approve. See remaining task about the checking if the attribute is already on the body

2021-07-07 19:29 UTC, fregante commented on src/contentScript/externalProtocol.ts
> +    // Wait for the extension to load before sending the message
Absolutely. I had implemented this via `p-wait-for` initially and that didn't need a pre-check. Fixed now:

- if <html> doesn't have the attribute
	- wait for it or timeout

2021-07-07 19:43 UTC, twschiller approved these changes

2021-07-07 19:43 UTC, twschiller commented
@fregante Go ahead and merge when ready! :shipit:

2021-07-07 19:49 UTC, merged

2021-07-11 15:29 UTC, fregante commented
Has this been deployed to the site? If not, can you? Without this I'm unable to login in Firefox and cannot continue testing other parts of the extension.