Support linking App to Extension beta
pixiebrix/pixiebrix-extension pull request #7313
Opened 2024-01-09 21:36 UTC by johnnymetz

## What does this PR do?

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/4523

## Demo

https://www.loom.com/share/33e4d121da644af29f9ea2107dcc6ec0

## Checklist

- [ ] Add tests
- [x] Designate a primary reviewer: @twschiller

2024-01-09 21:47 UTC, grahamlangford commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
Note: we'll need to update `release.yml` to set the `CHROME_EXTENSION_ID` variable.

2024-01-09 22:02 UTC, grahamlangford approved these changes

2024-01-09 23:01 UTC, twschiller commented on src/contentScript/setExtensionIdInApp.ts
> +void initRuntimeLogging();
I don't think we need this because there's no console logging in this module?

2024-01-10 01:25 UTC, fregante commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
We don't really need to do this, the ID is available natively via `chrome.runtime.id`

2024-01-10 01:25 UTC, fregante commented on src/contentScript/setExtensionIdInApp.ts
> +// https://github.com/pixiebrix/webext-messenger/issues/88
Let's add this file to the "grep" check in ci.yml

2024-01-10 01:25 UTC, fregante commented on scripts/manifest.mjs
> +  addInternalUrlsToContentScripts(manifest, internal);
I don’t think this is necessary? We already have `*://*/*` there

2024-01-10 01:27 UTC, fregante commented on src/contentScript/setExtensionIdInApp.ts
> +void initRuntimeLogging();
I had the same concern, is this needed? I'm afraid it will lead to a duplicate webext-messenger loading

2024-01-10 13:53 UTC, twschiller commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
> We don't really need to do this, the ID is available natively via chrome.runtime.id

That's a great point. @johnnymetz should just use `chrome.runtime.id` here

2024-01-10 13:55 UTC, twschiller requested changes
@johnnymetz changes to make:
- Use `chrome.runtime.id` for the id
- Drop the init logging
- See grep check here that @fregante is referring to: https://github.com/pixiebrix/pixiebrix-extension/blob/c8576e9b529af1f46f1b632ba69eae4a7a097edb/.github/workflows/ci.yml#L93-L93

2024-01-10 15:05 UTC, johnnymetz commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
Looks like `chrome.runtime.id` can't be overridden while `CHROME_EXTENSION_ID` can. We need to override the chrome extension id in some cases (e.g. [test manifest changes](https://www.notion.so/pixiebrix/Testing-Manifest-json-changes-c60283073fba40d98ee28cdeab19b04a?pvs=4#1aeb476f72844605a2089aab838d6659)) so I'm thinking we stick with `CHROME_EXTENSION_ID`. Or is there an easy way to override it that I'm not aware of?

2024-01-10 15:44 UTC, twschiller commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
> Or is there an easy way to override it that I'm not aware of?

Good callout. Setting the `CHROME_MANIFEST_KEY` in the build with force the Chrome extension id that's returned from `chrome.runtime.id`. So for testing manifest changes, it will be slightly more annoying. But overall, using `chrome.runtime.id` will be less error-prone

2024-01-10 17:29 UTC, johnnymetz commented on src/contentScript/setExtensionIdInApp.ts
> +const CHROME_EXTENSION_ID = process.env.CHROME_EXTENSION_ID;
Sounds good. I imagine we probably want to replace all uses of `CHROME_EXTENSION_ID` with `chrome.runtime.id` for consistency. I can make a separate DX ticket for this.

2024-01-10 18:58 UTC, grahamlangford commented
@twschiller can you approve?

2024-01-10 19:07 UTC, twschiller approved these changes

2024-01-10 19:09 UTC, twschiller commented
<img width="684" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/a24c2d04-527a-4b4a-a2da-2b0d78b8d17f">

2024-01-10 19:30 UTC, merged