#570: Extract and deduplicate webpack resolution config
pixiebrix/pixiebrix-extension pull request #761
Opened 2021-07-11 20:58 UTC by fregante

- Fixes #570

This was low priority but the solution was pretty simple:

- extract resolutions into shared file
- point eslint to this file
- import file from both webpack.browsers.js and webpack.scripts.js

In the future:

- [ ] import file from Jest config, maybe as part of #684

2021-07-11 21:05 UTC, fregante commented on .eslintrc
>      // "plugin:import/errors",
This PR does not attempt to lint the codebase, so I can't enable this preset yet because it will fail the build. Also it's just possible that it's because YAML isn't working with eslint even without the shared configuration. Example:

```
   24:3   error    Schema not found in '@cfworker/json-schema'                                                                                                                                                                                                                    import/named
   25:3   error    ValidationResult not found in '@cfworker/json-schema'                                                                                                                                                                                                          import/named
```

2021-07-11 23:39 UTC, twschiller commented on .eslintrc
>      // "plugin:import/errors",
> that it's because YAML isn't working with eslint

The `@cfworker/json-schema` package is written in Typescript: https://github.com/cfworker/cfworker/tree/main/packages/json-schema/src

Not sure what you mean by YAML isn't working?

2021-07-11 23:40 UTC, twschiller commented on browsers/resolve.config.js
> +    // Need to set these fields manually as their default values rely on `web` target.
This comment should be back in the other file as it refers to

```
mainFields: ["browser", "module", "main"],
aliasFields: ["browser"],
```

2021-07-11 23:41 UTC, twschiller commented on scripts/webpack.scripts.js
> +const { resolve: sharedResolutions } = require("../browsers/resolve.config.js");
Any particular reason to rename this to sharedResolutions instead of just using resolve?

2021-07-11 23:42 UTC, twschiller requested changes
Move the comment back to avoid future confusion: https://github.com/pixiebrix/pixiebrix-extension/pull/761#discussion_r667552368

2021-07-12 03:58 UTC, fregante commented on scripts/webpack.scripts.js
> +const { resolve: sharedResolutions } = require("../browsers/resolve.config.js");
Actually I used `resolve` exactly that way but thought you'd have preferred a more specific variable name 😅

2021-07-12 11:37 UTC, fregante commented on .eslintrc
>      // "plugin:import/errors",
> YAML isn't working with eslint

I mean that `import './file.yaml'` has a behavior defined by a webpack loader, it means nothing in node/JS, and my guess was that those imports were causing errors with this plugin for this reason.

However the errors were because the `import/named` rule doesn't understand type imports. `Schema` is just a type and it cannot find it. Since these are handled by TypeScript, I now disabled the rule.

I ended up fixing the one remaining issue so `import/errors` is now fully enabled.

2021-07-12 11:40 UTC, fregante commented on src/blocks/readers/index.ts
> +import "./ElementReader";
These files don't actually export anything so a rule was rightfully being reported:

```
No named exports found in module './meta'.eslint(import/export)
```

2021-07-12 14:39 UTC, twschiller approved these changes

2021-07-12 14:40 UTC, twschiller commented
@fregante Approved - go ahead an merge when ready 

![image](https://user-images.githubusercontent.com/1879821/125306832-89b6e480-e2fd-11eb-9c5d-06edbd5e215f.png)

2021-07-12 14:54 UTC, merged

2021-07-12 14:54 UTC, fregante commented
That's a _charming_ way to say ":shipit:"