Sidepanel open check failing in some browsers
pixiebrix/pixiebrix-extension pull request #8271
Opened 2024-04-17 15:44 UTC by grahamlangford

## What does this PR do?

- Potentially fixes an issue where the side panel would hang in a loading state with the reserved panels showing

## Discussion

- I've never been able to reproduce the issue (on Mac or Windows via Parallel)
- When the width check ever returns false, side panel hangs
- In customer calls, we were able to determine that  the sidebar was being reported as not visible

#### Important
- I'm not sure about the performance implications of always pinging
    - `SIDEBAR_PING` is a `noop`, but we're still increasing the number of messenger calls
    - We always ping using the messenger when we think the side panel might be open, though, so it's probably ok
- Alternatively, we could try reducing the `MINIMUM_SIDEBAR_WIDTH`, but as it is already 300, I don't think that would help. It's possible that something is going wrong with the inner and outer width checks 

## Checklist

- [x] Designate a primary reviewer @twschiller

2024-04-17 15:45 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> -}
Relocated function closer to the call site since it's no longer used by `isSidePanelOpenMv3`

2024-04-17 16:09 UTC, twschiller commented on src/contentScript/sidebarController.tsx
> +  return window.outerWidth - window.innerWidth > MINIMUM_SIDEBAR_WIDTH
I don't know much about outerWidth/innerWidth. Should we just be saying if there's any difference then it's unknown?

2024-04-17 16:15 UTC, twschiller commented on src/contentScript/sidebarController.tsx
> + * Determines whether the sidebar is open.
Provide some comment on when this should be used vs. other ways to determine?

2024-04-17 16:23 UTC, fungairino commented on src/contentScript/sidebarController.tsx
> +  return window.outerWidth - window.innerWidth > MINIMUM_SIDEBAR_WIDTH
It does seem like on my machine + chrome, the outerWidth is always equal to the inner width. However, I could imagine that could not be the case on different OS's / Edge. Ex. if you have a persistent scrollbar or not.

2024-04-17 16:25 UTC, fungairino commented
Can we ping the w3c folks on this feature request so we don't have to make such a hack? 😅
https://github.com/w3c/webextensions/issues/517

2024-04-17 16:29 UTC, fungairino commented
Maybe relevant? https://codereview.stackexchange.com/questions/213760/window-innerwidth-workaround-for-when-it-returns-the-wrong-value

2024-04-17 17:15 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +  return window.outerWidth - window.innerWidth > MINIMUM_SIDEBAR_WIDTH
We could potentially change to `window.outerWidth > window.innerWidth`. I'm not 100% confident here since I've never been able to reproduce. I think this failing is far less likely to be problematic when called by `sidePanelOnCloseSignal`, which is the only remaining usage of `isSidePanelOpenSync` in this PR

2024-04-17 18:25 UTC, fungairino commented on src/contentScript/sidebarController.tsx
> +  }, 500) as () => Promise<void>,
Why the bump down to 500 here, and still using 1000 above in isSidePanelOpenMV3?

2024-04-17 20:40 UTC, fungairino approved these changes

2024-04-18 00:10 UTC, fregante requested changes

2024-04-18 00:10 UTC, fregante commented on src/contentScript/sidebarController.tsx
> +function isSidePanelOpenSync(): false | "unknown" {
If this function is not reliable, then it should just be dropped. I don’t think there's a scenario in which we *need* it to be sync, right?

2024-04-18 00:10 UTC, fregante commented on src/contentScript/sidebarController.tsx
> +    throttle(async () => {
These aren't hooks, they're being used incorrectly.

- two `isSidePanelOpenMv3()` will still send two messages
- same for `throttle`

You're probably looking for:

```js
const isSidePanelOpenMv3 = throttle(memoizeUntilSettled(fn));
```

2024-04-18 00:12 UTC, fregante commented on src/contentScript/sidebarController.tsx
> +    throttle(async () => {
Now that I look at the file, isn't the `pingSidebar` function above identical? It's immediately below, it can just be changed to return a Boolean maybe

2024-04-18 12:07 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +  }, 500) as () => Promise<void>,
Modified the wrong timeout by mistake. Good catch

2024-04-18 12:15 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +function isSidePanelOpenSync(): false | "unknown" {
I was avoiding making changes to `sidePanelOnCloseSignal`, but it's should be safe. I'll drop it.

2024-04-18 12:19 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +    throttle(async () => {
This was my initial inclination, but I assumed the original implementation used `messenger` directly for a reason.

2024-04-18 12:23 UTC, fregante approved these changes

2024-04-18 12:23 UTC, fregante commented on src/contentScript/sidebarController.tsx
> +// This method is exclusive to the content script, don't export it
Outdated now that it doesn't use the DOM/`window`, it can be called from anywhere

2024-04-18 14:49 UTC, fungairino approved these changes

2024-04-18 14:56 UTC, merged