run e2e tests for beta-release unless skipped
pixiebrix/pixiebrix-extension pull request #8350
Opened 2024-04-25 20:30 UTC by grahamlangford

## What does this PR do?

- Part of #8343

## Reviewer Tips

- Changes in ci.yaml and release.yaml were just cleanup

## Checklist

- [x] Designate a primary reviewer @fungairino

2024-04-25 20:32 UTC, fungairino approved these changes

2024-04-26 15:49 UTC, mnholtz commented
I made some changes to env variables recently that this branch will probably need to pull in. Merging with main to look into fixing that

2024-04-26 17:39 UTC, mnholtz commented on .github/workflows/beta-release.yaml
> +      REQUIRE_OPTIONAL_PERMISSIONS_IN_MANIFEST: 1
Now that I'm looking at this, where is the test username/password?

2024-04-26 17:41 UTC, mnholtz requested changes
Sorry, maybe I'm misunderstanding something. But I don't see `E2E_TEST_USER_EMAIL_UNAFFILIATED` or `E2E_TEST_USER_PASSWORD_UNAFFILIATED`.

Also, I want to make sure that we update the required env variables per changes made in https://github.com/pixiebrix/pixiebrix-extension/pull/8341

In particular, I think we'll need to add ` DEV_EVENT_TELEMETRY` and `DATADOG_CLIENT_TOKEN`

2024-04-29 14:47 UTC, twschiller commented
@grahamlangford see @mnholtz's change request comments

2024-04-29 17:09 UTC, grahamlangford commented
> Sorry, maybe I'm misunderstanding something. But I don't see `E2E_TEST_USER_EMAIL_UNAFFILIATED` or `E2E_TEST_USER_PASSWORD_UNAFFILIATED`.
> 
> Also, I want to make sure that we update the required env variables per changes made in #8341
> 
> In particular, I think we'll need to add ` DEV_EVENT_TELEMETRY` and `DATADOG_CLIENT_TOKEN`

Done. `DATADOG_CLIENT_TOKEN` was already included

2024-04-29 23:39 UTC, mnholtz approved these changes

2024-04-30 14:28 UTC, merged