Feature/846 validate dom nesting warning
pixiebrix/pixiebrix-extension pull request #884
Opened 2021-07-21 00:37 UTC by mnholtz

This fixes #846 by adding extra conditional rendering to a Page component description. Specifically, this will render the description wrapped in <p> tags if the description is a String object, otherwise it will render as-is.

2021-07-21 02:08 UTC, twschiller commented on src/layout/Page.tsx
> +              (description instanceof String ? (
I think we actually need to use `typeof description === "string"` here. `instanceof` doesn't work with primitive types. See discussion at: https://stackoverflow.com/questions/899574/what-is-the-difference-between-typeof-and-instanceof-and-when-should-one-be-used?rq=1

Also, let's try to avoid nested expressions like this (&& + ternary) since they're hard to read

I think you might just be able to do 

```
{typeof description === "string" ? <p>{description}</p> : description}
```

I'm not sure, but React might yell at you if description is `undefined`. If it does you could default description to `null` in the params for the method

```
({ icon, title, breadcrumb, toolbar, description = null, children }) => {
```

2021-07-21 02:10 UTC, twschiller requested changes
See comment on using typeof of primitive types

2021-07-21 11:31 UTC, twschiller commented
@mnholtz Let's also use this as an opportunity to put the `Page` component in our [Storybook](https://storybook.js.org/)

You can see this file for an example of a Story: http://github.com/pixiebrix/pixiebrix-extension/blob/58bd065d514a3710252abc9ad094874beb8ede0e/src/components/AsyncButton.stories.tsx#L22-L22

To run storybook, you run the following at the root of the repo:

```
npm run storybook
```

Here's a quick Tutorial on Storybook as well: https://storybook.js.org/tutorials/intro-to-storybook/react/en/simple-component/

2021-07-21 16:44 UTC, fregante commented on src/layout/Page.tsx
> +              (description instanceof String ? (
> string primitives are "[temporarily converted to String objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#:~:text=JavaScript%20automatically%20converts%20primitives%20to%20String%20objects%2C%20so%20that%20it%27s%20possible%20to%20use%20String%20object%20methods%20for%20primitive%20strings.)"

That's some crazy behavior that leads some people to think that every primitive is actually an `object`, but it really isn't. This is why `'string'.foo = 4` does not persist on that string.

2021-07-21 22:12 UTC, mnholtz commented on .storybook/preview.js
> +library.add(faMusic);
Not sure if this is the best way to solve this. Font Awesome icons were not rendering on for Page component with imports for individual components. This issue [has been seen in the past](https://github.com/storybookjs/storybook/issues/3798), the workaround for which are global imports for specific icons for Storybook.

2021-07-21 22:16 UTC, mnholtz commented on .storybook/preview.js
> +library.add(faMusic);
Additionally, icons are rendering off-center. Not sure the cause of this yet.
<img width="182" alt="Screen Shot 2021-07-21 at 3 13 58 PM" src="https://user-images.githubusercontent.com/36575242/126567046-fab118c8-4700-4f4d-a6c1-5f0980b2b146.png">

2021-07-21 22:25 UTC, mnholtz commented on src/components/AsyncButton.stories.tsx
> +      options: ["primary", "secondary", "info", "warning", "danger"],
control.options is deprecated: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-controloptions

2021-07-22 00:16 UTC, twschiller commented on .storybook/preview.js
> +library.add(faMusic);
Could you add a comment to the code with a link to that issue? In general if there's some insight/external bug that causes us to do something in an unnatural way, we should document it in the code

It's not the just the icon that's off the. The header text vertical alignment is also off. I took a quick look, but couldn't spot what it is immediately. They both have the same text baseline, which is the vertical middle

2021-07-22 00:17 UTC, twschiller commented on src/layout/Page.stories.tsx
> +export const Default = Template.bind({});
Take a look at for an example of how to write the TypeScript types: http://github.com/pixiebrix/pixiebrix-extension/blob/bfea5df9b2d1205ea3b2087d150b12ec0f8fedea/src/components/AsyncButton.stories.tsx#L43-L43

2021-07-22 16:38 UTC, mnholtz commented on .storybook/preview.js
> +library.add(faMusic);
Ah, I found it. [Overrides.css](https://github.com/pixiebrix/pixiebrix-extension/blob/1ebb8499be072346fd5339694c198aa87364f0c3/src/vendors/overrides.scss#L1-L1) isn't being included in the storybook render.

2021-07-22 16:43 UTC, mnholtz commented on .storybook/preview.js
> +library.add(faMusic);
> Could you add a comment to the code with a link to that issue?

Done.

2021-07-22 19:12 UTC, twschiller approved these changes

2021-07-22 19:12 UTC, merged