#8976: show sidebar brick not showing active tab
pixiebrix/pixiebrix-extension pull request #8987
Opened 2024-08-08 18:08 UTC by grahamlangford

## What does this PR do?

- Closes #8976 

## Demo

- Coming Soon

For more information on our expectations for the PR process, see the
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs=4)

2024-08-08 18:09 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +  activateOptions: ActivatePanelOptions,
Unnecessary, activateOptions should always be defined

2024-08-08 18:09 UTC, grahamlangford commented on src/contentScript/sidebarController.tsx
> +    await sidebarInThisTab.activatePanel(getTimedSequence(), activateOptions);
Unnecessary spread

2024-08-08 18:10 UTC, grahamlangford commented on src/sidebar/protocol.tsx
> +  activateOptions: ActivatePanelOptions,
Just renaming for consistency

2024-08-08 18:31 UTC, grahamlangford commented on src/store/sidebar/sidebarSlice.ts
> +      if (!payload.force && !isModLauncherOnlyTabVisible) {
This is the fix

2024-08-09 14:36 UTC, fungairino commented
Does any documentation need to be updated (or description around the force field)?

2024-08-09 14:37 UTC, fungairino approved these changes

2024-08-09 14:44 UTC, twschiller commented
> Does any documentation need to be updated (or description around the force field)?

I don't think so? This PR is fixing behavior that was buggy w.r.t. expectations: https://www.notion.so/pixiebrix/8976-show-sidebar-specification-54cb74ac3170407da2bdaa861fc62ea0?pvs=4

2024-08-09 14:44 UTC, twschiller commented on src/bricks/effects/sidebarEffects.ts
> +      forcePanel = true,
@grahamlangford This is a backward incompatible change

2024-08-09 14:47 UTC, twschiller requested changes
Flagging backward-incompatible change for existing bricks with forcePanel excluded: https://github.com/pixiebrix/pixiebrix-extension/pull/8987/files#r1711602209

I'm open to making the change (as I doubt it will have a big impact and is probably what people already expect, but flagging to at least have the discussion)

2024-08-09 15:17 UTC, grahamlangford commented on src/bricks/effects/sidebarEffects.ts
> +      forcePanel = true,
You're right. I should have caught that. Got a little trigger happy with the switch. I'll revert and update getExampleBrickConfig

2024-08-09 16:08 UTC, twschiller approved these changes
Consider setting example brick config as necessary

2024-08-09 16:20 UTC, merged