794 copy to clipboard accepts numbers and bools
pixiebrix/pixiebrix-extension pull request #901
Opened 2021-07-23 23:16 UTC by mnholtz

Resolves #794 and also resolves #900

This adds additional boolean and number types to the JSON schema for Alert and CopyToClipboard blocks, to prevent unintentional type errors when building up actions.

2021-07-23 23:32 UTC, twschiller commented on src/blocks/effects/clipboard.ts
> +        type: ["string", "boolean"],
We'll also want to support number here too

2021-07-23 23:32 UTC, twschiller requested changes
Support number for clipboard too

2021-07-26 15:33 UTC, mnholtz commented on src/blocks/effects/clipboard.ts
> +        type: ["string", "boolean"],
Oops, my bad.

2021-07-26 21:19 UTC, twschiller approved these changes

2021-07-26 21:19 UTC, merged