Avoid overflow on setup page
pixiebrix/pixiebrix-extension pull request #903
Opened 2021-07-24 06:25 UTC by fregante

1. Install extension
2. Resize window to about 1000px

## Before

<img width="1003" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/126859628-1e7d8222-71d9-4b74-98a4-c1dce347ab33.png">

## After

<img width="1002" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/126859660-fc775a9a-49d9-40f2-80ac-6e7dd9f0155b.png">

<img width="50" src="https://user-images.githubusercontent.com/1402241/126859634-4792c0e8-9de1-46a1-a97c-e5fb594db2f4.jpg">

2021-07-26 15:37 UTC, twschiller commented on src/options/pages/SetupPage.scss
> -      height: 115px;
I think this should be `min-height`. IIRC the original intent was to make sure the rows were equally sized

2021-07-26 15:37 UTC, twschiller submitted a review, later dismissed
Use `min-height` instead of removing height completely

2021-07-26 15:38 UTC, twschiller requested changes
Use min-height instead of removing height completely

2021-07-26 15:47 UTC, fregante commented on src/options/pages/SetupPage.scss
> -      height: 115px;
I think it's not a good look:

<img width="857" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/127018407-1056f3be-53c5-4512-a930-0b249a9ec6ad.png">

compared to:

<img width="878" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/127018396-37017fd2-0930-47ce-a1ae-a2e5e777dbac.png">


since the extra space makes it look like something is missing IMO. But can add it anyway

```suggestion
      min-height: 115px;
```

2021-07-27 13:01 UTC, twschiller commented on src/options/pages/SetupPage.scss
> -      height: 115px;
@MMirandi any preference on spacing?

2021-07-27 13:07 UTC, MMirandi commented on src/options/pages/SetupPage.scss
> -      height: 115px;
@twschiller I like @fregante's suggestion of removing the extra space in the first row.

2021-07-27 13:07 UTC, twschiller commented on src/options/pages/SetupPage.scss
> -      height: 115px;
@fregante fire away!

2021-07-27 13:08 UTC, twschiller approved these changes

2021-07-27 13:08 UTC, merged