Use real links wherever possible
pixiebrix/pixiebrix-extension pull request #907
Opened 2021-07-24 10:36 UTC by fregante

- Fixes #906 

Also tested in Chrome. Let's try to use real links wherever possible. `chrome-extension://` aren't clickable only on the web (and even then we can inject a generic handler on `app.pixiebrix.com` to handle them as regular links, instead of creating a function for each)

![gif](https://user-images.githubusercontent.com/1402241/126865800-2ca25205-4faa-4b47-86e1-e4aa35257f20.gif)

2021-07-24 11:56 UTC, fregante commented on src/actionPanel/ActionPanelApp.tsx
> -import { openExtensionOptions } from "@/messaging/external";
I just realized that this was failing because it's an _external_ API, meaning it's not supposed to be used from within the extension. It broke in Firefox because the external part was only used there:

https://github.com/pixiebrix/pixiebrix-extension/blob/ede30e8e08065622ce659d1119fc296b8ac771b3/src/messaging/external.ts#L28

2021-07-24 12:05 UTC, fregante commented on src/devTools/editor/sidebar/Sidebar.tsx
> +            target="_blank"
<table>
<tr>
	<td>😣✋ 
	<td>span[onClick]
<tr>
	<td>😌👉 
	<td>a[href]
</table>

This was also broken (Firefox)

<img width="264" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/126867819-c09e3517-c9d4-41da-97cf-179ad4492762.png">

Tested in both Chrome and Firefox

2021-07-24 12:06 UTC, fregante commented on src/actionPanel/ActionPanelApp.tsx
> -import { openExtensionOptions } from "@/messaging/external";
I think that `openExtensionOptions` is the only wrongly-used API here, I don't see anything else.

2021-07-26 14:36 UTC, twschiller commented
There's an a11y eslint ruleset for react we should probably enable sooner than later: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md

This would catch cases like this

2021-07-26 14:38 UTC, twschiller commented on src/actionPanel/ActionPanelApp.tsx
> -import { openExtensionOptions } from "@/messaging/external";
You're correct that it's the wrong method to call, and just happens to work on Chrome b/c of it's the same API that gets called under the hood

I think your approach of changing it to a link with href is the correct way to go

2021-07-26 14:42 UTC, twschiller requested changes
Look at passing `as="a"` to the Button component if it's not already rendering the elements as "a" tag

2021-07-26 15:23 UTC, fregante commented
> we should probably enable sooner than later

🎉 



> Look at passing `as="a"` to the Button component if it's not already rendering the elements as "a" tag

It's implied by the `href`: https://react-bootstrap.github.io/components/buttons/#button-tags

> adding a `href` prop will automatically render an `<a />` element

2021-07-26 15:25 UTC, fregante commented on src/actionPanel/ActionPanelApp.tsx
> -import { openExtensionOptions } from "@/messaging/external";
It works because `href` causes the button to turn into an `a`, as it's the only HTML element that supports it.

> adding a `href` prop will automatically render an `<a />` element

2021-07-26 15:25 UTC, twschiller commented on src/actionPanel/DefaultActionPanel.tsx
> +          target="_blank"
Codacy has a fix for the issue: [Functions that return promises must be async.](https://app.codacy.com/gh/pixiebrix/pixiebrix-extension/pullRequest?prid=7805688)
```suggestion
          <Button onClick={async () => openExtensionOptions()} variant="info">
```

2021-07-26 15:28 UTC, twschiller commented on src/actionPanel/DefaultActionPanel.tsx
> +          <Button onClick={async () => openExtensionOptions()} variant="info">
Codacy has a fix for the issue: [Functions that return promises must be async.](https://app.codacy.com/gh/pixiebrix/pixiebrix-extension/pullRequest?prid=7805688)
```suggestion
          <Button onClick={async () => openExtensionOptions()} variant="info">
```

2021-07-26 16:14 UTC, twschiller approved these changes

2021-07-26 16:15 UTC, merged